name = "entryvine-event-frontend"
compatibility_date = "2026-06-28"
pages_build_output_dir = "dist"

[vars]
VITE_BACKEND_URL = "https://entryvine-backend.onrender.com"
VITE_PORTAL = "public"
VITE_GOOGLE_CLIENT_ID = "809405355784-1nbp56vsdqmutsrmmd8gv7svq414k7um.apps.googleusercontent.com"
VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_51Tlz6bFZVzzNl3AmtNp0iv1D8rxjx8PkQdac3esOfiZIwPcYMwIRk3HXTjYfgdkY8ukIRJ7hEDa2QvUq5KGvUhev00QwRLUidw"
