/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "admin.proto" (package "entryvine.admin", syntax proto3)
// tslint:disable
import { HealthService } from "./admin";
import type { HealthStatus } from "./admin";
import { PlatformLeadService } from "./admin";
import type { ListPlatformLeadsResponse } from "./admin";
import type { CreatePlatformLeadRequest } from "./admin";
import { FeedbackService } from "./admin";
import type { ListFeedbackResponse } from "./admin";
import type { CreateFeedbackRequest } from "./admin";
import { LogService } from "./admin";
import type { ClientErrorBatch } from "./admin";
import type { ResolveErrorLogRequest } from "./admin";
import type { ErrorLogStats } from "./admin";
import type { ErrorLogPage } from "./admin";
import type { ErrorLogQuery } from "./admin";
import type { LogPage } from "./admin";
import type { LogQuery } from "./admin";
import { InvitationService } from "./admin";
import type { ListInvitationsResponse } from "./admin";
import type { PageRequest } from "./common";
import type { AcceptInvitationRequest } from "./admin";
import type { CreateInvitationRequest } from "./admin";
import { StaffService } from "./admin";
import type { AddOrInviteStaffResponse } from "./admin";
import type { AddOrInviteStaffRequest } from "./admin";
import type { AssignStaffByEmailResponse } from "./admin";
import type { AssignStaffByEmailRequest } from "./admin";
import type { AckResponse } from "./common";
import type { AssignStaffRequest } from "./admin";
import type { ListStaffResponse } from "./admin";
import { FinancialService } from "./admin";
import type { StripeOnboardingLink } from "./admin";
import type { StripeStatus } from "./admin";
import type { UuidValue } from "./common";
import type { MonthlyReport } from "./admin";
import type { MonthlyReportRequest } from "./admin";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DashboardService } from "./admin";
import type { DeveloperDashboard } from "./admin";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AdminDashboard } from "./admin";
import type { Empty } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service entryvine.admin.DashboardService
 */
export interface IDashboardServiceClient {
    /**
     * @generated from protobuf rpc: GetAdminDashboard(entryvine.common.Empty) returns (entryvine.admin.AdminDashboard);
     */
    getAdminDashboard(input: Empty, options?: RpcOptions): UnaryCall<Empty, AdminDashboard>;
    /**
     * @generated from protobuf rpc: GetDeveloperDashboard(entryvine.common.Empty) returns (entryvine.admin.DeveloperDashboard);
     */
    getDeveloperDashboard(input: Empty, options?: RpcOptions): UnaryCall<Empty, DeveloperDashboard>;
}
/**
 * @generated from protobuf service entryvine.admin.DashboardService
 */
export class DashboardServiceClient implements IDashboardServiceClient, ServiceInfo {
    typeName = DashboardService.typeName;
    methods = DashboardService.methods;
    options = DashboardService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAdminDashboard(entryvine.common.Empty) returns (entryvine.admin.AdminDashboard);
     */
    getAdminDashboard(input: Empty, options?: RpcOptions): UnaryCall<Empty, AdminDashboard> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, AdminDashboard>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDeveloperDashboard(entryvine.common.Empty) returns (entryvine.admin.DeveloperDashboard);
     */
    getDeveloperDashboard(input: Empty, options?: RpcOptions): UnaryCall<Empty, DeveloperDashboard> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, DeveloperDashboard>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service entryvine.admin.FinancialService
 */
export interface IFinancialServiceClient {
    /**
     * @generated from protobuf rpc: GetMonthlyReport(entryvine.admin.MonthlyReportRequest) returns (entryvine.admin.MonthlyReport);
     */
    getMonthlyReport(input: MonthlyReportRequest, options?: RpcOptions): UnaryCall<MonthlyReportRequest, MonthlyReport>;
    /**
     * @generated from protobuf rpc: GetStripeStatus(entryvine.common.UuidValue) returns (entryvine.admin.StripeStatus);
     */
    getStripeStatus(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, StripeStatus>;
    /**
     * @generated from protobuf rpc: StartStripeOnboarding(entryvine.common.UuidValue) returns (entryvine.admin.StripeOnboardingLink);
     */
    startStripeOnboarding(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, StripeOnboardingLink>;
}
/**
 * @generated from protobuf service entryvine.admin.FinancialService
 */
export class FinancialServiceClient implements IFinancialServiceClient, ServiceInfo {
    typeName = FinancialService.typeName;
    methods = FinancialService.methods;
    options = FinancialService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetMonthlyReport(entryvine.admin.MonthlyReportRequest) returns (entryvine.admin.MonthlyReport);
     */
    getMonthlyReport(input: MonthlyReportRequest, options?: RpcOptions): UnaryCall<MonthlyReportRequest, MonthlyReport> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<MonthlyReportRequest, MonthlyReport>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetStripeStatus(entryvine.common.UuidValue) returns (entryvine.admin.StripeStatus);
     */
    getStripeStatus(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, StripeStatus> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, StripeStatus>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StartStripeOnboarding(entryvine.common.UuidValue) returns (entryvine.admin.StripeOnboardingLink);
     */
    startStripeOnboarding(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, StripeOnboardingLink> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, StripeOnboardingLink>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service entryvine.admin.StaffService
 */
export interface IStaffServiceClient {
    /**
     * @generated from protobuf rpc: ListStaffForEvent(entryvine.common.UuidValue) returns (entryvine.admin.ListStaffResponse);
     */
    listStaffForEvent(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListStaffResponse>;
    /**
     * @generated from protobuf rpc: AssignStaff(entryvine.admin.AssignStaffRequest) returns (entryvine.common.AckResponse);
     */
    assignStaff(input: AssignStaffRequest, options?: RpcOptions): UnaryCall<AssignStaffRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: UnassignStaff(entryvine.admin.AssignStaffRequest) returns (entryvine.common.AckResponse);
     */
    unassignStaff(input: AssignStaffRequest, options?: RpcOptions): UnaryCall<AssignStaffRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListAllStaff(entryvine.common.Empty) returns (entryvine.admin.ListStaffResponse);
     */
    listAllStaff(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListStaffResponse>;
    /**
     * @generated from protobuf rpc: AssignStaffByEmail(entryvine.admin.AssignStaffByEmailRequest) returns (entryvine.admin.AssignStaffByEmailResponse);
     */
    assignStaffByEmail(input: AssignStaffByEmailRequest, options?: RpcOptions): UnaryCall<AssignStaffByEmailRequest, AssignStaffByEmailResponse>;
    /**
     * @generated from protobuf rpc: AddOrInviteStaff(entryvine.admin.AddOrInviteStaffRequest) returns (entryvine.admin.AddOrInviteStaffResponse);
     */
    addOrInviteStaff(input: AddOrInviteStaffRequest, options?: RpcOptions): UnaryCall<AddOrInviteStaffRequest, AddOrInviteStaffResponse>;
    /**
     * @generated from protobuf rpc: RemoveStaffRole(entryvine.common.UuidValue) returns (entryvine.common.AckResponse);
     */
    removeStaffRole(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
}
/**
 * @generated from protobuf service entryvine.admin.StaffService
 */
export class StaffServiceClient implements IStaffServiceClient, ServiceInfo {
    typeName = StaffService.typeName;
    methods = StaffService.methods;
    options = StaffService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListStaffForEvent(entryvine.common.UuidValue) returns (entryvine.admin.ListStaffResponse);
     */
    listStaffForEvent(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListStaffResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, ListStaffResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AssignStaff(entryvine.admin.AssignStaffRequest) returns (entryvine.common.AckResponse);
     */
    assignStaff(input: AssignStaffRequest, options?: RpcOptions): UnaryCall<AssignStaffRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AssignStaffRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnassignStaff(entryvine.admin.AssignStaffRequest) returns (entryvine.common.AckResponse);
     */
    unassignStaff(input: AssignStaffRequest, options?: RpcOptions): UnaryCall<AssignStaffRequest, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<AssignStaffRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAllStaff(entryvine.common.Empty) returns (entryvine.admin.ListStaffResponse);
     */
    listAllStaff(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListStaffResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ListStaffResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AssignStaffByEmail(entryvine.admin.AssignStaffByEmailRequest) returns (entryvine.admin.AssignStaffByEmailResponse);
     */
    assignStaffByEmail(input: AssignStaffByEmailRequest, options?: RpcOptions): UnaryCall<AssignStaffByEmailRequest, AssignStaffByEmailResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<AssignStaffByEmailRequest, AssignStaffByEmailResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddOrInviteStaff(entryvine.admin.AddOrInviteStaffRequest) returns (entryvine.admin.AddOrInviteStaffResponse);
     */
    addOrInviteStaff(input: AddOrInviteStaffRequest, options?: RpcOptions): UnaryCall<AddOrInviteStaffRequest, AddOrInviteStaffResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddOrInviteStaffRequest, AddOrInviteStaffResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveStaffRole(entryvine.common.UuidValue) returns (entryvine.common.AckResponse);
     */
    removeStaffRole(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service entryvine.admin.InvitationService
 */
export interface IInvitationServiceClient {
    /**
     * @generated from protobuf rpc: CreateInvitation(entryvine.admin.CreateInvitationRequest) returns (entryvine.common.UuidValue);
     */
    createInvitation(input: CreateInvitationRequest, options?: RpcOptions): UnaryCall<CreateInvitationRequest, UuidValue>;
    /**
     * @generated from protobuf rpc: AcceptInvitation(entryvine.admin.AcceptInvitationRequest) returns (entryvine.common.AckResponse);
     */
    acceptInvitation(input: AcceptInvitationRequest, options?: RpcOptions): UnaryCall<AcceptInvitationRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: RevokeInvitation(entryvine.common.UuidValue) returns (entryvine.common.AckResponse);
     */
    revokeInvitation(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: ListInvitations(entryvine.common.PageRequest) returns (entryvine.admin.ListInvitationsResponse);
     */
    listInvitations(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, ListInvitationsResponse>;
}
/**
 * @generated from protobuf service entryvine.admin.InvitationService
 */
export class InvitationServiceClient implements IInvitationServiceClient, ServiceInfo {
    typeName = InvitationService.typeName;
    methods = InvitationService.methods;
    options = InvitationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateInvitation(entryvine.admin.CreateInvitationRequest) returns (entryvine.common.UuidValue);
     */
    createInvitation(input: CreateInvitationRequest, options?: RpcOptions): UnaryCall<CreateInvitationRequest, UuidValue> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateInvitationRequest, UuidValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AcceptInvitation(entryvine.admin.AcceptInvitationRequest) returns (entryvine.common.AckResponse);
     */
    acceptInvitation(input: AcceptInvitationRequest, options?: RpcOptions): UnaryCall<AcceptInvitationRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AcceptInvitationRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RevokeInvitation(entryvine.common.UuidValue) returns (entryvine.common.AckResponse);
     */
    revokeInvitation(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListInvitations(entryvine.common.PageRequest) returns (entryvine.admin.ListInvitationsResponse);
     */
    listInvitations(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, ListInvitationsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<PageRequest, ListInvitationsResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service entryvine.admin.LogService
 */
export interface ILogServiceClient {
    /**
     * @generated from protobuf rpc: GetAdminLogs(entryvine.admin.LogQuery) returns (entryvine.admin.LogPage);
     */
    getAdminLogs(input: LogQuery, options?: RpcOptions): UnaryCall<LogQuery, LogPage>;
    /**
     * @generated from protobuf rpc: GetDeveloperLogs(entryvine.admin.LogQuery) returns (entryvine.admin.LogPage);
     */
    getDeveloperLogs(input: LogQuery, options?: RpcOptions): UnaryCall<LogQuery, LogPage>;
    /**
     * @generated from protobuf rpc: GetSystemLogs(entryvine.admin.LogQuery) returns (entryvine.admin.LogPage);
     */
    getSystemLogs(input: LogQuery, options?: RpcOptions): UnaryCall<LogQuery, LogPage>;
    /**
     * @generated from protobuf rpc: GetErrorLogs(entryvine.admin.ErrorLogQuery) returns (entryvine.admin.ErrorLogPage);
     */
    getErrorLogs(input: ErrorLogQuery, options?: RpcOptions): UnaryCall<ErrorLogQuery, ErrorLogPage>;
    /**
     * @generated from protobuf rpc: GetErrorLogStats(entryvine.common.Empty) returns (entryvine.admin.ErrorLogStats);
     */
    getErrorLogStats(input: Empty, options?: RpcOptions): UnaryCall<Empty, ErrorLogStats>;
    /**
     * @generated from protobuf rpc: ResolveErrorLog(entryvine.admin.ResolveErrorLogRequest) returns (entryvine.common.AckResponse);
     */
    resolveErrorLog(input: ResolveErrorLogRequest, options?: RpcOptions): UnaryCall<ResolveErrorLogRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ReportClientErrors(entryvine.admin.ClientErrorBatch) returns (entryvine.common.AckResponse);
     */
    reportClientErrors(input: ClientErrorBatch, options?: RpcOptions): UnaryCall<ClientErrorBatch, AckResponse>;
}
/**
 * @generated from protobuf service entryvine.admin.LogService
 */
export class LogServiceClient implements ILogServiceClient, ServiceInfo {
    typeName = LogService.typeName;
    methods = LogService.methods;
    options = LogService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAdminLogs(entryvine.admin.LogQuery) returns (entryvine.admin.LogPage);
     */
    getAdminLogs(input: LogQuery, options?: RpcOptions): UnaryCall<LogQuery, LogPage> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogQuery, LogPage>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDeveloperLogs(entryvine.admin.LogQuery) returns (entryvine.admin.LogPage);
     */
    getDeveloperLogs(input: LogQuery, options?: RpcOptions): UnaryCall<LogQuery, LogPage> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogQuery, LogPage>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSystemLogs(entryvine.admin.LogQuery) returns (entryvine.admin.LogPage);
     */
    getSystemLogs(input: LogQuery, options?: RpcOptions): UnaryCall<LogQuery, LogPage> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogQuery, LogPage>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetErrorLogs(entryvine.admin.ErrorLogQuery) returns (entryvine.admin.ErrorLogPage);
     */
    getErrorLogs(input: ErrorLogQuery, options?: RpcOptions): UnaryCall<ErrorLogQuery, ErrorLogPage> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ErrorLogQuery, ErrorLogPage>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetErrorLogStats(entryvine.common.Empty) returns (entryvine.admin.ErrorLogStats);
     */
    getErrorLogStats(input: Empty, options?: RpcOptions): UnaryCall<Empty, ErrorLogStats> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ErrorLogStats>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ResolveErrorLog(entryvine.admin.ResolveErrorLogRequest) returns (entryvine.common.AckResponse);
     */
    resolveErrorLog(input: ResolveErrorLogRequest, options?: RpcOptions): UnaryCall<ResolveErrorLogRequest, AckResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResolveErrorLogRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReportClientErrors(entryvine.admin.ClientErrorBatch) returns (entryvine.common.AckResponse);
     */
    reportClientErrors(input: ClientErrorBatch, options?: RpcOptions): UnaryCall<ClientErrorBatch, AckResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClientErrorBatch, AckResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service entryvine.admin.FeedbackService
 */
export interface IFeedbackServiceClient {
    /**
     * @generated from protobuf rpc: CreateFeedback(entryvine.admin.CreateFeedbackRequest) returns (entryvine.common.UuidValue);
     */
    createFeedback(input: CreateFeedbackRequest, options?: RpcOptions): UnaryCall<CreateFeedbackRequest, UuidValue>;
    /**
     * @generated from protobuf rpc: ListFeedback(entryvine.common.PageRequest) returns (entryvine.admin.ListFeedbackResponse);
     */
    listFeedback(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, ListFeedbackResponse>;
    /**
     * @generated from protobuf rpc: DeleteFeedback(entryvine.common.UuidValue) returns (entryvine.common.AckResponse);
     */
    deleteFeedback(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
}
/**
 * @generated from protobuf service entryvine.admin.FeedbackService
 */
export class FeedbackServiceClient implements IFeedbackServiceClient, ServiceInfo {
    typeName = FeedbackService.typeName;
    methods = FeedbackService.methods;
    options = FeedbackService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateFeedback(entryvine.admin.CreateFeedbackRequest) returns (entryvine.common.UuidValue);
     */
    createFeedback(input: CreateFeedbackRequest, options?: RpcOptions): UnaryCall<CreateFeedbackRequest, UuidValue> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateFeedbackRequest, UuidValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListFeedback(entryvine.common.PageRequest) returns (entryvine.admin.ListFeedbackResponse);
     */
    listFeedback(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, ListFeedbackResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<PageRequest, ListFeedbackResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteFeedback(entryvine.common.UuidValue) returns (entryvine.common.AckResponse);
     */
    deleteFeedback(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service entryvine.admin.PlatformLeadService
 */
export interface IPlatformLeadServiceClient {
    /**
     * @generated from protobuf rpc: CreatePlatformLead(entryvine.admin.CreatePlatformLeadRequest) returns (entryvine.common.UuidValue);
     */
    createPlatformLead(input: CreatePlatformLeadRequest, options?: RpcOptions): UnaryCall<CreatePlatformLeadRequest, UuidValue>;
    /**
     * @generated from protobuf rpc: ListPlatformLeads(entryvine.common.PageRequest) returns (entryvine.admin.ListPlatformLeadsResponse);
     */
    listPlatformLeads(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, ListPlatformLeadsResponse>;
}
/**
 * @generated from protobuf service entryvine.admin.PlatformLeadService
 */
export class PlatformLeadServiceClient implements IPlatformLeadServiceClient, ServiceInfo {
    typeName = PlatformLeadService.typeName;
    methods = PlatformLeadService.methods;
    options = PlatformLeadService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePlatformLead(entryvine.admin.CreatePlatformLeadRequest) returns (entryvine.common.UuidValue);
     */
    createPlatformLead(input: CreatePlatformLeadRequest, options?: RpcOptions): UnaryCall<CreatePlatformLeadRequest, UuidValue> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePlatformLeadRequest, UuidValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPlatformLeads(entryvine.common.PageRequest) returns (entryvine.admin.ListPlatformLeadsResponse);
     */
    listPlatformLeads(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, ListPlatformLeadsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<PageRequest, ListPlatformLeadsResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service entryvine.admin.HealthService
 */
export interface IHealthServiceClient {
    /**
     * @generated from protobuf rpc: Check(entryvine.common.Empty) returns (entryvine.admin.HealthStatus);
     */
    check(input: Empty, options?: RpcOptions): UnaryCall<Empty, HealthStatus>;
}
/**
 * @generated from protobuf service entryvine.admin.HealthService
 */
export class HealthServiceClient implements IHealthServiceClient, ServiceInfo {
    typeName = HealthService.typeName;
    methods = HealthService.methods;
    options = HealthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Check(entryvine.common.Empty) returns (entryvine.admin.HealthStatus);
     */
    check(input: Empty, options?: RpcOptions): UnaryCall<Empty, HealthStatus> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, HealthStatus>("unary", this._transport, method, opt, input);
    }
}
