/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "auth.proto" (package "entryvine.auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import type { LinkGoogleRequest } from "./auth";
import type { SetAvatarRequest } from "./auth";
import type { UpdateProfileRequest } from "./auth";
import type { UserProfile } from "./auth";
import type { Empty } from "./common";
import type { SetPasswordRequest } from "./auth";
import type { ValidateResetTokenRequest } from "./auth";
import type { PasswordResetRequest } from "./auth";
import type { MagicLinkVerifyRequest } from "./auth";
import type { MagicLinkRequest } from "./auth";
import type { AckResponse } from "./common";
import type { LogoutRequest } from "./auth";
import type { RefreshTokenRequest } from "./auth";
import type { GoogleSignInRequest } from "./auth";
import type { SignUpRequest } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AuthResponse } from "./auth";
import type { LoginRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service entryvine.auth.AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: Login(entryvine.auth.LoginRequest) returns (entryvine.auth.AuthResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: SignUp(entryvine.auth.SignUpRequest) returns (entryvine.auth.AuthResponse);
     */
    signUp(input: SignUpRequest, options?: RpcOptions): UnaryCall<SignUpRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: GoogleSignIn(entryvine.auth.GoogleSignInRequest) returns (entryvine.auth.AuthResponse);
     */
    googleSignIn(input: GoogleSignInRequest, options?: RpcOptions): UnaryCall<GoogleSignInRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: RefreshToken(entryvine.auth.RefreshTokenRequest) returns (entryvine.auth.AuthResponse);
     */
    refreshToken(input: RefreshTokenRequest, options?: RpcOptions): UnaryCall<RefreshTokenRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: Logout(entryvine.auth.LogoutRequest) returns (entryvine.common.AckResponse);
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: RequestMagicLink(entryvine.auth.MagicLinkRequest) returns (entryvine.common.AckResponse);
     */
    requestMagicLink(input: MagicLinkRequest, options?: RpcOptions): UnaryCall<MagicLinkRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: VerifyMagicLink(entryvine.auth.MagicLinkVerifyRequest) returns (entryvine.auth.AuthResponse);
     */
    verifyMagicLink(input: MagicLinkVerifyRequest, options?: RpcOptions): UnaryCall<MagicLinkVerifyRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: RequestPasswordReset(entryvine.auth.PasswordResetRequest) returns (entryvine.common.AckResponse);
     */
    requestPasswordReset(input: PasswordResetRequest, options?: RpcOptions): UnaryCall<PasswordResetRequest, AckResponse>;
    /**
     * Validate a reset token without consuming it (called when the reset page loads).
     *
     * @generated from protobuf rpc: ValidatePasswordResetToken(entryvine.auth.ValidateResetTokenRequest) returns (entryvine.common.AckResponse);
     */
    validatePasswordResetToken(input: ValidateResetTokenRequest, options?: RpcOptions): UnaryCall<ValidateResetTokenRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: SetPassword(entryvine.auth.SetPasswordRequest) returns (entryvine.common.AckResponse);
     */
    setPassword(input: SetPasswordRequest, options?: RpcOptions): UnaryCall<SetPasswordRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: Me(entryvine.common.Empty) returns (entryvine.auth.UserProfile);
     */
    me(input: Empty, options?: RpcOptions): UnaryCall<Empty, UserProfile>;
    /**
     * @generated from protobuf rpc: UpdateProfile(entryvine.auth.UpdateProfileRequest) returns (entryvine.auth.UserProfile);
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, UserProfile>;
    /**
     * @generated from protobuf rpc: SetAvatar(entryvine.auth.SetAvatarRequest) returns (entryvine.auth.UserProfile);
     */
    setAvatar(input: SetAvatarRequest, options?: RpcOptions): UnaryCall<SetAvatarRequest, UserProfile>;
    /**
     * @generated from protobuf rpc: LinkGoogle(entryvine.auth.LinkGoogleRequest) returns (entryvine.auth.UserProfile);
     */
    linkGoogle(input: LinkGoogleRequest, options?: RpcOptions): UnaryCall<LinkGoogleRequest, UserProfile>;
    /**
     * @generated from protobuf rpc: UnlinkGoogle(entryvine.common.Empty) returns (entryvine.auth.UserProfile);
     */
    unlinkGoogle(input: Empty, options?: RpcOptions): UnaryCall<Empty, UserProfile>;
}
/**
 * @generated from protobuf service entryvine.auth.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Login(entryvine.auth.LoginRequest) returns (entryvine.auth.AuthResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, AuthResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SignUp(entryvine.auth.SignUpRequest) returns (entryvine.auth.AuthResponse);
     */
    signUp(input: SignUpRequest, options?: RpcOptions): UnaryCall<SignUpRequest, AuthResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignUpRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GoogleSignIn(entryvine.auth.GoogleSignInRequest) returns (entryvine.auth.AuthResponse);
     */
    googleSignIn(input: GoogleSignInRequest, options?: RpcOptions): UnaryCall<GoogleSignInRequest, AuthResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GoogleSignInRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefreshToken(entryvine.auth.RefreshTokenRequest) returns (entryvine.auth.AuthResponse);
     */
    refreshToken(input: RefreshTokenRequest, options?: RpcOptions): UnaryCall<RefreshTokenRequest, AuthResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefreshTokenRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout(entryvine.auth.LogoutRequest) returns (entryvine.common.AckResponse);
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, AckResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RequestMagicLink(entryvine.auth.MagicLinkRequest) returns (entryvine.common.AckResponse);
     */
    requestMagicLink(input: MagicLinkRequest, options?: RpcOptions): UnaryCall<MagicLinkRequest, AckResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<MagicLinkRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: VerifyMagicLink(entryvine.auth.MagicLinkVerifyRequest) returns (entryvine.auth.AuthResponse);
     */
    verifyMagicLink(input: MagicLinkVerifyRequest, options?: RpcOptions): UnaryCall<MagicLinkVerifyRequest, AuthResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<MagicLinkVerifyRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RequestPasswordReset(entryvine.auth.PasswordResetRequest) returns (entryvine.common.AckResponse);
     */
    requestPasswordReset(input: PasswordResetRequest, options?: RpcOptions): UnaryCall<PasswordResetRequest, AckResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<PasswordResetRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Validate a reset token without consuming it (called when the reset page loads).
     *
     * @generated from protobuf rpc: ValidatePasswordResetToken(entryvine.auth.ValidateResetTokenRequest) returns (entryvine.common.AckResponse);
     */
    validatePasswordResetToken(input: ValidateResetTokenRequest, options?: RpcOptions): UnaryCall<ValidateResetTokenRequest, AckResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ValidateResetTokenRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetPassword(entryvine.auth.SetPasswordRequest) returns (entryvine.common.AckResponse);
     */
    setPassword(input: SetPasswordRequest, options?: RpcOptions): UnaryCall<SetPasswordRequest, AckResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetPasswordRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Me(entryvine.common.Empty) returns (entryvine.auth.UserProfile);
     */
    me(input: Empty, options?: RpcOptions): UnaryCall<Empty, UserProfile> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, UserProfile>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateProfile(entryvine.auth.UpdateProfileRequest) returns (entryvine.auth.UserProfile);
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, UserProfile> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateProfileRequest, UserProfile>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetAvatar(entryvine.auth.SetAvatarRequest) returns (entryvine.auth.UserProfile);
     */
    setAvatar(input: SetAvatarRequest, options?: RpcOptions): UnaryCall<SetAvatarRequest, UserProfile> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetAvatarRequest, UserProfile>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LinkGoogle(entryvine.auth.LinkGoogleRequest) returns (entryvine.auth.UserProfile);
     */
    linkGoogle(input: LinkGoogleRequest, options?: RpcOptions): UnaryCall<LinkGoogleRequest, UserProfile> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<LinkGoogleRequest, UserProfile>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnlinkGoogle(entryvine.common.Empty) returns (entryvine.auth.UserProfile);
     */
    unlinkGoogle(input: Empty, options?: RpcOptions): UnaryCall<Empty, UserProfile> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, UserProfile>("unary", this._transport, method, opt, input);
    }
}
