/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "billing.proto" (package "entryvine.billing", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DeveloperBillingService } from "./billing";
import type { VenueTaxSummaryList } from "./billing";
import type { TaxRateRow } from "./billing";
import type { TaxRateLookupRequest } from "./billing";
import type { TaxRateList } from "./billing";
import type { SetEventTaxOverrideRequest } from "./billing";
import type { TaxOverrideList } from "./billing";
import type { TenantDashboard } from "./billing";
import type { TaxRemittanceReport } from "./billing";
import type { TaxReport } from "./billing";
import type { TenantActivityList } from "./billing";
import type { TenantActivityRequest } from "./billing";
import type { RevenueReport } from "./billing";
import type { RevenueReportRequest } from "./billing";
import type { ClearEventFeeOverrideRequest } from "./billing";
import type { SetEventFeeOverrideRequest } from "./billing";
import type { FeeOverrideList } from "./billing";
import type { Empty } from "./common";
import type { CancelAddonRequest } from "./billing";
import type { ProvisionAddonRequest } from "./billing";
import type { TenantAddonList } from "./billing";
import type { CancelEventUpgradeRequest } from "./billing";
import type { EventUpgradeRequest } from "./billing";
import type { EventUpgradeList } from "./billing";
import type { CancelSubscriptionRequest } from "./billing";
import type { SubscriptionRequest } from "./billing";
import type { AckResponse } from "./common";
import type { TenantRequest } from "./billing";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { TenantBillingList } from "./billing";
import type { PageRequest } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Developer-only pricing controls: subscriptions & trials, Pay Per Event,
 * add-ons, fee overrides, and platform revenue reports. Every mutation is
 * audit-logged (who/when/from/to/why) by the service.
 *
 * @generated from protobuf service entryvine.billing.DeveloperBillingService
 */
export interface IDeveloperBillingServiceClient {
    /**
     * @generated from protobuf rpc: ListTenantBilling(entryvine.common.PageRequest) returns (entryvine.billing.TenantBillingList);
     */
    listTenantBilling(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, TenantBillingList>;
    /**
     * @generated from protobuf rpc: StartTrial(entryvine.billing.TenantRequest) returns (entryvine.common.AckResponse);
     */
    startTrial(input: TenantRequest, options?: RpcOptions): UnaryCall<TenantRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: CreateSubscription(entryvine.billing.SubscriptionRequest) returns (entryvine.common.AckResponse);
     */
    createSubscription(input: SubscriptionRequest, options?: RpcOptions): UnaryCall<SubscriptionRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ChangeSubscriptionTier(entryvine.billing.SubscriptionRequest) returns (entryvine.common.AckResponse);
     */
    changeSubscriptionTier(input: SubscriptionRequest, options?: RpcOptions): UnaryCall<SubscriptionRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: CancelSubscription(entryvine.billing.CancelSubscriptionRequest) returns (entryvine.common.AckResponse);
     */
    cancelSubscription(input: CancelSubscriptionRequest, options?: RpcOptions): UnaryCall<CancelSubscriptionRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListEventUpgrades(entryvine.common.PageRequest) returns (entryvine.billing.EventUpgradeList);
     */
    listEventUpgrades(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, EventUpgradeList>;
    /**
     * @generated from protobuf rpc: ActivateEventUpgrade(entryvine.billing.EventUpgradeRequest) returns (entryvine.common.AckResponse);
     */
    activateEventUpgrade(input: EventUpgradeRequest, options?: RpcOptions): UnaryCall<EventUpgradeRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: CancelEventUpgrade(entryvine.billing.CancelEventUpgradeRequest) returns (entryvine.common.AckResponse);
     */
    cancelEventUpgrade(input: CancelEventUpgradeRequest, options?: RpcOptions): UnaryCall<CancelEventUpgradeRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListTenantAddons(entryvine.billing.TenantRequest) returns (entryvine.billing.TenantAddonList);
     */
    listTenantAddons(input: TenantRequest, options?: RpcOptions): UnaryCall<TenantRequest, TenantAddonList>;
    /**
     * @generated from protobuf rpc: ProvisionAddon(entryvine.billing.ProvisionAddonRequest) returns (entryvine.common.AckResponse);
     */
    provisionAddon(input: ProvisionAddonRequest, options?: RpcOptions): UnaryCall<ProvisionAddonRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: CancelAddon(entryvine.billing.CancelAddonRequest) returns (entryvine.common.AckResponse);
     */
    cancelAddon(input: CancelAddonRequest, options?: RpcOptions): UnaryCall<CancelAddonRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListFeeOverrides(entryvine.common.Empty) returns (entryvine.billing.FeeOverrideList);
     */
    listFeeOverrides(input: Empty, options?: RpcOptions): UnaryCall<Empty, FeeOverrideList>;
    /**
     * @generated from protobuf rpc: SetEventFeeOverride(entryvine.billing.SetEventFeeOverrideRequest) returns (entryvine.common.AckResponse);
     */
    setEventFeeOverride(input: SetEventFeeOverrideRequest, options?: RpcOptions): UnaryCall<SetEventFeeOverrideRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ClearEventFeeOverride(entryvine.billing.ClearEventFeeOverrideRequest) returns (entryvine.common.AckResponse);
     */
    clearEventFeeOverride(input: ClearEventFeeOverrideRequest, options?: RpcOptions): UnaryCall<ClearEventFeeOverrideRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: GetRevenueReport(entryvine.billing.RevenueReportRequest) returns (entryvine.billing.RevenueReport);
     */
    getRevenueReport(input: RevenueReportRequest, options?: RpcOptions): UnaryCall<RevenueReportRequest, RevenueReport>;
    /**
     * @generated from protobuf rpc: GetTenantActivity(entryvine.billing.TenantActivityRequest) returns (entryvine.billing.TenantActivityList);
     */
    getTenantActivity(input: TenantActivityRequest, options?: RpcOptions): UnaryCall<TenantActivityRequest, TenantActivityList>;
    /**
     * @generated from protobuf rpc: GetTaxReport(entryvine.billing.RevenueReportRequest) returns (entryvine.billing.TaxReport);
     */
    getTaxReport(input: RevenueReportRequest, options?: RpcOptions): UnaryCall<RevenueReportRequest, TaxReport>;
    /**
     * Monthly remittance view split by who collected the tax: 'platform' months
     * are what EntryVine owes the tax authorities; 'self' months are informational
     * (tenants remit those themselves). Tenant breakdown inside each month.
     *
     * @generated from protobuf rpc: GetTaxRemittanceReport(entryvine.billing.RevenueReportRequest) returns (entryvine.billing.TaxRemittanceReport);
     */
    getTaxRemittanceReport(input: RevenueReportRequest, options?: RpcOptions): UnaryCall<RevenueReportRequest, TaxRemittanceReport>;
    /**
     * @generated from protobuf rpc: GetTenantDashboard(entryvine.billing.TenantRequest) returns (entryvine.billing.TenantDashboard);
     */
    getTenantDashboard(input: TenantRequest, options?: RpcOptions): UnaryCall<TenantRequest, TenantDashboard>;
    /**
     * @generated from protobuf rpc: ListTaxOverrides(entryvine.common.Empty) returns (entryvine.billing.TaxOverrideList);
     */
    listTaxOverrides(input: Empty, options?: RpcOptions): UnaryCall<Empty, TaxOverrideList>;
    /**
     * @generated from protobuf rpc: SetEventTaxOverride(entryvine.billing.SetEventTaxOverrideRequest) returns (entryvine.common.AckResponse);
     */
    setEventTaxOverride(input: SetEventTaxOverrideRequest, options?: RpcOptions): UnaryCall<SetEventTaxOverrideRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ClearEventTaxOverride(entryvine.billing.ClearEventFeeOverrideRequest) returns (entryvine.common.AckResponse);
     */
    clearEventTaxOverride(input: ClearEventFeeOverrideRequest, options?: RpcOptions): UnaryCall<ClearEventFeeOverrideRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListTaxRates(entryvine.common.Empty) returns (entryvine.billing.TaxRateList);
     */
    listTaxRates(input: Empty, options?: RpcOptions): UnaryCall<Empty, TaxRateList>;
    /**
     * @generated from protobuf rpc: LookupTaxRate(entryvine.billing.TaxRateLookupRequest) returns (entryvine.billing.TaxRateRow);
     */
    lookupTaxRate(input: TaxRateLookupRequest, options?: RpcOptions): UnaryCall<TaxRateLookupRequest, TaxRateRow>;
    /**
     * @generated from protobuf rpc: RefreshAllTaxRates(entryvine.common.Empty) returns (entryvine.common.AckResponse);
     */
    refreshAllTaxRates(input: Empty, options?: RpcOptions): UnaryCall<Empty, AckResponse>;
    /**
     * @generated from protobuf rpc: ListVenueTaxSummaries(entryvine.common.Empty) returns (entryvine.billing.VenueTaxSummaryList);
     */
    listVenueTaxSummaries(input: Empty, options?: RpcOptions): UnaryCall<Empty, VenueTaxSummaryList>;
}
/**
 * Developer-only pricing controls: subscriptions & trials, Pay Per Event,
 * add-ons, fee overrides, and platform revenue reports. Every mutation is
 * audit-logged (who/when/from/to/why) by the service.
 *
 * @generated from protobuf service entryvine.billing.DeveloperBillingService
 */
export class DeveloperBillingServiceClient implements IDeveloperBillingServiceClient, ServiceInfo {
    typeName = DeveloperBillingService.typeName;
    methods = DeveloperBillingService.methods;
    options = DeveloperBillingService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListTenantBilling(entryvine.common.PageRequest) returns (entryvine.billing.TenantBillingList);
     */
    listTenantBilling(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, TenantBillingList> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PageRequest, TenantBillingList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StartTrial(entryvine.billing.TenantRequest) returns (entryvine.common.AckResponse);
     */
    startTrial(input: TenantRequest, options?: RpcOptions): UnaryCall<TenantRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<TenantRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateSubscription(entryvine.billing.SubscriptionRequest) returns (entryvine.common.AckResponse);
     */
    createSubscription(input: SubscriptionRequest, options?: RpcOptions): UnaryCall<SubscriptionRequest, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SubscriptionRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ChangeSubscriptionTier(entryvine.billing.SubscriptionRequest) returns (entryvine.common.AckResponse);
     */
    changeSubscriptionTier(input: SubscriptionRequest, options?: RpcOptions): UnaryCall<SubscriptionRequest, AckResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SubscriptionRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelSubscription(entryvine.billing.CancelSubscriptionRequest) returns (entryvine.common.AckResponse);
     */
    cancelSubscription(input: CancelSubscriptionRequest, options?: RpcOptions): UnaryCall<CancelSubscriptionRequest, AckResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelSubscriptionRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListEventUpgrades(entryvine.common.PageRequest) returns (entryvine.billing.EventUpgradeList);
     */
    listEventUpgrades(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, EventUpgradeList> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<PageRequest, EventUpgradeList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ActivateEventUpgrade(entryvine.billing.EventUpgradeRequest) returns (entryvine.common.AckResponse);
     */
    activateEventUpgrade(input: EventUpgradeRequest, options?: RpcOptions): UnaryCall<EventUpgradeRequest, AckResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<EventUpgradeRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelEventUpgrade(entryvine.billing.CancelEventUpgradeRequest) returns (entryvine.common.AckResponse);
     */
    cancelEventUpgrade(input: CancelEventUpgradeRequest, options?: RpcOptions): UnaryCall<CancelEventUpgradeRequest, AckResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelEventUpgradeRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTenantAddons(entryvine.billing.TenantRequest) returns (entryvine.billing.TenantAddonList);
     */
    listTenantAddons(input: TenantRequest, options?: RpcOptions): UnaryCall<TenantRequest, TenantAddonList> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<TenantRequest, TenantAddonList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ProvisionAddon(entryvine.billing.ProvisionAddonRequest) returns (entryvine.common.AckResponse);
     */
    provisionAddon(input: ProvisionAddonRequest, options?: RpcOptions): UnaryCall<ProvisionAddonRequest, AckResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProvisionAddonRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelAddon(entryvine.billing.CancelAddonRequest) returns (entryvine.common.AckResponse);
     */
    cancelAddon(input: CancelAddonRequest, options?: RpcOptions): UnaryCall<CancelAddonRequest, AckResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelAddonRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListFeeOverrides(entryvine.common.Empty) returns (entryvine.billing.FeeOverrideList);
     */
    listFeeOverrides(input: Empty, options?: RpcOptions): UnaryCall<Empty, FeeOverrideList> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, FeeOverrideList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetEventFeeOverride(entryvine.billing.SetEventFeeOverrideRequest) returns (entryvine.common.AckResponse);
     */
    setEventFeeOverride(input: SetEventFeeOverrideRequest, options?: RpcOptions): UnaryCall<SetEventFeeOverrideRequest, AckResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetEventFeeOverrideRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ClearEventFeeOverride(entryvine.billing.ClearEventFeeOverrideRequest) returns (entryvine.common.AckResponse);
     */
    clearEventFeeOverride(input: ClearEventFeeOverrideRequest, options?: RpcOptions): UnaryCall<ClearEventFeeOverrideRequest, AckResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClearEventFeeOverrideRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRevenueReport(entryvine.billing.RevenueReportRequest) returns (entryvine.billing.RevenueReport);
     */
    getRevenueReport(input: RevenueReportRequest, options?: RpcOptions): UnaryCall<RevenueReportRequest, RevenueReport> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevenueReportRequest, RevenueReport>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTenantActivity(entryvine.billing.TenantActivityRequest) returns (entryvine.billing.TenantActivityList);
     */
    getTenantActivity(input: TenantActivityRequest, options?: RpcOptions): UnaryCall<TenantActivityRequest, TenantActivityList> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<TenantActivityRequest, TenantActivityList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTaxReport(entryvine.billing.RevenueReportRequest) returns (entryvine.billing.TaxReport);
     */
    getTaxReport(input: RevenueReportRequest, options?: RpcOptions): UnaryCall<RevenueReportRequest, TaxReport> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevenueReportRequest, TaxReport>("unary", this._transport, method, opt, input);
    }
    /**
     * Monthly remittance view split by who collected the tax: 'platform' months
     * are what EntryVine owes the tax authorities; 'self' months are informational
     * (tenants remit those themselves). Tenant breakdown inside each month.
     *
     * @generated from protobuf rpc: GetTaxRemittanceReport(entryvine.billing.RevenueReportRequest) returns (entryvine.billing.TaxRemittanceReport);
     */
    getTaxRemittanceReport(input: RevenueReportRequest, options?: RpcOptions): UnaryCall<RevenueReportRequest, TaxRemittanceReport> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevenueReportRequest, TaxRemittanceReport>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTenantDashboard(entryvine.billing.TenantRequest) returns (entryvine.billing.TenantDashboard);
     */
    getTenantDashboard(input: TenantRequest, options?: RpcOptions): UnaryCall<TenantRequest, TenantDashboard> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<TenantRequest, TenantDashboard>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTaxOverrides(entryvine.common.Empty) returns (entryvine.billing.TaxOverrideList);
     */
    listTaxOverrides(input: Empty, options?: RpcOptions): UnaryCall<Empty, TaxOverrideList> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, TaxOverrideList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetEventTaxOverride(entryvine.billing.SetEventTaxOverrideRequest) returns (entryvine.common.AckResponse);
     */
    setEventTaxOverride(input: SetEventTaxOverrideRequest, options?: RpcOptions): UnaryCall<SetEventTaxOverrideRequest, AckResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetEventTaxOverrideRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ClearEventTaxOverride(entryvine.billing.ClearEventFeeOverrideRequest) returns (entryvine.common.AckResponse);
     */
    clearEventTaxOverride(input: ClearEventFeeOverrideRequest, options?: RpcOptions): UnaryCall<ClearEventFeeOverrideRequest, AckResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClearEventFeeOverrideRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTaxRates(entryvine.common.Empty) returns (entryvine.billing.TaxRateList);
     */
    listTaxRates(input: Empty, options?: RpcOptions): UnaryCall<Empty, TaxRateList> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, TaxRateList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LookupTaxRate(entryvine.billing.TaxRateLookupRequest) returns (entryvine.billing.TaxRateRow);
     */
    lookupTaxRate(input: TaxRateLookupRequest, options?: RpcOptions): UnaryCall<TaxRateLookupRequest, TaxRateRow> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<TaxRateLookupRequest, TaxRateRow>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefreshAllTaxRates(entryvine.common.Empty) returns (entryvine.common.AckResponse);
     */
    refreshAllTaxRates(input: Empty, options?: RpcOptions): UnaryCall<Empty, AckResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListVenueTaxSummaries(entryvine.common.Empty) returns (entryvine.billing.VenueTaxSummaryList);
     */
    listVenueTaxSummaries(input: Empty, options?: RpcOptions): UnaryCall<Empty, VenueTaxSummaryList> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, VenueTaxSummaryList>("unary", this._transport, method, opt, input);
    }
}
