/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "bookings.proto" (package "svyne.booking", syntax proto3)
// tslint:disable
import { CheckInService } from "./bookings";
import type { CheckInStats } from "./bookings";
import type { ScanResponse } from "./bookings";
import type { ScanRequest } from "./bookings";
import { TicketService } from "./bookings";
import type { ListTicketsResponse } from "./bookings";
import type { InviteTicketRequest } from "./bookings";
import type { ClaimTicketRequest } from "./bookings";
import type { Ticket } from "./bookings";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BookingService } from "./bookings";
import type { BookingStats } from "./bookings";
import type { ListBookingsResponse } from "./bookings";
import type { ListBookingsRequest } from "./bookings";
import type { Booking } from "./bookings";
import type { AckResponse } from "./common";
import type { ConfirmBookingRequest } from "./bookings";
import type { PaymentStatusResponse } from "./bookings";
import type { PaymentIntentResponse } from "./bookings";
import type { PaymentIntentRequest } from "./bookings";
import type { CreateMultiBookingRequest } from "./bookings";
import type { ReserveOpenCapacityRequest } from "./bookings";
import type { CreateBookingResponse } from "./bookings";
import type { CreateBookingRequest } from "./bookings";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListEventTicketTypesResponse } from "./bookings";
import type { UuidValue } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service svyne.booking.BookingService
 */
export interface IBookingServiceClient {
    /**
     * @generated from protobuf rpc: ListEventTicketTypes(svyne.common.UuidValue) returns (svyne.booking.ListEventTicketTypesResponse);
     */
    listEventTicketTypes(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListEventTicketTypesResponse>;
    /**
     * @generated from protobuf rpc: CreateBooking(svyne.booking.CreateBookingRequest) returns (svyne.booking.CreateBookingResponse);
     */
    createBooking(input: CreateBookingRequest, options?: RpcOptions): UnaryCall<CreateBookingRequest, CreateBookingResponse>;
    /**
     * @generated from protobuf rpc: ReserveOpenCapacity(svyne.booking.ReserveOpenCapacityRequest) returns (svyne.booking.CreateBookingResponse);
     */
    reserveOpenCapacity(input: ReserveOpenCapacityRequest, options?: RpcOptions): UnaryCall<ReserveOpenCapacityRequest, CreateBookingResponse>;
    /**
     * Cart checkout: one booking aggregating many ticket/table lines, one payment.
     *
     * @generated from protobuf rpc: CreateMultiBooking(svyne.booking.CreateMultiBookingRequest) returns (svyne.booking.CreateBookingResponse);
     */
    createMultiBooking(input: CreateMultiBookingRequest, options?: RpcOptions): UnaryCall<CreateMultiBookingRequest, CreateBookingResponse>;
    /**
     * @generated from protobuf rpc: CreatePaymentIntent(svyne.booking.PaymentIntentRequest) returns (svyne.booking.PaymentIntentResponse);
     */
    createPaymentIntent(input: PaymentIntentRequest, options?: RpcOptions): UnaryCall<PaymentIntentRequest, PaymentIntentResponse>;
    /**
     * @generated from protobuf rpc: GetPaymentStatus(svyne.common.UuidValue) returns (svyne.booking.PaymentStatusResponse);
     */
    getPaymentStatus(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, PaymentStatusResponse>;
    /**
     * @generated from protobuf rpc: ConfirmBooking(svyne.booking.ConfirmBookingRequest) returns (svyne.common.AckResponse);
     */
    confirmBooking(input: ConfirmBookingRequest, options?: RpcOptions): UnaryCall<ConfirmBookingRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: CancelBooking(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    cancelBooking(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: RefundBooking(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    refundBooking(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: GetBooking(svyne.common.UuidValue) returns (svyne.booking.Booking);
     */
    getBooking(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Booking>;
    /**
     * @generated from protobuf rpc: ListBookings(svyne.booking.ListBookingsRequest) returns (svyne.booking.ListBookingsResponse);
     */
    listBookings(input: ListBookingsRequest, options?: RpcOptions): UnaryCall<ListBookingsRequest, ListBookingsResponse>;
    /**
     * @generated from protobuf rpc: GetBookingStats(svyne.common.UuidValue) returns (svyne.booking.BookingStats);
     */
    getBookingStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, BookingStats>;
}
/**
 * @generated from protobuf service svyne.booking.BookingService
 */
export class BookingServiceClient implements IBookingServiceClient, ServiceInfo {
    typeName = BookingService.typeName;
    methods = BookingService.methods;
    options = BookingService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListEventTicketTypes(svyne.common.UuidValue) returns (svyne.booking.ListEventTicketTypesResponse);
     */
    listEventTicketTypes(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListEventTicketTypesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, ListEventTicketTypesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateBooking(svyne.booking.CreateBookingRequest) returns (svyne.booking.CreateBookingResponse);
     */
    createBooking(input: CreateBookingRequest, options?: RpcOptions): UnaryCall<CreateBookingRequest, CreateBookingResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateBookingRequest, CreateBookingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReserveOpenCapacity(svyne.booking.ReserveOpenCapacityRequest) returns (svyne.booking.CreateBookingResponse);
     */
    reserveOpenCapacity(input: ReserveOpenCapacityRequest, options?: RpcOptions): UnaryCall<ReserveOpenCapacityRequest, CreateBookingResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReserveOpenCapacityRequest, CreateBookingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Cart checkout: one booking aggregating many ticket/table lines, one payment.
     *
     * @generated from protobuf rpc: CreateMultiBooking(svyne.booking.CreateMultiBookingRequest) returns (svyne.booking.CreateBookingResponse);
     */
    createMultiBooking(input: CreateMultiBookingRequest, options?: RpcOptions): UnaryCall<CreateMultiBookingRequest, CreateBookingResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateMultiBookingRequest, CreateBookingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreatePaymentIntent(svyne.booking.PaymentIntentRequest) returns (svyne.booking.PaymentIntentResponse);
     */
    createPaymentIntent(input: PaymentIntentRequest, options?: RpcOptions): UnaryCall<PaymentIntentRequest, PaymentIntentResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<PaymentIntentRequest, PaymentIntentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPaymentStatus(svyne.common.UuidValue) returns (svyne.booking.PaymentStatusResponse);
     */
    getPaymentStatus(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, PaymentStatusResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, PaymentStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ConfirmBooking(svyne.booking.ConfirmBookingRequest) returns (svyne.common.AckResponse);
     */
    confirmBooking(input: ConfirmBookingRequest, options?: RpcOptions): UnaryCall<ConfirmBookingRequest, AckResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConfirmBookingRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelBooking(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    cancelBooking(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefundBooking(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    refundBooking(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBooking(svyne.common.UuidValue) returns (svyne.booking.Booking);
     */
    getBooking(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Booking> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, Booking>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListBookings(svyne.booking.ListBookingsRequest) returns (svyne.booking.ListBookingsResponse);
     */
    listBookings(input: ListBookingsRequest, options?: RpcOptions): UnaryCall<ListBookingsRequest, ListBookingsResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBookingsRequest, ListBookingsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBookingStats(svyne.common.UuidValue) returns (svyne.booking.BookingStats);
     */
    getBookingStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, BookingStats> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, BookingStats>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service svyne.booking.TicketService
 */
export interface ITicketServiceClient {
    /**
     * @generated from protobuf rpc: GetTicket(svyne.common.UuidValue) returns (svyne.booking.Ticket);
     */
    getTicket(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Ticket>;
    /**
     * @generated from protobuf rpc: ClaimTicket(svyne.booking.ClaimTicketRequest) returns (svyne.common.AckResponse);
     */
    claimTicket(input: ClaimTicketRequest, options?: RpcOptions): UnaryCall<ClaimTicketRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: InviteTicket(svyne.booking.InviteTicketRequest) returns (svyne.common.AckResponse);
     */
    inviteTicket(input: InviteTicketRequest, options?: RpcOptions): UnaryCall<InviteTicketRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListTickets(svyne.common.UuidValue) returns (svyne.booking.ListTicketsResponse);
     */
    listTickets(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListTicketsResponse>;
}
/**
 * @generated from protobuf service svyne.booking.TicketService
 */
export class TicketServiceClient implements ITicketServiceClient, ServiceInfo {
    typeName = TicketService.typeName;
    methods = TicketService.methods;
    options = TicketService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetTicket(svyne.common.UuidValue) returns (svyne.booking.Ticket);
     */
    getTicket(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Ticket> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, Ticket>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ClaimTicket(svyne.booking.ClaimTicketRequest) returns (svyne.common.AckResponse);
     */
    claimTicket(input: ClaimTicketRequest, options?: RpcOptions): UnaryCall<ClaimTicketRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClaimTicketRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InviteTicket(svyne.booking.InviteTicketRequest) returns (svyne.common.AckResponse);
     */
    inviteTicket(input: InviteTicketRequest, options?: RpcOptions): UnaryCall<InviteTicketRequest, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<InviteTicketRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTickets(svyne.common.UuidValue) returns (svyne.booking.ListTicketsResponse);
     */
    listTickets(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListTicketsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, ListTicketsResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service svyne.booking.CheckInService
 */
export interface ICheckInServiceClient {
    /**
     * @generated from protobuf rpc: Scan(svyne.booking.ScanRequest) returns (svyne.booking.ScanResponse);
     */
    scan(input: ScanRequest, options?: RpcOptions): UnaryCall<ScanRequest, ScanResponse>;
    /**
     * @generated from protobuf rpc: GetCheckInStats(svyne.common.UuidValue) returns (svyne.booking.CheckInStats);
     */
    getCheckInStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, CheckInStats>;
}
/**
 * @generated from protobuf service svyne.booking.CheckInService
 */
export class CheckInServiceClient implements ICheckInServiceClient, ServiceInfo {
    typeName = CheckInService.typeName;
    methods = CheckInService.methods;
    options = CheckInService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Scan(svyne.booking.ScanRequest) returns (svyne.booking.ScanResponse);
     */
    scan(input: ScanRequest, options?: RpcOptions): UnaryCall<ScanRequest, ScanResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ScanRequest, ScanResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCheckInStats(svyne.common.UuidValue) returns (svyne.booking.CheckInStats);
     */
    getCheckInStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, CheckInStats> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, CheckInStats>("unary", this._transport, method, opt, input);
    }
}
