/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "booking.proto" (package "svyne.booking", syntax proto3)
// tslint:disable
import { Empty } from "./common";
import { AckResponse } from "./common";
import { UuidValue } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message svyne.booking.Table
 */
export interface Table {
    /**
     * @generated from protobuf field: string tables_id = 1;
     */
    tablesId: string;
    /**
     * @generated from protobuf field: string event_tables_id = 2;
     */
    eventTablesId: string;
    /**
     * @generated from protobuf field: string label = 3;
     */
    label: string;
    /**
     * @generated from protobuf field: double pos_x = 4;
     */
    posX: number;
    /**
     * @generated from protobuf field: double pos_y = 5;
     */
    posY: number;
    /**
     * @generated from protobuf field: double width = 6;
     */
    width: number;
    /**
     * @generated from protobuf field: double height = 7;
     */
    height: number;
    /**
     * @generated from protobuf field: string status = 8;
     */
    status: string;
    /**
     * @generated from protobuf field: int32 price_cents = 9;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: int32 platform_fee_cents = 10;
     */
    platformFeeCents: number;
    /**
     * @generated from protobuf field: string fee_formulas_id = 11;
     */
    feeFormulasId: string;
    /**
     * Per-individual-table overrides of the parent event_table type (empty/0 = inherit).
     *
     * @generated from protobuf field: string shape_override = 12;
     */
    shapeOverride: string;
    /**
     * @generated from protobuf field: string color_override = 13;
     */
    colorOverride: string;
    /**
     * @generated from protobuf field: int32 capacity_override = 14;
     */
    capacityOverride: number;
    /**
     * Linked Pricing Module price (authoritative). Empty = legacy cached price.
     *
     * @generated from protobuf field: string prices_id = 15;
     */
    pricesId: string;
}
/**
 * A non-table object placed on the floor-plan canvas (Entry/Exit/Stage).
 *
 * @generated from protobuf message svyne.booking.LayoutObject
 */
export interface LayoutObject {
    /**
     * @generated from protobuf field: string layout_objects_id = 1;
     */
    layoutObjectsId: string;
    /**
     * @generated from protobuf field: string object_type = 2;
     */
    objectType: string;
    /**
     * @generated from protobuf field: string label = 3;
     */
    label: string;
    /**
     * @generated from protobuf field: double pos_x = 4;
     */
    posX: number;
    /**
     * @generated from protobuf field: double pos_y = 5;
     */
    posY: number;
    /**
     * @generated from protobuf field: double width = 6;
     */
    width: number;
    /**
     * @generated from protobuf field: double height = 7;
     */
    height: number;
    /**
     * @generated from protobuf field: string color = 8;
     */
    color: string;
    /**
     * @generated from protobuf field: int32 sort_order = 9;
     */
    sortOrder: number;
}
/**
 * @generated from protobuf message svyne.booking.EventLayout
 */
export interface EventLayout {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: repeated svyne.booking.Table tables = 4;
     */
    tables: Table[];
    /**
     * @generated from protobuf field: repeated svyne.booking.LayoutObject objects = 5;
     */
    objects: LayoutObject[];
}
/**
 * @generated from protobuf message svyne.booking.SaveEventLayoutRequest
 */
export interface SaveEventLayoutRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string tables_json = 4;
     */
    tablesJson: string;
    /**
     * @generated from protobuf field: repeated string locked_ids = 5;
     */
    lockedIds: string[];
    /**
     * JSON array of layout objects (Entry/Exit/Stage) to upsert/delete.
     *
     * @generated from protobuf field: string objects_json = 6;
     */
    objectsJson: string;
}
/**
 * @generated from protobuf message svyne.booking.LockTableRequest
 */
export interface LockTableRequest {
    /**
     * @generated from protobuf field: string tables_id = 1;
     */
    tablesId: string;
}
/**
 * @generated from protobuf message svyne.booking.ListTablesResponse
 */
export interface ListTablesResponse {
    /**
     * @generated from protobuf field: repeated svyne.booking.Table tables = 1;
     */
    tables: Table[];
}
/**
 * A table TYPE (event_tables) used as a palette item in the floor-plan builder.
 *
 * @generated from protobuf message svyne.booking.EventTableType
 */
export interface EventTableType {
    /**
     * @generated from protobuf field: string event_tables_id = 1;
     */
    eventTablesId: string;
    /**
     * @generated from protobuf field: string label = 2;
     */
    label: string;
    /**
     * @generated from protobuf field: int32 capacity = 3;
     */
    capacity: number;
    /**
     * @generated from protobuf field: string shape = 4;
     */
    shape: string;
    /**
     * @generated from protobuf field: string color = 5;
     */
    color: string;
    /**
     * @generated from protobuf field: int32 price_cents = 6;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: string prices_id = 7;
     */
    pricesId: string;
    /**
     * Default pixel footprint used when placing this type on the floor plan.
     *
     * @generated from protobuf field: double default_width = 8;
     */
    defaultWidth: number;
    /**
     * @generated from protobuf field: double default_height = 9;
     */
    defaultHeight: number;
}
/**
 * @generated from protobuf message svyne.booking.ListEventTableTypesResponse
 */
export interface ListEventTableTypesResponse {
    /**
     * @generated from protobuf field: repeated svyne.booking.EventTableType table_types = 1;
     */
    tableTypes: EventTableType[];
}
/**
 * @generated from protobuf message svyne.booking.CreateEventTableRequest
 */
export interface CreateEventTableRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string label = 2;
     */
    label: string;
    /**
     * @generated from protobuf field: int32 capacity = 3;
     */
    capacity: number;
    /**
     * @generated from protobuf field: string shape = 4;
     */
    shape: string;
    /**
     * @generated from protobuf field: string color = 5;
     */
    color: string;
    /**
     * @generated from protobuf field: int32 price_cents = 6;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: string fee_formulas_id = 7;
     */
    feeFormulasId: string;
    /**
     * @generated from protobuf field: string table_templates_id = 8;
     */
    tableTemplatesId: string;
    /**
     * Table pricing mode for the linked Price. Default (is_all_inclusive=true):
     * the price_cents covers the whole table. When false, price_cents is the table
     * base and per_attendee_cents is added per reserved seat.
     *
     * @generated from protobuf field: bool is_all_inclusive = 9;
     */
    isAllInclusive: boolean;
    /**
     * @generated from protobuf field: int32 per_attendee_cents = 10;
     */
    perAttendeeCents: number;
    /**
     * Pixel footprint override (0 = inherit the catalog template default).
     *
     * @generated from protobuf field: double width = 11;
     */
    width: number;
    /**
     * @generated from protobuf field: double height = 12;
     */
    height: number;
}
/**
 * @generated from protobuf message svyne.booking.CreateEventTicketTypeRequest
 */
export interface CreateEventTicketTypeRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string label = 2;
     */
    label: string;
    /**
     * @generated from protobuf field: int32 price_cents = 3;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: string fee_formulas_id = 4;
     */
    feeFormulasId: string;
    /**
     * @generated from protobuf field: int32 max_quantity = 5;
     */
    maxQuantity: number;
    /**
     * @generated from protobuf field: int32 sort_order = 6;
     */
    sortOrder: number;
    /**
     * @generated from protobuf field: string description = 7;
     */
    description: string;
    /**
     * @generated from protobuf field: int32 capacity = 8;
     */
    capacity: number; // seats this tier contributes to event capacity (0 = uncapped)
}
/**
 * @generated from protobuf message svyne.booking.UpdateEventTicketTypeRequest
 */
export interface UpdateEventTicketTypeRequest {
    /**
     * @generated from protobuf field: string event_ticket_types_id = 1;
     */
    eventTicketTypesId: string;
    /**
     * @generated from protobuf field: string label = 2;
     */
    label: string;
    /**
     * @generated from protobuf field: int32 price_cents = 3;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: string fee_formulas_id = 4;
     */
    feeFormulasId: string;
    /**
     * @generated from protobuf field: int32 max_quantity = 5;
     */
    maxQuantity: number;
    /**
     * @generated from protobuf field: int32 sort_order = 6;
     */
    sortOrder: number;
    /**
     * @generated from protobuf field: string description = 7;
     */
    description: string;
    /**
     * @generated from protobuf field: bool is_active = 8;
     */
    isActive: boolean;
    /**
     * @generated from protobuf field: int32 capacity = 9;
     */
    capacity: number; // seats this tier contributes to event capacity (0 = uncapped)
}
/**
 * A catalog price rule on a table template (mirrors pricing.PriceRule, keyed by
 * table_templates_id instead of prices_id).
 *
 * @generated from protobuf message svyne.booking.TableTemplatePriceRule
 */
export interface TableTemplatePriceRule {
    /**
     * @generated from protobuf field: string table_template_price_rules_id = 1;
     */
    tableTemplatePriceRulesId: string;
    /**
     * @generated from protobuf field: string table_templates_id = 2;
     */
    tableTemplatesId: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: string rule_type = 4;
     */
    ruleType: string; // Presale | LastMinute | TimeWindow | Dynamic
    /**
     * @generated from protobuf field: int32 priority = 5;
     */
    priority: number; // higher wins
    /**
     * @generated from protobuf field: int32 price_cents = 6;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: int64 active_from = 7;
     */
    activeFrom: string; // unix seconds; 0 = unset
    /**
     * @generated from protobuf field: int64 active_until = 8;
     */
    activeUntil: string; // unix seconds; 0 = unset
    /**
     * @generated from protobuf field: int32 min_remaining = 9;
     */
    minRemaining: number; // -1 = unset
    /**
     * @generated from protobuf field: int32 max_remaining = 10;
     */
    maxRemaining: number; // -1 = unset
    /**
     * @generated from protobuf field: bool is_active = 11;
     */
    isActive: boolean;
}
/**
 * @generated from protobuf message svyne.booking.CreateTableTemplatePriceRuleRequest
 */
export interface CreateTableTemplatePriceRuleRequest {
    /**
     * @generated from protobuf field: string table_templates_id = 1;
     */
    tableTemplatesId: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string rule_type = 3;
     */
    ruleType: string;
    /**
     * @generated from protobuf field: int32 priority = 4;
     */
    priority: number;
    /**
     * @generated from protobuf field: int32 price_cents = 5;
     */
    priceCents: number;
    /**
     * @generated from protobuf field: int64 active_from = 6;
     */
    activeFrom: string;
    /**
     * @generated from protobuf field: int64 active_until = 7;
     */
    activeUntil: string;
    /**
     * @generated from protobuf field: int32 min_remaining = 8;
     */
    minRemaining: number;
    /**
     * @generated from protobuf field: int32 max_remaining = 9;
     */
    maxRemaining: number;
}
/**
 * @generated from protobuf message svyne.booking.ListTableTemplatePriceRulesResponse
 */
export interface ListTableTemplatePriceRulesResponse {
    /**
     * @generated from protobuf field: repeated svyne.booking.TableTemplatePriceRule rules = 1;
     */
    rules: TableTemplatePriceRule[];
}
/**
 * @generated from protobuf message svyne.booking.TableTemplate
 */
export interface TableTemplate {
    /**
     * @generated from protobuf field: string table_templates_id = 1;
     */
    tableTemplatesId: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: int32 default_capacity = 3;
     */
    defaultCapacity: number;
    /**
     * @generated from protobuf field: string default_shape = 4;
     */
    defaultShape: string;
    /**
     * @generated from protobuf field: string default_color = 5;
     */
    defaultColor: string;
    /**
     * @generated from protobuf field: int32 default_price_cents = 6;
     */
    defaultPriceCents: number;
    /**
     * @generated from protobuf field: bool is_active = 7;
     */
    isActive: boolean;
    /**
     * @generated from protobuf field: double default_width = 8;
     */
    defaultWidth: number;
    /**
     * @generated from protobuf field: double default_height = 9;
     */
    defaultHeight: number;
}
/**
 * @generated from protobuf message svyne.booking.CreateTableTemplateRequest
 */
export interface CreateTableTemplateRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: int32 default_capacity = 2;
     */
    defaultCapacity: number;
    /**
     * @generated from protobuf field: string default_shape = 3;
     */
    defaultShape: string;
    /**
     * @generated from protobuf field: string default_color = 4;
     */
    defaultColor: string;
    /**
     * @generated from protobuf field: int32 default_price_cents = 5;
     */
    defaultPriceCents: number;
    /**
     * @generated from protobuf field: double default_width = 6;
     */
    defaultWidth: number;
    /**
     * @generated from protobuf field: double default_height = 7;
     */
    defaultHeight: number;
}
/**
 * @generated from protobuf message svyne.booking.ListTableTemplatesResponse
 */
export interface ListTableTemplatesResponse {
    /**
     * @generated from protobuf field: repeated svyne.booking.TableTemplate templates = 1;
     */
    templates: TableTemplate[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Table$Type extends MessageType<Table> {
    constructor() {
        super("svyne.booking.Table", [
            { no: 1, name: "tables_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "event_tables_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "pos_x", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "pos_y", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "width", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "height", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "platform_fee_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "fee_formulas_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "shape_override", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "color_override", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "capacity_override", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 15, name: "prices_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Table>): Table {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tablesId = "";
        message.eventTablesId = "";
        message.label = "";
        message.posX = 0;
        message.posY = 0;
        message.width = 0;
        message.height = 0;
        message.status = "";
        message.priceCents = 0;
        message.platformFeeCents = 0;
        message.feeFormulasId = "";
        message.shapeOverride = "";
        message.colorOverride = "";
        message.capacityOverride = 0;
        message.pricesId = "";
        if (value !== undefined)
            reflectionMergePartial<Table>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Table): Table {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tables_id */ 1:
                    message.tablesId = reader.string();
                    break;
                case /* string event_tables_id */ 2:
                    message.eventTablesId = reader.string();
                    break;
                case /* string label */ 3:
                    message.label = reader.string();
                    break;
                case /* double pos_x */ 4:
                    message.posX = reader.double();
                    break;
                case /* double pos_y */ 5:
                    message.posY = reader.double();
                    break;
                case /* double width */ 6:
                    message.width = reader.double();
                    break;
                case /* double height */ 7:
                    message.height = reader.double();
                    break;
                case /* string status */ 8:
                    message.status = reader.string();
                    break;
                case /* int32 price_cents */ 9:
                    message.priceCents = reader.int32();
                    break;
                case /* int32 platform_fee_cents */ 10:
                    message.platformFeeCents = reader.int32();
                    break;
                case /* string fee_formulas_id */ 11:
                    message.feeFormulasId = reader.string();
                    break;
                case /* string shape_override */ 12:
                    message.shapeOverride = reader.string();
                    break;
                case /* string color_override */ 13:
                    message.colorOverride = reader.string();
                    break;
                case /* int32 capacity_override */ 14:
                    message.capacityOverride = reader.int32();
                    break;
                case /* string prices_id */ 15:
                    message.pricesId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Table, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tables_id = 1; */
        if (message.tablesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tablesId);
        /* string event_tables_id = 2; */
        if (message.eventTablesId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventTablesId);
        /* string label = 3; */
        if (message.label !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.label);
        /* double pos_x = 4; */
        if (message.posX !== 0)
            writer.tag(4, WireType.Bit64).double(message.posX);
        /* double pos_y = 5; */
        if (message.posY !== 0)
            writer.tag(5, WireType.Bit64).double(message.posY);
        /* double width = 6; */
        if (message.width !== 0)
            writer.tag(6, WireType.Bit64).double(message.width);
        /* double height = 7; */
        if (message.height !== 0)
            writer.tag(7, WireType.Bit64).double(message.height);
        /* string status = 8; */
        if (message.status !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.status);
        /* int32 price_cents = 9; */
        if (message.priceCents !== 0)
            writer.tag(9, WireType.Varint).int32(message.priceCents);
        /* int32 platform_fee_cents = 10; */
        if (message.platformFeeCents !== 0)
            writer.tag(10, WireType.Varint).int32(message.platformFeeCents);
        /* string fee_formulas_id = 11; */
        if (message.feeFormulasId !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.feeFormulasId);
        /* string shape_override = 12; */
        if (message.shapeOverride !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.shapeOverride);
        /* string color_override = 13; */
        if (message.colorOverride !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.colorOverride);
        /* int32 capacity_override = 14; */
        if (message.capacityOverride !== 0)
            writer.tag(14, WireType.Varint).int32(message.capacityOverride);
        /* string prices_id = 15; */
        if (message.pricesId !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.pricesId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.Table
 */
export const Table = new Table$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LayoutObject$Type extends MessageType<LayoutObject> {
    constructor() {
        super("svyne.booking.LayoutObject", [
            { no: 1, name: "layout_objects_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "object_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "pos_x", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "pos_y", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "width", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "height", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "sort_order", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<LayoutObject>): LayoutObject {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.layoutObjectsId = "";
        message.objectType = "";
        message.label = "";
        message.posX = 0;
        message.posY = 0;
        message.width = 0;
        message.height = 0;
        message.color = "";
        message.sortOrder = 0;
        if (value !== undefined)
            reflectionMergePartial<LayoutObject>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LayoutObject): LayoutObject {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string layout_objects_id */ 1:
                    message.layoutObjectsId = reader.string();
                    break;
                case /* string object_type */ 2:
                    message.objectType = reader.string();
                    break;
                case /* string label */ 3:
                    message.label = reader.string();
                    break;
                case /* double pos_x */ 4:
                    message.posX = reader.double();
                    break;
                case /* double pos_y */ 5:
                    message.posY = reader.double();
                    break;
                case /* double width */ 6:
                    message.width = reader.double();
                    break;
                case /* double height */ 7:
                    message.height = reader.double();
                    break;
                case /* string color */ 8:
                    message.color = reader.string();
                    break;
                case /* int32 sort_order */ 9:
                    message.sortOrder = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LayoutObject, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string layout_objects_id = 1; */
        if (message.layoutObjectsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.layoutObjectsId);
        /* string object_type = 2; */
        if (message.objectType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.objectType);
        /* string label = 3; */
        if (message.label !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.label);
        /* double pos_x = 4; */
        if (message.posX !== 0)
            writer.tag(4, WireType.Bit64).double(message.posX);
        /* double pos_y = 5; */
        if (message.posY !== 0)
            writer.tag(5, WireType.Bit64).double(message.posY);
        /* double width = 6; */
        if (message.width !== 0)
            writer.tag(6, WireType.Bit64).double(message.width);
        /* double height = 7; */
        if (message.height !== 0)
            writer.tag(7, WireType.Bit64).double(message.height);
        /* string color = 8; */
        if (message.color !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.color);
        /* int32 sort_order = 9; */
        if (message.sortOrder !== 0)
            writer.tag(9, WireType.Varint).int32(message.sortOrder);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.LayoutObject
 */
export const LayoutObject = new LayoutObject$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventLayout$Type extends MessageType<EventLayout> {
    constructor() {
        super("svyne.booking.EventLayout", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "tables", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Table },
            { no: 5, name: "objects", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LayoutObject }
        ]);
    }
    create(value?: PartialMessage<EventLayout>): EventLayout {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.tables = [];
        message.objects = [];
        if (value !== undefined)
            reflectionMergePartial<EventLayout>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventLayout): EventLayout {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* repeated svyne.booking.Table tables */ 4:
                    message.tables.push(Table.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated svyne.booking.LayoutObject objects */ 5:
                    message.objects.push(LayoutObject.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventLayout, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* repeated svyne.booking.Table tables = 4; */
        for (let i = 0; i < message.tables.length; i++)
            Table.internalBinaryWrite(message.tables[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated svyne.booking.LayoutObject objects = 5; */
        for (let i = 0; i < message.objects.length; i++)
            LayoutObject.internalBinaryWrite(message.objects[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.EventLayout
 */
export const EventLayout = new EventLayout$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SaveEventLayoutRequest$Type extends MessageType<SaveEventLayoutRequest> {
    constructor() {
        super("svyne.booking.SaveEventLayoutRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "tables_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "locked_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "objects_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SaveEventLayoutRequest>): SaveEventLayoutRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.tablesJson = "";
        message.lockedIds = [];
        message.objectsJson = "";
        if (value !== undefined)
            reflectionMergePartial<SaveEventLayoutRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SaveEventLayoutRequest): SaveEventLayoutRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string tables_json */ 4:
                    message.tablesJson = reader.string();
                    break;
                case /* repeated string locked_ids */ 5:
                    message.lockedIds.push(reader.string());
                    break;
                case /* string objects_json */ 6:
                    message.objectsJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SaveEventLayoutRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string tables_json = 4; */
        if (message.tablesJson !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.tablesJson);
        /* repeated string locked_ids = 5; */
        for (let i = 0; i < message.lockedIds.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.lockedIds[i]);
        /* string objects_json = 6; */
        if (message.objectsJson !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.objectsJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.SaveEventLayoutRequest
 */
export const SaveEventLayoutRequest = new SaveEventLayoutRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LockTableRequest$Type extends MessageType<LockTableRequest> {
    constructor() {
        super("svyne.booking.LockTableRequest", [
            { no: 1, name: "tables_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LockTableRequest>): LockTableRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tablesId = "";
        if (value !== undefined)
            reflectionMergePartial<LockTableRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LockTableRequest): LockTableRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tables_id */ 1:
                    message.tablesId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LockTableRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tables_id = 1; */
        if (message.tablesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tablesId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.LockTableRequest
 */
export const LockTableRequest = new LockTableRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListTablesResponse$Type extends MessageType<ListTablesResponse> {
    constructor() {
        super("svyne.booking.ListTablesResponse", [
            { no: 1, name: "tables", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Table }
        ]);
    }
    create(value?: PartialMessage<ListTablesResponse>): ListTablesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tables = [];
        if (value !== undefined)
            reflectionMergePartial<ListTablesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListTablesResponse): ListTablesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.booking.Table tables */ 1:
                    message.tables.push(Table.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListTablesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.booking.Table tables = 1; */
        for (let i = 0; i < message.tables.length; i++)
            Table.internalBinaryWrite(message.tables[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.ListTablesResponse
 */
export const ListTablesResponse = new ListTablesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventTableType$Type extends MessageType<EventTableType> {
    constructor() {
        super("svyne.booking.EventTableType", [
            { no: 1, name: "event_tables_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "shape", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "prices_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "default_width", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "default_height", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<EventTableType>): EventTableType {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventTablesId = "";
        message.label = "";
        message.capacity = 0;
        message.shape = "";
        message.color = "";
        message.priceCents = 0;
        message.pricesId = "";
        message.defaultWidth = 0;
        message.defaultHeight = 0;
        if (value !== undefined)
            reflectionMergePartial<EventTableType>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventTableType): EventTableType {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_tables_id */ 1:
                    message.eventTablesId = reader.string();
                    break;
                case /* string label */ 2:
                    message.label = reader.string();
                    break;
                case /* int32 capacity */ 3:
                    message.capacity = reader.int32();
                    break;
                case /* string shape */ 4:
                    message.shape = reader.string();
                    break;
                case /* string color */ 5:
                    message.color = reader.string();
                    break;
                case /* int32 price_cents */ 6:
                    message.priceCents = reader.int32();
                    break;
                case /* string prices_id */ 7:
                    message.pricesId = reader.string();
                    break;
                case /* double default_width */ 8:
                    message.defaultWidth = reader.double();
                    break;
                case /* double default_height */ 9:
                    message.defaultHeight = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventTableType, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_tables_id = 1; */
        if (message.eventTablesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventTablesId);
        /* string label = 2; */
        if (message.label !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.label);
        /* int32 capacity = 3; */
        if (message.capacity !== 0)
            writer.tag(3, WireType.Varint).int32(message.capacity);
        /* string shape = 4; */
        if (message.shape !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.shape);
        /* string color = 5; */
        if (message.color !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.color);
        /* int32 price_cents = 6; */
        if (message.priceCents !== 0)
            writer.tag(6, WireType.Varint).int32(message.priceCents);
        /* string prices_id = 7; */
        if (message.pricesId !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.pricesId);
        /* double default_width = 8; */
        if (message.defaultWidth !== 0)
            writer.tag(8, WireType.Bit64).double(message.defaultWidth);
        /* double default_height = 9; */
        if (message.defaultHeight !== 0)
            writer.tag(9, WireType.Bit64).double(message.defaultHeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.EventTableType
 */
export const EventTableType = new EventTableType$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventTableTypesResponse$Type extends MessageType<ListEventTableTypesResponse> {
    constructor() {
        super("svyne.booking.ListEventTableTypesResponse", [
            { no: 1, name: "table_types", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventTableType }
        ]);
    }
    create(value?: PartialMessage<ListEventTableTypesResponse>): ListEventTableTypesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tableTypes = [];
        if (value !== undefined)
            reflectionMergePartial<ListEventTableTypesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventTableTypesResponse): ListEventTableTypesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.booking.EventTableType table_types */ 1:
                    message.tableTypes.push(EventTableType.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventTableTypesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.booking.EventTableType table_types = 1; */
        for (let i = 0; i < message.tableTypes.length; i++)
            EventTableType.internalBinaryWrite(message.tableTypes[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.ListEventTableTypesResponse
 */
export const ListEventTableTypesResponse = new ListEventTableTypesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateEventTableRequest$Type extends MessageType<CreateEventTableRequest> {
    constructor() {
        super("svyne.booking.CreateEventTableRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "shape", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "fee_formulas_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "table_templates_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "is_all_inclusive", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "per_attendee_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "width", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 12, name: "height", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<CreateEventTableRequest>): CreateEventTableRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.label = "";
        message.capacity = 0;
        message.shape = "";
        message.color = "";
        message.priceCents = 0;
        message.feeFormulasId = "";
        message.tableTemplatesId = "";
        message.isAllInclusive = false;
        message.perAttendeeCents = 0;
        message.width = 0;
        message.height = 0;
        if (value !== undefined)
            reflectionMergePartial<CreateEventTableRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateEventTableRequest): CreateEventTableRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string label */ 2:
                    message.label = reader.string();
                    break;
                case /* int32 capacity */ 3:
                    message.capacity = reader.int32();
                    break;
                case /* string shape */ 4:
                    message.shape = reader.string();
                    break;
                case /* string color */ 5:
                    message.color = reader.string();
                    break;
                case /* int32 price_cents */ 6:
                    message.priceCents = reader.int32();
                    break;
                case /* string fee_formulas_id */ 7:
                    message.feeFormulasId = reader.string();
                    break;
                case /* string table_templates_id */ 8:
                    message.tableTemplatesId = reader.string();
                    break;
                case /* bool is_all_inclusive */ 9:
                    message.isAllInclusive = reader.bool();
                    break;
                case /* int32 per_attendee_cents */ 10:
                    message.perAttendeeCents = reader.int32();
                    break;
                case /* double width */ 11:
                    message.width = reader.double();
                    break;
                case /* double height */ 12:
                    message.height = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateEventTableRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string label = 2; */
        if (message.label !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.label);
        /* int32 capacity = 3; */
        if (message.capacity !== 0)
            writer.tag(3, WireType.Varint).int32(message.capacity);
        /* string shape = 4; */
        if (message.shape !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.shape);
        /* string color = 5; */
        if (message.color !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.color);
        /* int32 price_cents = 6; */
        if (message.priceCents !== 0)
            writer.tag(6, WireType.Varint).int32(message.priceCents);
        /* string fee_formulas_id = 7; */
        if (message.feeFormulasId !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.feeFormulasId);
        /* string table_templates_id = 8; */
        if (message.tableTemplatesId !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.tableTemplatesId);
        /* bool is_all_inclusive = 9; */
        if (message.isAllInclusive !== false)
            writer.tag(9, WireType.Varint).bool(message.isAllInclusive);
        /* int32 per_attendee_cents = 10; */
        if (message.perAttendeeCents !== 0)
            writer.tag(10, WireType.Varint).int32(message.perAttendeeCents);
        /* double width = 11; */
        if (message.width !== 0)
            writer.tag(11, WireType.Bit64).double(message.width);
        /* double height = 12; */
        if (message.height !== 0)
            writer.tag(12, WireType.Bit64).double(message.height);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.CreateEventTableRequest
 */
export const CreateEventTableRequest = new CreateEventTableRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateEventTicketTypeRequest$Type extends MessageType<CreateEventTicketTypeRequest> {
    constructor() {
        super("svyne.booking.CreateEventTicketTypeRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "fee_formulas_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "max_quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "sort_order", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CreateEventTicketTypeRequest>): CreateEventTicketTypeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.label = "";
        message.priceCents = 0;
        message.feeFormulasId = "";
        message.maxQuantity = 0;
        message.sortOrder = 0;
        message.description = "";
        message.capacity = 0;
        if (value !== undefined)
            reflectionMergePartial<CreateEventTicketTypeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateEventTicketTypeRequest): CreateEventTicketTypeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string label */ 2:
                    message.label = reader.string();
                    break;
                case /* int32 price_cents */ 3:
                    message.priceCents = reader.int32();
                    break;
                case /* string fee_formulas_id */ 4:
                    message.feeFormulasId = reader.string();
                    break;
                case /* int32 max_quantity */ 5:
                    message.maxQuantity = reader.int32();
                    break;
                case /* int32 sort_order */ 6:
                    message.sortOrder = reader.int32();
                    break;
                case /* string description */ 7:
                    message.description = reader.string();
                    break;
                case /* int32 capacity */ 8:
                    message.capacity = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateEventTicketTypeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string label = 2; */
        if (message.label !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.label);
        /* int32 price_cents = 3; */
        if (message.priceCents !== 0)
            writer.tag(3, WireType.Varint).int32(message.priceCents);
        /* string fee_formulas_id = 4; */
        if (message.feeFormulasId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.feeFormulasId);
        /* int32 max_quantity = 5; */
        if (message.maxQuantity !== 0)
            writer.tag(5, WireType.Varint).int32(message.maxQuantity);
        /* int32 sort_order = 6; */
        if (message.sortOrder !== 0)
            writer.tag(6, WireType.Varint).int32(message.sortOrder);
        /* string description = 7; */
        if (message.description !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.description);
        /* int32 capacity = 8; */
        if (message.capacity !== 0)
            writer.tag(8, WireType.Varint).int32(message.capacity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.CreateEventTicketTypeRequest
 */
export const CreateEventTicketTypeRequest = new CreateEventTicketTypeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateEventTicketTypeRequest$Type extends MessageType<UpdateEventTicketTypeRequest> {
    constructor() {
        super("svyne.booking.UpdateEventTicketTypeRequest", [
            { no: 1, name: "event_ticket_types_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "fee_formulas_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "max_quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "sort_order", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "is_active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateEventTicketTypeRequest>): UpdateEventTicketTypeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventTicketTypesId = "";
        message.label = "";
        message.priceCents = 0;
        message.feeFormulasId = "";
        message.maxQuantity = 0;
        message.sortOrder = 0;
        message.description = "";
        message.isActive = false;
        message.capacity = 0;
        if (value !== undefined)
            reflectionMergePartial<UpdateEventTicketTypeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateEventTicketTypeRequest): UpdateEventTicketTypeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_ticket_types_id */ 1:
                    message.eventTicketTypesId = reader.string();
                    break;
                case /* string label */ 2:
                    message.label = reader.string();
                    break;
                case /* int32 price_cents */ 3:
                    message.priceCents = reader.int32();
                    break;
                case /* string fee_formulas_id */ 4:
                    message.feeFormulasId = reader.string();
                    break;
                case /* int32 max_quantity */ 5:
                    message.maxQuantity = reader.int32();
                    break;
                case /* int32 sort_order */ 6:
                    message.sortOrder = reader.int32();
                    break;
                case /* string description */ 7:
                    message.description = reader.string();
                    break;
                case /* bool is_active */ 8:
                    message.isActive = reader.bool();
                    break;
                case /* int32 capacity */ 9:
                    message.capacity = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateEventTicketTypeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_ticket_types_id = 1; */
        if (message.eventTicketTypesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventTicketTypesId);
        /* string label = 2; */
        if (message.label !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.label);
        /* int32 price_cents = 3; */
        if (message.priceCents !== 0)
            writer.tag(3, WireType.Varint).int32(message.priceCents);
        /* string fee_formulas_id = 4; */
        if (message.feeFormulasId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.feeFormulasId);
        /* int32 max_quantity = 5; */
        if (message.maxQuantity !== 0)
            writer.tag(5, WireType.Varint).int32(message.maxQuantity);
        /* int32 sort_order = 6; */
        if (message.sortOrder !== 0)
            writer.tag(6, WireType.Varint).int32(message.sortOrder);
        /* string description = 7; */
        if (message.description !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.description);
        /* bool is_active = 8; */
        if (message.isActive !== false)
            writer.tag(8, WireType.Varint).bool(message.isActive);
        /* int32 capacity = 9; */
        if (message.capacity !== 0)
            writer.tag(9, WireType.Varint).int32(message.capacity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.UpdateEventTicketTypeRequest
 */
export const UpdateEventTicketTypeRequest = new UpdateEventTicketTypeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TableTemplatePriceRule$Type extends MessageType<TableTemplatePriceRule> {
    constructor() {
        super("svyne.booking.TableTemplatePriceRule", [
            { no: 1, name: "table_template_price_rules_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "table_templates_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "rule_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "priority", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "active_from", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "active_until", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "min_remaining", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "max_remaining", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "is_active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TableTemplatePriceRule>): TableTemplatePriceRule {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tableTemplatePriceRulesId = "";
        message.tableTemplatesId = "";
        message.name = "";
        message.ruleType = "";
        message.priority = 0;
        message.priceCents = 0;
        message.activeFrom = "0";
        message.activeUntil = "0";
        message.minRemaining = 0;
        message.maxRemaining = 0;
        message.isActive = false;
        if (value !== undefined)
            reflectionMergePartial<TableTemplatePriceRule>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TableTemplatePriceRule): TableTemplatePriceRule {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string table_template_price_rules_id */ 1:
                    message.tableTemplatePriceRulesId = reader.string();
                    break;
                case /* string table_templates_id */ 2:
                    message.tableTemplatesId = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string rule_type */ 4:
                    message.ruleType = reader.string();
                    break;
                case /* int32 priority */ 5:
                    message.priority = reader.int32();
                    break;
                case /* int32 price_cents */ 6:
                    message.priceCents = reader.int32();
                    break;
                case /* int64 active_from */ 7:
                    message.activeFrom = reader.int64().toString();
                    break;
                case /* int64 active_until */ 8:
                    message.activeUntil = reader.int64().toString();
                    break;
                case /* int32 min_remaining */ 9:
                    message.minRemaining = reader.int32();
                    break;
                case /* int32 max_remaining */ 10:
                    message.maxRemaining = reader.int32();
                    break;
                case /* bool is_active */ 11:
                    message.isActive = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TableTemplatePriceRule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string table_template_price_rules_id = 1; */
        if (message.tableTemplatePriceRulesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tableTemplatePriceRulesId);
        /* string table_templates_id = 2; */
        if (message.tableTemplatesId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tableTemplatesId);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string rule_type = 4; */
        if (message.ruleType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.ruleType);
        /* int32 priority = 5; */
        if (message.priority !== 0)
            writer.tag(5, WireType.Varint).int32(message.priority);
        /* int32 price_cents = 6; */
        if (message.priceCents !== 0)
            writer.tag(6, WireType.Varint).int32(message.priceCents);
        /* int64 active_from = 7; */
        if (message.activeFrom !== "0")
            writer.tag(7, WireType.Varint).int64(message.activeFrom);
        /* int64 active_until = 8; */
        if (message.activeUntil !== "0")
            writer.tag(8, WireType.Varint).int64(message.activeUntil);
        /* int32 min_remaining = 9; */
        if (message.minRemaining !== 0)
            writer.tag(9, WireType.Varint).int32(message.minRemaining);
        /* int32 max_remaining = 10; */
        if (message.maxRemaining !== 0)
            writer.tag(10, WireType.Varint).int32(message.maxRemaining);
        /* bool is_active = 11; */
        if (message.isActive !== false)
            writer.tag(11, WireType.Varint).bool(message.isActive);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.TableTemplatePriceRule
 */
export const TableTemplatePriceRule = new TableTemplatePriceRule$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTableTemplatePriceRuleRequest$Type extends MessageType<CreateTableTemplatePriceRuleRequest> {
    constructor() {
        super("svyne.booking.CreateTableTemplatePriceRuleRequest", [
            { no: 1, name: "table_templates_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "rule_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "priority", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "active_from", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 7, name: "active_until", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "min_remaining", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "max_remaining", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CreateTableTemplatePriceRuleRequest>): CreateTableTemplatePriceRuleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tableTemplatesId = "";
        message.name = "";
        message.ruleType = "";
        message.priority = 0;
        message.priceCents = 0;
        message.activeFrom = "0";
        message.activeUntil = "0";
        message.minRemaining = 0;
        message.maxRemaining = 0;
        if (value !== undefined)
            reflectionMergePartial<CreateTableTemplatePriceRuleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTableTemplatePriceRuleRequest): CreateTableTemplatePriceRuleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string table_templates_id */ 1:
                    message.tableTemplatesId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string rule_type */ 3:
                    message.ruleType = reader.string();
                    break;
                case /* int32 priority */ 4:
                    message.priority = reader.int32();
                    break;
                case /* int32 price_cents */ 5:
                    message.priceCents = reader.int32();
                    break;
                case /* int64 active_from */ 6:
                    message.activeFrom = reader.int64().toString();
                    break;
                case /* int64 active_until */ 7:
                    message.activeUntil = reader.int64().toString();
                    break;
                case /* int32 min_remaining */ 8:
                    message.minRemaining = reader.int32();
                    break;
                case /* int32 max_remaining */ 9:
                    message.maxRemaining = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTableTemplatePriceRuleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string table_templates_id = 1; */
        if (message.tableTemplatesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tableTemplatesId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string rule_type = 3; */
        if (message.ruleType !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.ruleType);
        /* int32 priority = 4; */
        if (message.priority !== 0)
            writer.tag(4, WireType.Varint).int32(message.priority);
        /* int32 price_cents = 5; */
        if (message.priceCents !== 0)
            writer.tag(5, WireType.Varint).int32(message.priceCents);
        /* int64 active_from = 6; */
        if (message.activeFrom !== "0")
            writer.tag(6, WireType.Varint).int64(message.activeFrom);
        /* int64 active_until = 7; */
        if (message.activeUntil !== "0")
            writer.tag(7, WireType.Varint).int64(message.activeUntil);
        /* int32 min_remaining = 8; */
        if (message.minRemaining !== 0)
            writer.tag(8, WireType.Varint).int32(message.minRemaining);
        /* int32 max_remaining = 9; */
        if (message.maxRemaining !== 0)
            writer.tag(9, WireType.Varint).int32(message.maxRemaining);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.CreateTableTemplatePriceRuleRequest
 */
export const CreateTableTemplatePriceRuleRequest = new CreateTableTemplatePriceRuleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListTableTemplatePriceRulesResponse$Type extends MessageType<ListTableTemplatePriceRulesResponse> {
    constructor() {
        super("svyne.booking.ListTableTemplatePriceRulesResponse", [
            { no: 1, name: "rules", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TableTemplatePriceRule }
        ]);
    }
    create(value?: PartialMessage<ListTableTemplatePriceRulesResponse>): ListTableTemplatePriceRulesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rules = [];
        if (value !== undefined)
            reflectionMergePartial<ListTableTemplatePriceRulesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListTableTemplatePriceRulesResponse): ListTableTemplatePriceRulesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.booking.TableTemplatePriceRule rules */ 1:
                    message.rules.push(TableTemplatePriceRule.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListTableTemplatePriceRulesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.booking.TableTemplatePriceRule rules = 1; */
        for (let i = 0; i < message.rules.length; i++)
            TableTemplatePriceRule.internalBinaryWrite(message.rules[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.ListTableTemplatePriceRulesResponse
 */
export const ListTableTemplatePriceRulesResponse = new ListTableTemplatePriceRulesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TableTemplate$Type extends MessageType<TableTemplate> {
    constructor() {
        super("svyne.booking.TableTemplate", [
            { no: 1, name: "table_templates_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "default_capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "default_shape", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "default_color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "default_price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "is_active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "default_width", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "default_height", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<TableTemplate>): TableTemplate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tableTemplatesId = "";
        message.name = "";
        message.defaultCapacity = 0;
        message.defaultShape = "";
        message.defaultColor = "";
        message.defaultPriceCents = 0;
        message.isActive = false;
        message.defaultWidth = 0;
        message.defaultHeight = 0;
        if (value !== undefined)
            reflectionMergePartial<TableTemplate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TableTemplate): TableTemplate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string table_templates_id */ 1:
                    message.tableTemplatesId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 default_capacity */ 3:
                    message.defaultCapacity = reader.int32();
                    break;
                case /* string default_shape */ 4:
                    message.defaultShape = reader.string();
                    break;
                case /* string default_color */ 5:
                    message.defaultColor = reader.string();
                    break;
                case /* int32 default_price_cents */ 6:
                    message.defaultPriceCents = reader.int32();
                    break;
                case /* bool is_active */ 7:
                    message.isActive = reader.bool();
                    break;
                case /* double default_width */ 8:
                    message.defaultWidth = reader.double();
                    break;
                case /* double default_height */ 9:
                    message.defaultHeight = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TableTemplate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string table_templates_id = 1; */
        if (message.tableTemplatesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tableTemplatesId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 default_capacity = 3; */
        if (message.defaultCapacity !== 0)
            writer.tag(3, WireType.Varint).int32(message.defaultCapacity);
        /* string default_shape = 4; */
        if (message.defaultShape !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.defaultShape);
        /* string default_color = 5; */
        if (message.defaultColor !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.defaultColor);
        /* int32 default_price_cents = 6; */
        if (message.defaultPriceCents !== 0)
            writer.tag(6, WireType.Varint).int32(message.defaultPriceCents);
        /* bool is_active = 7; */
        if (message.isActive !== false)
            writer.tag(7, WireType.Varint).bool(message.isActive);
        /* double default_width = 8; */
        if (message.defaultWidth !== 0)
            writer.tag(8, WireType.Bit64).double(message.defaultWidth);
        /* double default_height = 9; */
        if (message.defaultHeight !== 0)
            writer.tag(9, WireType.Bit64).double(message.defaultHeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.TableTemplate
 */
export const TableTemplate = new TableTemplate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTableTemplateRequest$Type extends MessageType<CreateTableTemplateRequest> {
    constructor() {
        super("svyne.booking.CreateTableTemplateRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "default_capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "default_shape", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "default_color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "default_price_cents", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "default_width", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "default_height", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<CreateTableTemplateRequest>): CreateTableTemplateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.defaultCapacity = 0;
        message.defaultShape = "";
        message.defaultColor = "";
        message.defaultPriceCents = 0;
        message.defaultWidth = 0;
        message.defaultHeight = 0;
        if (value !== undefined)
            reflectionMergePartial<CreateTableTemplateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTableTemplateRequest): CreateTableTemplateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* int32 default_capacity */ 2:
                    message.defaultCapacity = reader.int32();
                    break;
                case /* string default_shape */ 3:
                    message.defaultShape = reader.string();
                    break;
                case /* string default_color */ 4:
                    message.defaultColor = reader.string();
                    break;
                case /* int32 default_price_cents */ 5:
                    message.defaultPriceCents = reader.int32();
                    break;
                case /* double default_width */ 6:
                    message.defaultWidth = reader.double();
                    break;
                case /* double default_height */ 7:
                    message.defaultHeight = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTableTemplateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* int32 default_capacity = 2; */
        if (message.defaultCapacity !== 0)
            writer.tag(2, WireType.Varint).int32(message.defaultCapacity);
        /* string default_shape = 3; */
        if (message.defaultShape !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.defaultShape);
        /* string default_color = 4; */
        if (message.defaultColor !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.defaultColor);
        /* int32 default_price_cents = 5; */
        if (message.defaultPriceCents !== 0)
            writer.tag(5, WireType.Varint).int32(message.defaultPriceCents);
        /* double default_width = 6; */
        if (message.defaultWidth !== 0)
            writer.tag(6, WireType.Bit64).double(message.defaultWidth);
        /* double default_height = 7; */
        if (message.defaultHeight !== 0)
            writer.tag(7, WireType.Bit64).double(message.defaultHeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.CreateTableTemplateRequest
 */
export const CreateTableTemplateRequest = new CreateTableTemplateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListTableTemplatesResponse$Type extends MessageType<ListTableTemplatesResponse> {
    constructor() {
        super("svyne.booking.ListTableTemplatesResponse", [
            { no: 1, name: "templates", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TableTemplate }
        ]);
    }
    create(value?: PartialMessage<ListTableTemplatesResponse>): ListTableTemplatesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.templates = [];
        if (value !== undefined)
            reflectionMergePartial<ListTableTemplatesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListTableTemplatesResponse): ListTableTemplatesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.booking.TableTemplate templates */ 1:
                    message.templates.push(TableTemplate.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListTableTemplatesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.booking.TableTemplate templates = 1; */
        for (let i = 0; i < message.templates.length; i++)
            TableTemplate.internalBinaryWrite(message.templates[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.booking.ListTableTemplatesResponse
 */
export const ListTableTemplatesResponse = new ListTableTemplatesResponse$Type();
/**
 * @generated ServiceType for protobuf service svyne.booking.TableBookingService
 */
export const TableBookingService = new ServiceType("svyne.booking.TableBookingService", [
    { name: "GetEventLayout", options: {}, I: UuidValue, O: EventLayout },
    { name: "SaveEventLayout", options: {}, I: SaveEventLayoutRequest, O: AckResponse },
    { name: "LockTable", options: {}, I: LockTableRequest, O: AckResponse },
    { name: "ReleaseTableLock", options: {}, I: LockTableRequest, O: AckResponse },
    { name: "ListTablesForEvent", options: {}, I: UuidValue, O: ListTablesResponse },
    { name: "ListEventTableTypes", options: {}, I: UuidValue, O: ListEventTableTypesResponse },
    { name: "CreateEventTable", options: {}, I: CreateEventTableRequest, O: UuidValue },
    { name: "DeleteEventTable", options: {}, I: UuidValue, O: AckResponse },
    { name: "CreateEventTicketType", options: {}, I: CreateEventTicketTypeRequest, O: UuidValue },
    { name: "UpdateEventTicketType", options: {}, I: UpdateEventTicketTypeRequest, O: AckResponse },
    { name: "DeleteEventTicketType", options: {}, I: UuidValue, O: AckResponse },
    { name: "CreateTableTemplatePriceRule", options: {}, I: CreateTableTemplatePriceRuleRequest, O: UuidValue },
    { name: "ListTableTemplatePriceRules", options: {}, I: UuidValue, O: ListTableTemplatePriceRulesResponse },
    { name: "DeleteTableTemplatePriceRule", options: {}, I: UuidValue, O: AckResponse },
    { name: "ListTableTemplates", options: {}, I: Empty, O: ListTableTemplatesResponse },
    { name: "CreateTableTemplate", options: {}, I: CreateTableTemplateRequest, O: UuidValue },
    { name: "DeleteTableTemplate", options: {}, I: UuidValue, O: AckResponse }
]);
