/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "enums.proto" (package "entryvine.enums", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message entryvine.enums.ListEnumsRequest
 */
export interface ListEnumsRequest {
    /**
     * @generated from protobuf field: string enum_type = 1;
     */
    enumType: string;
}
/**
 * @generated from protobuf message entryvine.enums.EnumValue
 */
export interface EnumValue {
    /**
     * @generated from protobuf field: string enum_type = 1;
     */
    enumType: string;
    /**
     * @generated from protobuf field: string value = 2;
     */
    value: string;
    /**
     * @generated from protobuf field: int32 int_value = 3;
     */
    intValue: number;
    /**
     * @generated from protobuf field: string used_in = 4;
     */
    usedIn: string;
    /**
     * @generated from protobuf field: string description = 5;
     */
    description: string;
}
/**
 * @generated from protobuf message entryvine.enums.ListEnumsResponse
 */
export interface ListEnumsResponse {
    /**
     * @generated from protobuf field: repeated entryvine.enums.EnumValue values = 1;
     */
    values: EnumValue[];
}
// @generated message type with reflection information, may provide speed optimized methods
class ListEnumsRequest$Type extends MessageType<ListEnumsRequest> {
    constructor() {
        super("entryvine.enums.ListEnumsRequest", [
            { no: 1, name: "enum_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListEnumsRequest>): ListEnumsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.enumType = "";
        if (value !== undefined)
            reflectionMergePartial<ListEnumsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEnumsRequest): ListEnumsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string enum_type */ 1:
                    message.enumType = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEnumsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string enum_type = 1; */
        if (message.enumType !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.enumType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.enums.ListEnumsRequest
 */
export const ListEnumsRequest = new ListEnumsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnumValue$Type extends MessageType<EnumValue> {
    constructor() {
        super("entryvine.enums.EnumValue", [
            { no: 1, name: "enum_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "int_value", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "used_in", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EnumValue>): EnumValue {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.enumType = "";
        message.value = "";
        message.intValue = 0;
        message.usedIn = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<EnumValue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnumValue): EnumValue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string enum_type */ 1:
                    message.enumType = reader.string();
                    break;
                case /* string value */ 2:
                    message.value = reader.string();
                    break;
                case /* int32 int_value */ 3:
                    message.intValue = reader.int32();
                    break;
                case /* string used_in */ 4:
                    message.usedIn = reader.string();
                    break;
                case /* string description */ 5:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnumValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string enum_type = 1; */
        if (message.enumType !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.enumType);
        /* string value = 2; */
        if (message.value !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.value);
        /* int32 int_value = 3; */
        if (message.intValue !== 0)
            writer.tag(3, WireType.Varint).int32(message.intValue);
        /* string used_in = 4; */
        if (message.usedIn !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.usedIn);
        /* string description = 5; */
        if (message.description !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.enums.EnumValue
 */
export const EnumValue = new EnumValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEnumsResponse$Type extends MessageType<ListEnumsResponse> {
    constructor() {
        super("entryvine.enums.ListEnumsResponse", [
            { no: 1, name: "values", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EnumValue }
        ]);
    }
    create(value?: PartialMessage<ListEnumsResponse>): ListEnumsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.values = [];
        if (value !== undefined)
            reflectionMergePartial<ListEnumsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEnumsResponse): ListEnumsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated entryvine.enums.EnumValue values */ 1:
                    message.values.push(EnumValue.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEnumsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated entryvine.enums.EnumValue values = 1; */
        for (let i = 0; i < message.values.length; i++)
            EnumValue.internalBinaryWrite(message.values[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.enums.ListEnumsResponse
 */
export const ListEnumsResponse = new ListEnumsResponse$Type();
/**
 * @generated ServiceType for protobuf service entryvine.enums.EnumService
 */
export const EnumService = new ServiceType("entryvine.enums.EnumService", [
    { name: "ListEnums", options: {}, I: ListEnumsRequest, O: ListEnumsResponse }
]);
