/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "enums.proto" (package "entryvine.enums", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EnumService } from "./enums";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListEnumsResponse } from "./enums";
import type { ListEnumsRequest } from "./enums";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service entryvine.enums.EnumService
 */
export interface IEnumServiceClient {
    /**
     * @generated from protobuf rpc: ListEnums(entryvine.enums.ListEnumsRequest) returns (entryvine.enums.ListEnumsResponse);
     */
    listEnums(input: ListEnumsRequest, options?: RpcOptions): UnaryCall<ListEnumsRequest, ListEnumsResponse>;
}
/**
 * @generated from protobuf service entryvine.enums.EnumService
 */
export class EnumServiceClient implements IEnumServiceClient, ServiceInfo {
    typeName = EnumService.typeName;
    methods = EnumService.methods;
    options = EnumService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListEnums(entryvine.enums.ListEnumsRequest) returns (entryvine.enums.ListEnumsResponse);
     */
    listEnums(input: ListEnumsRequest, options?: RpcOptions): UnaryCall<ListEnumsRequest, ListEnumsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListEnumsRequest, ListEnumsResponse>("unary", this._transport, method, opt, input);
    }
}
