/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "event.proto" (package "ticketspan.event", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EventService } from "./event";
import type { AiSettingsResponse } from "./event";
import type { GenerateEventInfoResponse } from "./event";
import type { GenerateEventInfoRequest } from "./event";
import type { MediaSettings } from "./event";
import type { Empty } from "./common";
import type { ReorderEventImagesRequest } from "./event";
import type { RemoveEventImageRequest } from "./event";
import type { EventImage } from "./event";
import type { AddEventImageRequest } from "./event";
import type { ListEventImagesResponse } from "./event";
import type { ListEventImagesRequest } from "./event";
import type { UpdateScheduleItemRequest } from "./event";
import type { CreateScheduleItemRequest } from "./event";
import type { ListScheduleItemsResponse } from "./event";
import type { SetEventAchRequest } from "./event";
import type { SetEventFeesIncludedRequest } from "./event";
import type { EventStats } from "./event";
import type { ChangeEventStatusRequest } from "./event";
import type { SearchEventsRequest } from "./event";
import type { ListEventsResponse } from "./event";
import type { ListEventsRequest } from "./event";
import type { GetEventBySlugRequest } from "./event";
import type { Event } from "./event";
import type { UuidValue } from "./common";
import type { AckResponse } from "./common";
import type { UpdateEventRequest } from "./event";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateEventResponse } from "./event";
import type { CreateEventRequest } from "./event";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ticketspan.event.EventService
 */
export interface IEventServiceClient {
    /**
     * @generated from protobuf rpc: CreateEvent(ticketspan.event.CreateEventRequest) returns (ticketspan.event.CreateEventResponse);
     */
    createEvent(input: CreateEventRequest, options?: RpcOptions): UnaryCall<CreateEventRequest, CreateEventResponse>;
    /**
     * @generated from protobuf rpc: UpdateEvent(ticketspan.event.UpdateEventRequest) returns (ticketspan.common.AckResponse);
     */
    updateEvent(input: UpdateEventRequest, options?: RpcOptions): UnaryCall<UpdateEventRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: DeleteEvent(ticketspan.common.UuidValue) returns (ticketspan.common.AckResponse);
     */
    deleteEvent(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: GetEvent(ticketspan.common.UuidValue) returns (ticketspan.event.Event);
     */
    getEvent(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Event>;
    /**
     * @generated from protobuf rpc: GetEventBySlug(ticketspan.event.GetEventBySlugRequest) returns (ticketspan.event.Event);
     */
    getEventBySlug(input: GetEventBySlugRequest, options?: RpcOptions): UnaryCall<GetEventBySlugRequest, Event>;
    /**
     * @generated from protobuf rpc: ListEvents(ticketspan.event.ListEventsRequest) returns (ticketspan.event.ListEventsResponse);
     */
    listEvents(input: ListEventsRequest, options?: RpcOptions): UnaryCall<ListEventsRequest, ListEventsResponse>;
    /**
     * @generated from protobuf rpc: SearchEvents(ticketspan.event.SearchEventsRequest) returns (ticketspan.event.ListEventsResponse);
     */
    searchEvents(input: SearchEventsRequest, options?: RpcOptions): UnaryCall<SearchEventsRequest, ListEventsResponse>;
    /**
     * @generated from protobuf rpc: ChangeEventStatus(ticketspan.event.ChangeEventStatusRequest) returns (ticketspan.common.AckResponse);
     */
    changeEventStatus(input: ChangeEventStatusRequest, options?: RpcOptions): UnaryCall<ChangeEventStatusRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: GetEventStats(ticketspan.common.UuidValue) returns (ticketspan.event.EventStats);
     */
    getEventStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, EventStats>;
    /**
     * @generated from protobuf rpc: SetEventFeesIncluded(ticketspan.event.SetEventFeesIncludedRequest) returns (ticketspan.common.AckResponse);
     */
    setEventFeesIncluded(input: SetEventFeesIncludedRequest, options?: RpcOptions): UnaryCall<SetEventFeesIncludedRequest, AckResponse>;
    /**
     * Admin opt-in to offering ACH at checkout (only sticks if the tenant is ACH-enabled).
     *
     * @generated from protobuf rpc: SetEventAch(ticketspan.event.SetEventAchRequest) returns (ticketspan.common.AckResponse);
     */
    setEventAch(input: SetEventAchRequest, options?: RpcOptions): UnaryCall<SetEventAchRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ListScheduleItems(ticketspan.common.UuidValue) returns (ticketspan.event.ListScheduleItemsResponse);
     */
    listScheduleItems(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListScheduleItemsResponse>;
    /**
     * @generated from protobuf rpc: CreateScheduleItem(ticketspan.event.CreateScheduleItemRequest) returns (ticketspan.common.UuidValue);
     */
    createScheduleItem(input: CreateScheduleItemRequest, options?: RpcOptions): UnaryCall<CreateScheduleItemRequest, UuidValue>;
    /**
     * @generated from protobuf rpc: UpdateScheduleItem(ticketspan.event.UpdateScheduleItemRequest) returns (ticketspan.common.AckResponse);
     */
    updateScheduleItem(input: UpdateScheduleItemRequest, options?: RpcOptions): UnaryCall<UpdateScheduleItemRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: DeleteScheduleItem(ticketspan.common.UuidValue) returns (ticketspan.common.AckResponse);
     */
    deleteScheduleItem(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: ListEventImages(ticketspan.event.ListEventImagesRequest) returns (ticketspan.event.ListEventImagesResponse);
     */
    listEventImages(input: ListEventImagesRequest, options?: RpcOptions): UnaryCall<ListEventImagesRequest, ListEventImagesResponse>;
    /**
     * @generated from protobuf rpc: AddEventImage(ticketspan.event.AddEventImageRequest) returns (ticketspan.event.EventImage);
     */
    addEventImage(input: AddEventImageRequest, options?: RpcOptions): UnaryCall<AddEventImageRequest, EventImage>;
    /**
     * @generated from protobuf rpc: RemoveEventImage(ticketspan.event.RemoveEventImageRequest) returns (ticketspan.common.AckResponse);
     */
    removeEventImage(input: RemoveEventImageRequest, options?: RpcOptions): UnaryCall<RemoveEventImageRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: SetPrimaryEventImage(ticketspan.event.RemoveEventImageRequest) returns (ticketspan.common.AckResponse);
     */
    setPrimaryEventImage(input: RemoveEventImageRequest, options?: RpcOptions): UnaryCall<RemoveEventImageRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ReorderEventImages(ticketspan.event.ReorderEventImagesRequest) returns (ticketspan.common.AckResponse);
     */
    reorderEventImages(input: ReorderEventImagesRequest, options?: RpcOptions): UnaryCall<ReorderEventImagesRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: GetMediaSettings(ticketspan.common.Empty) returns (ticketspan.event.MediaSettings);
     */
    getMediaSettings(input: Empty, options?: RpcOptions): UnaryCall<Empty, MediaSettings>;
    /**
     * @generated from protobuf rpc: GenerateEventInfo(ticketspan.event.GenerateEventInfoRequest) returns (ticketspan.event.GenerateEventInfoResponse);
     */
    generateEventInfo(input: GenerateEventInfoRequest, options?: RpcOptions): UnaryCall<GenerateEventInfoRequest, GenerateEventInfoResponse>;
    /**
     * @generated from protobuf rpc: GetAiSettings(ticketspan.common.Empty) returns (ticketspan.event.AiSettingsResponse);
     */
    getAiSettings(input: Empty, options?: RpcOptions): UnaryCall<Empty, AiSettingsResponse>;
}
/**
 * @generated from protobuf service ticketspan.event.EventService
 */
export class EventServiceClient implements IEventServiceClient, ServiceInfo {
    typeName = EventService.typeName;
    methods = EventService.methods;
    options = EventService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateEvent(ticketspan.event.CreateEventRequest) returns (ticketspan.event.CreateEventResponse);
     */
    createEvent(input: CreateEventRequest, options?: RpcOptions): UnaryCall<CreateEventRequest, CreateEventResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateEventRequest, CreateEventResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateEvent(ticketspan.event.UpdateEventRequest) returns (ticketspan.common.AckResponse);
     */
    updateEvent(input: UpdateEventRequest, options?: RpcOptions): UnaryCall<UpdateEventRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateEventRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteEvent(ticketspan.common.UuidValue) returns (ticketspan.common.AckResponse);
     */
    deleteEvent(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetEvent(ticketspan.common.UuidValue) returns (ticketspan.event.Event);
     */
    getEvent(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Event> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, Event>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetEventBySlug(ticketspan.event.GetEventBySlugRequest) returns (ticketspan.event.Event);
     */
    getEventBySlug(input: GetEventBySlugRequest, options?: RpcOptions): UnaryCall<GetEventBySlugRequest, Event> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetEventBySlugRequest, Event>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListEvents(ticketspan.event.ListEventsRequest) returns (ticketspan.event.ListEventsResponse);
     */
    listEvents(input: ListEventsRequest, options?: RpcOptions): UnaryCall<ListEventsRequest, ListEventsResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListEventsRequest, ListEventsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchEvents(ticketspan.event.SearchEventsRequest) returns (ticketspan.event.ListEventsResponse);
     */
    searchEvents(input: SearchEventsRequest, options?: RpcOptions): UnaryCall<SearchEventsRequest, ListEventsResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchEventsRequest, ListEventsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ChangeEventStatus(ticketspan.event.ChangeEventStatusRequest) returns (ticketspan.common.AckResponse);
     */
    changeEventStatus(input: ChangeEventStatusRequest, options?: RpcOptions): UnaryCall<ChangeEventStatusRequest, AckResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChangeEventStatusRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetEventStats(ticketspan.common.UuidValue) returns (ticketspan.event.EventStats);
     */
    getEventStats(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, EventStats> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, EventStats>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetEventFeesIncluded(ticketspan.event.SetEventFeesIncludedRequest) returns (ticketspan.common.AckResponse);
     */
    setEventFeesIncluded(input: SetEventFeesIncludedRequest, options?: RpcOptions): UnaryCall<SetEventFeesIncludedRequest, AckResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetEventFeesIncludedRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Admin opt-in to offering ACH at checkout (only sticks if the tenant is ACH-enabled).
     *
     * @generated from protobuf rpc: SetEventAch(ticketspan.event.SetEventAchRequest) returns (ticketspan.common.AckResponse);
     */
    setEventAch(input: SetEventAchRequest, options?: RpcOptions): UnaryCall<SetEventAchRequest, AckResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetEventAchRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListScheduleItems(ticketspan.common.UuidValue) returns (ticketspan.event.ListScheduleItemsResponse);
     */
    listScheduleItems(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListScheduleItemsResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, ListScheduleItemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateScheduleItem(ticketspan.event.CreateScheduleItemRequest) returns (ticketspan.common.UuidValue);
     */
    createScheduleItem(input: CreateScheduleItemRequest, options?: RpcOptions): UnaryCall<CreateScheduleItemRequest, UuidValue> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateScheduleItemRequest, UuidValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateScheduleItem(ticketspan.event.UpdateScheduleItemRequest) returns (ticketspan.common.AckResponse);
     */
    updateScheduleItem(input: UpdateScheduleItemRequest, options?: RpcOptions): UnaryCall<UpdateScheduleItemRequest, AckResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateScheduleItemRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteScheduleItem(ticketspan.common.UuidValue) returns (ticketspan.common.AckResponse);
     */
    deleteScheduleItem(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListEventImages(ticketspan.event.ListEventImagesRequest) returns (ticketspan.event.ListEventImagesResponse);
     */
    listEventImages(input: ListEventImagesRequest, options?: RpcOptions): UnaryCall<ListEventImagesRequest, ListEventImagesResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListEventImagesRequest, ListEventImagesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddEventImage(ticketspan.event.AddEventImageRequest) returns (ticketspan.event.EventImage);
     */
    addEventImage(input: AddEventImageRequest, options?: RpcOptions): UnaryCall<AddEventImageRequest, EventImage> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddEventImageRequest, EventImage>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveEventImage(ticketspan.event.RemoveEventImageRequest) returns (ticketspan.common.AckResponse);
     */
    removeEventImage(input: RemoveEventImageRequest, options?: RpcOptions): UnaryCall<RemoveEventImageRequest, AckResponse> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveEventImageRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetPrimaryEventImage(ticketspan.event.RemoveEventImageRequest) returns (ticketspan.common.AckResponse);
     */
    setPrimaryEventImage(input: RemoveEventImageRequest, options?: RpcOptions): UnaryCall<RemoveEventImageRequest, AckResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveEventImageRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReorderEventImages(ticketspan.event.ReorderEventImagesRequest) returns (ticketspan.common.AckResponse);
     */
    reorderEventImages(input: ReorderEventImagesRequest, options?: RpcOptions): UnaryCall<ReorderEventImagesRequest, AckResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReorderEventImagesRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMediaSettings(ticketspan.common.Empty) returns (ticketspan.event.MediaSettings);
     */
    getMediaSettings(input: Empty, options?: RpcOptions): UnaryCall<Empty, MediaSettings> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, MediaSettings>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GenerateEventInfo(ticketspan.event.GenerateEventInfoRequest) returns (ticketspan.event.GenerateEventInfoResponse);
     */
    generateEventInfo(input: GenerateEventInfoRequest, options?: RpcOptions): UnaryCall<GenerateEventInfoRequest, GenerateEventInfoResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<GenerateEventInfoRequest, GenerateEventInfoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAiSettings(ticketspan.common.Empty) returns (ticketspan.event.AiSettingsResponse);
     */
    getAiSettings(input: Empty, options?: RpcOptions): UnaryCall<Empty, AiSettingsResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, AiSettingsResponse>("unary", this._transport, method, opt, input);
    }
}
