/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "event.proto" (package "svyne.event", syntax proto3)
// tslint:disable
import { Empty } from "./common";
import { UuidValue } from "./common";
import { AckResponse } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PageMeta } from "./common";
import { PageRequest } from "./common";
/**
 * @generated from protobuf message svyne.event.EventImage
 */
export interface EventImage {
    /**
     * @generated from protobuf field: string images_id = 1;
     */
    imagesId: string;
    /**
     * @generated from protobuf field: string storage_key = 2;
     */
    storageKey: string;
    /**
     * @generated from protobuf field: string type = 3;
     */
    type: string;
    /**
     * @generated from protobuf field: bool is_primary = 4;
     */
    isPrimary: boolean;
    /**
     * @generated from protobuf field: int32 sort_order = 5;
     */
    sortOrder: number;
}
/**
 * @generated from protobuf message svyne.event.ListEventImagesRequest
 */
export interface ListEventImagesRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string type = 2;
     */
    type: string;
}
/**
 * @generated from protobuf message svyne.event.ListEventImagesResponse
 */
export interface ListEventImagesResponse {
    /**
     * @generated from protobuf field: repeated svyne.event.EventImage images = 1;
     */
    images: EventImage[];
}
/**
 * @generated from protobuf message svyne.event.AddEventImageRequest
 */
export interface AddEventImageRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string images_id = 2;
     */
    imagesId: string;
    /**
     * @generated from protobuf field: string type = 3;
     */
    type: string;
}
/**
 * @generated from protobuf message svyne.event.RemoveEventImageRequest
 */
export interface RemoveEventImageRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string images_id = 2;
     */
    imagesId: string;
}
/**
 * @generated from protobuf message svyne.event.ReorderEventImagesRequest
 */
export interface ReorderEventImagesRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string type = 2;
     */
    type: string;
    /**
     * @generated from protobuf field: repeated string images_id = 3;
     */
    imagesId: string[];
}
/**
 * @generated from protobuf message svyne.event.MediaSettings
 */
export interface MediaSettings {
    /**
     * @generated from protobuf field: string event_image_aspect_ratio = 1;
     */
    eventImageAspectRatio: string;
    /**
     * @generated from protobuf field: string event_thumbnail_aspect_ratio = 2;
     */
    eventThumbnailAspectRatio: string;
}
/**
 * @generated from protobuf message svyne.event.ScheduleItem
 */
export interface ScheduleItem {
    /**
     * @generated from protobuf field: string schedule_items_id = 1;
     */
    scheduleItemsId: string;
    /**
     * @generated from protobuf field: string events_id = 2;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string title = 3;
     */
    title: string;
    /**
     * @generated from protobuf field: string type_category = 4;
     */
    typeCategory: string;
    /**
     * @generated from protobuf field: int64 start_time = 5;
     */
    startTime: string;
    /**
     * @generated from protobuf field: int64 end_time = 6;
     */
    endTime: string;
}
/**
 * @generated from protobuf message svyne.event.ListScheduleItemsResponse
 */
export interface ListScheduleItemsResponse {
    /**
     * @generated from protobuf field: repeated svyne.event.ScheduleItem items = 1;
     */
    items: ScheduleItem[];
}
/**
 * @generated from protobuf message svyne.event.CreateScheduleItemRequest
 */
export interface CreateScheduleItemRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string type_category = 3;
     */
    typeCategory: string;
    /**
     * @generated from protobuf field: int64 start_time = 4;
     */
    startTime: string;
    /**
     * @generated from protobuf field: int64 end_time = 5;
     */
    endTime: string;
}
/**
 * @generated from protobuf message svyne.event.UpdateScheduleItemRequest
 */
export interface UpdateScheduleItemRequest {
    /**
     * @generated from protobuf field: string schedule_items_id = 1;
     */
    scheduleItemsId: string;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string type_category = 3;
     */
    typeCategory: string;
    /**
     * @generated from protobuf field: int64 start_time = 4;
     */
    startTime: string;
    /**
     * @generated from protobuf field: int64 end_time = 5;
     */
    endTime: string;
}
/**
 * @generated from protobuf message svyne.event.SetEventFeesIncludedRequest
 */
export interface SetEventFeesIncludedRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: bool fees_included = 2;
     */
    feesIncluded: boolean;
}
/**
 * @generated from protobuf message svyne.event.Event
 */
export interface Event {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string tenants_id = 2;
     */
    tenantsId: string;
    /**
     * @generated from protobuf field: string title = 3;
     */
    title: string;
    /**
     * @generated from protobuf field: string slug = 4;
     */
    slug: string;
    /**
     * @generated from protobuf field: string description = 5;
     */
    description: string;
    /**
     * @generated from protobuf field: string status = 6;
     */
    status: string;
    /**
     * @generated from protobuf field: string category = 7;
     */
    category: string;
    /**
     * @generated from protobuf field: int64 start_date = 8;
     */
    startDate: string;
    /**
     * @generated from protobuf field: int64 end_date = 9;
     */
    endDate: string;
    /**
     * @generated from protobuf field: string image_path = 10;
     */
    imagePath: string;
    /**
     * @generated from protobuf field: bool is_featured = 11;
     */
    isFeatured: boolean;
    /**
     * @generated from protobuf field: string layout_mode = 12;
     */
    layoutMode: string;
    /**
     * @generated from protobuf field: int32 total_capacity = 13;
     */
    totalCapacity: number; // calculated: sum of ticket-type / table capacity (read-only)
    /**
     * @generated from protobuf field: string venues_id = 14;
     */
    venuesId: string;
    /**
     * @generated from protobuf field: string performers_json = 15;
     */
    performersJson: string;
    /**
     * @generated from protobuf field: string sponsors_json = 16;
     */
    sponsorsJson: string;
    /**
     * @generated from protobuf field: bool fees_included = 17;
     */
    feesIncluded: boolean;
    /**
     * @generated from protobuf field: string event_type = 18;
     */
    eventType: string; // Open | Table | Both
    /**
     * @generated from protobuf field: string primary_image_id = 19;
     */
    primaryImageId: string; // images_id of primary thumbnail (fallback event image)
}
/**
 * @generated from protobuf message svyne.event.GetEventBySlugRequest
 */
export interface GetEventBySlugRequest {
    /**
     * @generated from protobuf field: string slug = 1;
     */
    slug: string;
}
/**
 * @generated from protobuf message svyne.event.CreateEventRequest
 */
export interface CreateEventRequest {
    /**
     * @generated from protobuf field: string title = 1;
     */
    title: string;
    /**
     * @generated from protobuf field: string slug = 2;
     */
    slug: string;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: string status = 4;
     */
    status: string;
    /**
     * @generated from protobuf field: string category = 5;
     */
    category: string;
    /**
     * @generated from protobuf field: int64 start_date = 6;
     */
    startDate: string;
    /**
     * @generated from protobuf field: int64 end_date = 7;
     */
    endDate: string;
    /**
     * @generated from protobuf field: string image_path = 8;
     */
    imagePath: string;
    /**
     * @generated from protobuf field: bool is_featured = 9;
     */
    isFeatured: boolean;
    /**
     * @generated from protobuf field: string layout_mode = 10;
     */
    layoutMode: string;
    /**
     * @generated from protobuf field: string venues_id = 14;
     */
    venuesId: string;
    /**
     * @generated from protobuf field: int64 scheduled_publish_at = 15;
     */
    scheduledPublishAt: string;
    /**
     * @generated from protobuf field: string event_type = 16;
     */
    eventType: string; // Open | Table | Both; default Open
}
/**
 * @generated from protobuf message svyne.event.CreateEventResponse
 */
export interface CreateEventResponse {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
}
/**
 * @generated from protobuf message svyne.event.UpdateEventRequest
 */
export interface UpdateEventRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: string category = 4;
     */
    category: string;
    /**
     * @generated from protobuf field: int64 start_date = 5;
     */
    startDate: string;
    /**
     * @generated from protobuf field: int64 end_date = 6;
     */
    endDate: string;
    /**
     * @generated from protobuf field: string image_path = 7;
     */
    imagePath: string;
    /**
     * @generated from protobuf field: bool is_featured = 8;
     */
    isFeatured: boolean;
    /**
     * @generated from protobuf field: string venues_id = 10;
     */
    venuesId: string;
    /**
     * @generated from protobuf field: string event_type = 11;
     */
    eventType: string; // Open | Table | Both; empty = unchanged
}
/**
 * @generated from protobuf message svyne.event.ChangeEventStatusRequest
 */
export interface ChangeEventStatusRequest {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: string status = 2;
     */
    status: string;
}
/**
 * @generated from protobuf message svyne.event.ListEventsRequest
 */
export interface ListEventsRequest {
    /**
     * @generated from protobuf field: svyne.common.PageRequest page = 1;
     */
    page?: PageRequest;
    /**
     * @generated from protobuf field: string status = 2;
     */
    status: string;
    /**
     * @generated from protobuf field: string category = 3;
     */
    category: string;
}
/**
 * @generated from protobuf message svyne.event.SearchEventsRequest
 */
export interface SearchEventsRequest {
    /**
     * @generated from protobuf field: string query = 1;
     */
    query: string;
}
/**
 * @generated from protobuf message svyne.event.ListEventsResponse
 */
export interface ListEventsResponse {
    /**
     * @generated from protobuf field: repeated svyne.event.Event events = 1;
     */
    events: Event[];
    /**
     * @generated from protobuf field: svyne.common.PageMeta meta = 2;
     */
    meta?: PageMeta;
}
/**
 * @generated from protobuf message svyne.event.EventStats
 */
export interface EventStats {
    /**
     * @generated from protobuf field: string events_id = 1;
     */
    eventsId: string;
    /**
     * @generated from protobuf field: int32 total_bookings = 2;
     */
    totalBookings: number;
    /**
     * @generated from protobuf field: int32 tickets_sold = 3;
     */
    ticketsSold: number;
    /**
     * @generated from protobuf field: int64 revenue_cents = 4;
     */
    revenueCents: string;
    /**
     * @generated from protobuf field: int32 checked_in = 5;
     */
    checkedIn: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class EventImage$Type extends MessageType<EventImage> {
    constructor() {
        super("svyne.event.EventImage", [
            { no: 1, name: "images_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "storage_key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "is_primary", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "sort_order", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<EventImage>): EventImage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.imagesId = "";
        message.storageKey = "";
        message.type = "";
        message.isPrimary = false;
        message.sortOrder = 0;
        if (value !== undefined)
            reflectionMergePartial<EventImage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventImage): EventImage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string images_id */ 1:
                    message.imagesId = reader.string();
                    break;
                case /* string storage_key */ 2:
                    message.storageKey = reader.string();
                    break;
                case /* string type */ 3:
                    message.type = reader.string();
                    break;
                case /* bool is_primary */ 4:
                    message.isPrimary = reader.bool();
                    break;
                case /* int32 sort_order */ 5:
                    message.sortOrder = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventImage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string images_id = 1; */
        if (message.imagesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.imagesId);
        /* string storage_key = 2; */
        if (message.storageKey !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.storageKey);
        /* string type = 3; */
        if (message.type !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.type);
        /* bool is_primary = 4; */
        if (message.isPrimary !== false)
            writer.tag(4, WireType.Varint).bool(message.isPrimary);
        /* int32 sort_order = 5; */
        if (message.sortOrder !== 0)
            writer.tag(5, WireType.Varint).int32(message.sortOrder);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.EventImage
 */
export const EventImage = new EventImage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventImagesRequest$Type extends MessageType<ListEventImagesRequest> {
    constructor() {
        super("svyne.event.ListEventImagesRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListEventImagesRequest>): ListEventImagesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.type = "";
        if (value !== undefined)
            reflectionMergePartial<ListEventImagesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventImagesRequest): ListEventImagesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string type */ 2:
                    message.type = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventImagesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string type = 2; */
        if (message.type !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.ListEventImagesRequest
 */
export const ListEventImagesRequest = new ListEventImagesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventImagesResponse$Type extends MessageType<ListEventImagesResponse> {
    constructor() {
        super("svyne.event.ListEventImagesResponse", [
            { no: 1, name: "images", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventImage }
        ]);
    }
    create(value?: PartialMessage<ListEventImagesResponse>): ListEventImagesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.images = [];
        if (value !== undefined)
            reflectionMergePartial<ListEventImagesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventImagesResponse): ListEventImagesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.event.EventImage images */ 1:
                    message.images.push(EventImage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventImagesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.event.EventImage images = 1; */
        for (let i = 0; i < message.images.length; i++)
            EventImage.internalBinaryWrite(message.images[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.ListEventImagesResponse
 */
export const ListEventImagesResponse = new ListEventImagesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddEventImageRequest$Type extends MessageType<AddEventImageRequest> {
    constructor() {
        super("svyne.event.AddEventImageRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "images_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddEventImageRequest>): AddEventImageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.imagesId = "";
        message.type = "";
        if (value !== undefined)
            reflectionMergePartial<AddEventImageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddEventImageRequest): AddEventImageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string images_id */ 2:
                    message.imagesId = reader.string();
                    break;
                case /* string type */ 3:
                    message.type = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddEventImageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string images_id = 2; */
        if (message.imagesId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.imagesId);
        /* string type = 3; */
        if (message.type !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.AddEventImageRequest
 */
export const AddEventImageRequest = new AddEventImageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveEventImageRequest$Type extends MessageType<RemoveEventImageRequest> {
    constructor() {
        super("svyne.event.RemoveEventImageRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "images_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RemoveEventImageRequest>): RemoveEventImageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.imagesId = "";
        if (value !== undefined)
            reflectionMergePartial<RemoveEventImageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveEventImageRequest): RemoveEventImageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string images_id */ 2:
                    message.imagesId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveEventImageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string images_id = 2; */
        if (message.imagesId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.imagesId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.RemoveEventImageRequest
 */
export const RemoveEventImageRequest = new RemoveEventImageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReorderEventImagesRequest$Type extends MessageType<ReorderEventImagesRequest> {
    constructor() {
        super("svyne.event.ReorderEventImagesRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "images_id", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReorderEventImagesRequest>): ReorderEventImagesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.type = "";
        message.imagesId = [];
        if (value !== undefined)
            reflectionMergePartial<ReorderEventImagesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReorderEventImagesRequest): ReorderEventImagesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string type */ 2:
                    message.type = reader.string();
                    break;
                case /* repeated string images_id */ 3:
                    message.imagesId.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReorderEventImagesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string type = 2; */
        if (message.type !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.type);
        /* repeated string images_id = 3; */
        for (let i = 0; i < message.imagesId.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.imagesId[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.ReorderEventImagesRequest
 */
export const ReorderEventImagesRequest = new ReorderEventImagesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MediaSettings$Type extends MessageType<MediaSettings> {
    constructor() {
        super("svyne.event.MediaSettings", [
            { no: 1, name: "event_image_aspect_ratio", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "event_thumbnail_aspect_ratio", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MediaSettings>): MediaSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventImageAspectRatio = "";
        message.eventThumbnailAspectRatio = "";
        if (value !== undefined)
            reflectionMergePartial<MediaSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MediaSettings): MediaSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_image_aspect_ratio */ 1:
                    message.eventImageAspectRatio = reader.string();
                    break;
                case /* string event_thumbnail_aspect_ratio */ 2:
                    message.eventThumbnailAspectRatio = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MediaSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_image_aspect_ratio = 1; */
        if (message.eventImageAspectRatio !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventImageAspectRatio);
        /* string event_thumbnail_aspect_ratio = 2; */
        if (message.eventThumbnailAspectRatio !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventThumbnailAspectRatio);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.MediaSettings
 */
export const MediaSettings = new MediaSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScheduleItem$Type extends MessageType<ScheduleItem> {
    constructor() {
        super("svyne.event.ScheduleItem", [
            { no: 1, name: "schedule_items_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type_category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "start_time", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 6, name: "end_time", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<ScheduleItem>): ScheduleItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.scheduleItemsId = "";
        message.eventsId = "";
        message.title = "";
        message.typeCategory = "";
        message.startTime = "0";
        message.endTime = "0";
        if (value !== undefined)
            reflectionMergePartial<ScheduleItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScheduleItem): ScheduleItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string schedule_items_id */ 1:
                    message.scheduleItemsId = reader.string();
                    break;
                case /* string events_id */ 2:
                    message.eventsId = reader.string();
                    break;
                case /* string title */ 3:
                    message.title = reader.string();
                    break;
                case /* string type_category */ 4:
                    message.typeCategory = reader.string();
                    break;
                case /* int64 start_time */ 5:
                    message.startTime = reader.int64().toString();
                    break;
                case /* int64 end_time */ 6:
                    message.endTime = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScheduleItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string schedule_items_id = 1; */
        if (message.scheduleItemsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.scheduleItemsId);
        /* string events_id = 2; */
        if (message.eventsId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventsId);
        /* string title = 3; */
        if (message.title !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.title);
        /* string type_category = 4; */
        if (message.typeCategory !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.typeCategory);
        /* int64 start_time = 5; */
        if (message.startTime !== "0")
            writer.tag(5, WireType.Varint).int64(message.startTime);
        /* int64 end_time = 6; */
        if (message.endTime !== "0")
            writer.tag(6, WireType.Varint).int64(message.endTime);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.ScheduleItem
 */
export const ScheduleItem = new ScheduleItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListScheduleItemsResponse$Type extends MessageType<ListScheduleItemsResponse> {
    constructor() {
        super("svyne.event.ListScheduleItemsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ScheduleItem }
        ]);
    }
    create(value?: PartialMessage<ListScheduleItemsResponse>): ListScheduleItemsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<ListScheduleItemsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListScheduleItemsResponse): ListScheduleItemsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.event.ScheduleItem items */ 1:
                    message.items.push(ScheduleItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListScheduleItemsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.event.ScheduleItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            ScheduleItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.ListScheduleItemsResponse
 */
export const ListScheduleItemsResponse = new ListScheduleItemsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateScheduleItemRequest$Type extends MessageType<CreateScheduleItemRequest> {
    constructor() {
        super("svyne.event.CreateScheduleItemRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type_category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "start_time", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "end_time", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<CreateScheduleItemRequest>): CreateScheduleItemRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.title = "";
        message.typeCategory = "";
        message.startTime = "0";
        message.endTime = "0";
        if (value !== undefined)
            reflectionMergePartial<CreateScheduleItemRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateScheduleItemRequest): CreateScheduleItemRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string type_category */ 3:
                    message.typeCategory = reader.string();
                    break;
                case /* int64 start_time */ 4:
                    message.startTime = reader.int64().toString();
                    break;
                case /* int64 end_time */ 5:
                    message.endTime = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateScheduleItemRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string type_category = 3; */
        if (message.typeCategory !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.typeCategory);
        /* int64 start_time = 4; */
        if (message.startTime !== "0")
            writer.tag(4, WireType.Varint).int64(message.startTime);
        /* int64 end_time = 5; */
        if (message.endTime !== "0")
            writer.tag(5, WireType.Varint).int64(message.endTime);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.CreateScheduleItemRequest
 */
export const CreateScheduleItemRequest = new CreateScheduleItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateScheduleItemRequest$Type extends MessageType<UpdateScheduleItemRequest> {
    constructor() {
        super("svyne.event.UpdateScheduleItemRequest", [
            { no: 1, name: "schedule_items_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type_category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "start_time", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "end_time", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateScheduleItemRequest>): UpdateScheduleItemRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.scheduleItemsId = "";
        message.title = "";
        message.typeCategory = "";
        message.startTime = "0";
        message.endTime = "0";
        if (value !== undefined)
            reflectionMergePartial<UpdateScheduleItemRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateScheduleItemRequest): UpdateScheduleItemRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string schedule_items_id */ 1:
                    message.scheduleItemsId = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string type_category */ 3:
                    message.typeCategory = reader.string();
                    break;
                case /* int64 start_time */ 4:
                    message.startTime = reader.int64().toString();
                    break;
                case /* int64 end_time */ 5:
                    message.endTime = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateScheduleItemRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string schedule_items_id = 1; */
        if (message.scheduleItemsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.scheduleItemsId);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string type_category = 3; */
        if (message.typeCategory !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.typeCategory);
        /* int64 start_time = 4; */
        if (message.startTime !== "0")
            writer.tag(4, WireType.Varint).int64(message.startTime);
        /* int64 end_time = 5; */
        if (message.endTime !== "0")
            writer.tag(5, WireType.Varint).int64(message.endTime);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.UpdateScheduleItemRequest
 */
export const UpdateScheduleItemRequest = new UpdateScheduleItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetEventFeesIncludedRequest$Type extends MessageType<SetEventFeesIncludedRequest> {
    constructor() {
        super("svyne.event.SetEventFeesIncludedRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "fees_included", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SetEventFeesIncludedRequest>): SetEventFeesIncludedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.feesIncluded = false;
        if (value !== undefined)
            reflectionMergePartial<SetEventFeesIncludedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetEventFeesIncludedRequest): SetEventFeesIncludedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* bool fees_included */ 2:
                    message.feesIncluded = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetEventFeesIncludedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* bool fees_included = 2; */
        if (message.feesIncluded !== false)
            writer.tag(2, WireType.Varint).bool(message.feesIncluded);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.SetEventFeesIncludedRequest
 */
export const SetEventFeesIncludedRequest = new SetEventFeesIncludedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Event$Type extends MessageType<Event> {
    constructor() {
        super("svyne.event.Event", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tenants_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "start_date", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "end_date", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 10, name: "image_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "is_featured", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "layout_mode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "total_capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "venues_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "performers_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "sponsors_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "fees_included", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "event_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "primary_image_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Event>): Event {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.tenantsId = "";
        message.title = "";
        message.slug = "";
        message.description = "";
        message.status = "";
        message.category = "";
        message.startDate = "0";
        message.endDate = "0";
        message.imagePath = "";
        message.isFeatured = false;
        message.layoutMode = "";
        message.totalCapacity = 0;
        message.venuesId = "";
        message.performersJson = "";
        message.sponsorsJson = "";
        message.feesIncluded = false;
        message.eventType = "";
        message.primaryImageId = "";
        if (value !== undefined)
            reflectionMergePartial<Event>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Event): Event {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string tenants_id */ 2:
                    message.tenantsId = reader.string();
                    break;
                case /* string title */ 3:
                    message.title = reader.string();
                    break;
                case /* string slug */ 4:
                    message.slug = reader.string();
                    break;
                case /* string description */ 5:
                    message.description = reader.string();
                    break;
                case /* string status */ 6:
                    message.status = reader.string();
                    break;
                case /* string category */ 7:
                    message.category = reader.string();
                    break;
                case /* int64 start_date */ 8:
                    message.startDate = reader.int64().toString();
                    break;
                case /* int64 end_date */ 9:
                    message.endDate = reader.int64().toString();
                    break;
                case /* string image_path */ 10:
                    message.imagePath = reader.string();
                    break;
                case /* bool is_featured */ 11:
                    message.isFeatured = reader.bool();
                    break;
                case /* string layout_mode */ 12:
                    message.layoutMode = reader.string();
                    break;
                case /* int32 total_capacity */ 13:
                    message.totalCapacity = reader.int32();
                    break;
                case /* string venues_id */ 14:
                    message.venuesId = reader.string();
                    break;
                case /* string performers_json */ 15:
                    message.performersJson = reader.string();
                    break;
                case /* string sponsors_json */ 16:
                    message.sponsorsJson = reader.string();
                    break;
                case /* bool fees_included */ 17:
                    message.feesIncluded = reader.bool();
                    break;
                case /* string event_type */ 18:
                    message.eventType = reader.string();
                    break;
                case /* string primary_image_id */ 19:
                    message.primaryImageId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Event, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string tenants_id = 2; */
        if (message.tenantsId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tenantsId);
        /* string title = 3; */
        if (message.title !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.title);
        /* string slug = 4; */
        if (message.slug !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.slug);
        /* string description = 5; */
        if (message.description !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.description);
        /* string status = 6; */
        if (message.status !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.status);
        /* string category = 7; */
        if (message.category !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.category);
        /* int64 start_date = 8; */
        if (message.startDate !== "0")
            writer.tag(8, WireType.Varint).int64(message.startDate);
        /* int64 end_date = 9; */
        if (message.endDate !== "0")
            writer.tag(9, WireType.Varint).int64(message.endDate);
        /* string image_path = 10; */
        if (message.imagePath !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.imagePath);
        /* bool is_featured = 11; */
        if (message.isFeatured !== false)
            writer.tag(11, WireType.Varint).bool(message.isFeatured);
        /* string layout_mode = 12; */
        if (message.layoutMode !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.layoutMode);
        /* int32 total_capacity = 13; */
        if (message.totalCapacity !== 0)
            writer.tag(13, WireType.Varint).int32(message.totalCapacity);
        /* string venues_id = 14; */
        if (message.venuesId !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.venuesId);
        /* string performers_json = 15; */
        if (message.performersJson !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.performersJson);
        /* string sponsors_json = 16; */
        if (message.sponsorsJson !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.sponsorsJson);
        /* bool fees_included = 17; */
        if (message.feesIncluded !== false)
            writer.tag(17, WireType.Varint).bool(message.feesIncluded);
        /* string event_type = 18; */
        if (message.eventType !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.eventType);
        /* string primary_image_id = 19; */
        if (message.primaryImageId !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.primaryImageId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.Event
 */
export const Event = new Event$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetEventBySlugRequest$Type extends MessageType<GetEventBySlugRequest> {
    constructor() {
        super("svyne.event.GetEventBySlugRequest", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetEventBySlugRequest>): GetEventBySlugRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        if (value !== undefined)
            reflectionMergePartial<GetEventBySlugRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetEventBySlugRequest): GetEventBySlugRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetEventBySlugRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.GetEventBySlugRequest
 */
export const GetEventBySlugRequest = new GetEventBySlugRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateEventRequest$Type extends MessageType<CreateEventRequest> {
    constructor() {
        super("svyne.event.CreateEventRequest", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "start_date", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 7, name: "end_date", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "image_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "is_featured", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "layout_mode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "venues_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "scheduled_publish_at", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 16, name: "event_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateEventRequest>): CreateEventRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.slug = "";
        message.description = "";
        message.status = "";
        message.category = "";
        message.startDate = "0";
        message.endDate = "0";
        message.imagePath = "";
        message.isFeatured = false;
        message.layoutMode = "";
        message.venuesId = "";
        message.scheduledPublishAt = "0";
        message.eventType = "";
        if (value !== undefined)
            reflectionMergePartial<CreateEventRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateEventRequest): CreateEventRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string slug */ 2:
                    message.slug = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string status */ 4:
                    message.status = reader.string();
                    break;
                case /* string category */ 5:
                    message.category = reader.string();
                    break;
                case /* int64 start_date */ 6:
                    message.startDate = reader.int64().toString();
                    break;
                case /* int64 end_date */ 7:
                    message.endDate = reader.int64().toString();
                    break;
                case /* string image_path */ 8:
                    message.imagePath = reader.string();
                    break;
                case /* bool is_featured */ 9:
                    message.isFeatured = reader.bool();
                    break;
                case /* string layout_mode */ 10:
                    message.layoutMode = reader.string();
                    break;
                case /* string venues_id */ 14:
                    message.venuesId = reader.string();
                    break;
                case /* int64 scheduled_publish_at */ 15:
                    message.scheduledPublishAt = reader.int64().toString();
                    break;
                case /* string event_type */ 16:
                    message.eventType = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateEventRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string slug = 2; */
        if (message.slug !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.slug);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string status = 4; */
        if (message.status !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.status);
        /* string category = 5; */
        if (message.category !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.category);
        /* int64 start_date = 6; */
        if (message.startDate !== "0")
            writer.tag(6, WireType.Varint).int64(message.startDate);
        /* int64 end_date = 7; */
        if (message.endDate !== "0")
            writer.tag(7, WireType.Varint).int64(message.endDate);
        /* string image_path = 8; */
        if (message.imagePath !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.imagePath);
        /* bool is_featured = 9; */
        if (message.isFeatured !== false)
            writer.tag(9, WireType.Varint).bool(message.isFeatured);
        /* string layout_mode = 10; */
        if (message.layoutMode !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.layoutMode);
        /* string venues_id = 14; */
        if (message.venuesId !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.venuesId);
        /* int64 scheduled_publish_at = 15; */
        if (message.scheduledPublishAt !== "0")
            writer.tag(15, WireType.Varint).int64(message.scheduledPublishAt);
        /* string event_type = 16; */
        if (message.eventType !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.eventType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.CreateEventRequest
 */
export const CreateEventRequest = new CreateEventRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateEventResponse$Type extends MessageType<CreateEventResponse> {
    constructor() {
        super("svyne.event.CreateEventResponse", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateEventResponse>): CreateEventResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        if (value !== undefined)
            reflectionMergePartial<CreateEventResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateEventResponse): CreateEventResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateEventResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.CreateEventResponse
 */
export const CreateEventResponse = new CreateEventResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateEventRequest$Type extends MessageType<UpdateEventRequest> {
    constructor() {
        super("svyne.event.UpdateEventRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "start_date", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 6, name: "end_date", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 7, name: "image_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "is_featured", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "venues_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "event_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateEventRequest>): UpdateEventRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.title = "";
        message.description = "";
        message.category = "";
        message.startDate = "0";
        message.endDate = "0";
        message.imagePath = "";
        message.isFeatured = false;
        message.venuesId = "";
        message.eventType = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateEventRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateEventRequest): UpdateEventRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string category */ 4:
                    message.category = reader.string();
                    break;
                case /* int64 start_date */ 5:
                    message.startDate = reader.int64().toString();
                    break;
                case /* int64 end_date */ 6:
                    message.endDate = reader.int64().toString();
                    break;
                case /* string image_path */ 7:
                    message.imagePath = reader.string();
                    break;
                case /* bool is_featured */ 8:
                    message.isFeatured = reader.bool();
                    break;
                case /* string venues_id */ 10:
                    message.venuesId = reader.string();
                    break;
                case /* string event_type */ 11:
                    message.eventType = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateEventRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string category = 4; */
        if (message.category !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.category);
        /* int64 start_date = 5; */
        if (message.startDate !== "0")
            writer.tag(5, WireType.Varint).int64(message.startDate);
        /* int64 end_date = 6; */
        if (message.endDate !== "0")
            writer.tag(6, WireType.Varint).int64(message.endDate);
        /* string image_path = 7; */
        if (message.imagePath !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.imagePath);
        /* bool is_featured = 8; */
        if (message.isFeatured !== false)
            writer.tag(8, WireType.Varint).bool(message.isFeatured);
        /* string venues_id = 10; */
        if (message.venuesId !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.venuesId);
        /* string event_type = 11; */
        if (message.eventType !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.eventType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.UpdateEventRequest
 */
export const UpdateEventRequest = new UpdateEventRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChangeEventStatusRequest$Type extends MessageType<ChangeEventStatusRequest> {
    constructor() {
        super("svyne.event.ChangeEventStatusRequest", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ChangeEventStatusRequest>): ChangeEventStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<ChangeEventStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChangeEventStatusRequest): ChangeEventStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChangeEventStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.ChangeEventStatusRequest
 */
export const ChangeEventStatusRequest = new ChangeEventStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventsRequest$Type extends MessageType<ListEventsRequest> {
    constructor() {
        super("svyne.event.ListEventsRequest", [
            { no: 1, name: "page", kind: "message", T: () => PageRequest },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListEventsRequest>): ListEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = "";
        message.category = "";
        if (value !== undefined)
            reflectionMergePartial<ListEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventsRequest): ListEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* svyne.common.PageRequest page */ 1:
                    message.page = PageRequest.internalBinaryRead(reader, reader.uint32(), options, message.page);
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* string category */ 3:
                    message.category = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* svyne.common.PageRequest page = 1; */
        if (message.page)
            PageRequest.internalBinaryWrite(message.page, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* string category = 3; */
        if (message.category !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.category);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.ListEventsRequest
 */
export const ListEventsRequest = new ListEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchEventsRequest$Type extends MessageType<SearchEventsRequest> {
    constructor() {
        super("svyne.event.SearchEventsRequest", [
            { no: 1, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SearchEventsRequest>): SearchEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.query = "";
        if (value !== undefined)
            reflectionMergePartial<SearchEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchEventsRequest): SearchEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string query */ 1:
                    message.query = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string query = 1; */
        if (message.query !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.query);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.SearchEventsRequest
 */
export const SearchEventsRequest = new SearchEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventsResponse$Type extends MessageType<ListEventsResponse> {
    constructor() {
        super("svyne.event.ListEventsResponse", [
            { no: 1, name: "events", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Event },
            { no: 2, name: "meta", kind: "message", T: () => PageMeta }
        ]);
    }
    create(value?: PartialMessage<ListEventsResponse>): ListEventsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.events = [];
        if (value !== undefined)
            reflectionMergePartial<ListEventsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventsResponse): ListEventsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated svyne.event.Event events */ 1:
                    message.events.push(Event.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* svyne.common.PageMeta meta */ 2:
                    message.meta = PageMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated svyne.event.Event events = 1; */
        for (let i = 0; i < message.events.length; i++)
            Event.internalBinaryWrite(message.events[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* svyne.common.PageMeta meta = 2; */
        if (message.meta)
            PageMeta.internalBinaryWrite(message.meta, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.ListEventsResponse
 */
export const ListEventsResponse = new ListEventsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventStats$Type extends MessageType<EventStats> {
    constructor() {
        super("svyne.event.EventStats", [
            { no: 1, name: "events_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "total_bookings", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "tickets_sold", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "revenue_cents", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "checked_in", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<EventStats>): EventStats {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventsId = "";
        message.totalBookings = 0;
        message.ticketsSold = 0;
        message.revenueCents = "0";
        message.checkedIn = 0;
        if (value !== undefined)
            reflectionMergePartial<EventStats>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventStats): EventStats {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string events_id */ 1:
                    message.eventsId = reader.string();
                    break;
                case /* int32 total_bookings */ 2:
                    message.totalBookings = reader.int32();
                    break;
                case /* int32 tickets_sold */ 3:
                    message.ticketsSold = reader.int32();
                    break;
                case /* int64 revenue_cents */ 4:
                    message.revenueCents = reader.int64().toString();
                    break;
                case /* int32 checked_in */ 5:
                    message.checkedIn = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventStats, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string events_id = 1; */
        if (message.eventsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventsId);
        /* int32 total_bookings = 2; */
        if (message.totalBookings !== 0)
            writer.tag(2, WireType.Varint).int32(message.totalBookings);
        /* int32 tickets_sold = 3; */
        if (message.ticketsSold !== 0)
            writer.tag(3, WireType.Varint).int32(message.ticketsSold);
        /* int64 revenue_cents = 4; */
        if (message.revenueCents !== "0")
            writer.tag(4, WireType.Varint).int64(message.revenueCents);
        /* int32 checked_in = 5; */
        if (message.checkedIn !== 0)
            writer.tag(5, WireType.Varint).int32(message.checkedIn);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message svyne.event.EventStats
 */
export const EventStats = new EventStats$Type();
/**
 * @generated ServiceType for protobuf service svyne.event.EventService
 */
export const EventService = new ServiceType("svyne.event.EventService", [
    { name: "CreateEvent", options: {}, I: CreateEventRequest, O: CreateEventResponse },
    { name: "UpdateEvent", options: {}, I: UpdateEventRequest, O: AckResponse },
    { name: "DeleteEvent", options: {}, I: UuidValue, O: AckResponse },
    { name: "GetEvent", options: {}, I: UuidValue, O: Event },
    { name: "GetEventBySlug", options: {}, I: GetEventBySlugRequest, O: Event },
    { name: "ListEvents", options: {}, I: ListEventsRequest, O: ListEventsResponse },
    { name: "SearchEvents", options: {}, I: SearchEventsRequest, O: ListEventsResponse },
    { name: "ChangeEventStatus", options: {}, I: ChangeEventStatusRequest, O: AckResponse },
    { name: "GetEventStats", options: {}, I: UuidValue, O: EventStats },
    { name: "SetEventFeesIncluded", options: {}, I: SetEventFeesIncludedRequest, O: AckResponse },
    { name: "ListScheduleItems", options: {}, I: UuidValue, O: ListScheduleItemsResponse },
    { name: "CreateScheduleItem", options: {}, I: CreateScheduleItemRequest, O: UuidValue },
    { name: "UpdateScheduleItem", options: {}, I: UpdateScheduleItemRequest, O: AckResponse },
    { name: "DeleteScheduleItem", options: {}, I: UuidValue, O: AckResponse },
    { name: "ListEventImages", options: {}, I: ListEventImagesRequest, O: ListEventImagesResponse },
    { name: "AddEventImage", options: {}, I: AddEventImageRequest, O: EventImage },
    { name: "RemoveEventImage", options: {}, I: RemoveEventImageRequest, O: AckResponse },
    { name: "SetPrimaryEventImage", options: {}, I: RemoveEventImageRequest, O: AckResponse },
    { name: "ReorderEventImages", options: {}, I: ReorderEventImagesRequest, O: AckResponse },
    { name: "GetMediaSettings", options: {}, I: Empty, O: MediaSettings }
]);
