/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "fees.proto" (package "ticketspan.fees", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { FeeService } from "./fees";
import type { AssignFeeFormulaRequest } from "./fees";
import type { DeveloperEventsResponse } from "./fees";
import type { AckResponse } from "./common";
import type { FeeFormula } from "./fees";
import type { UuidValue } from "./common";
import type { FeeFormulaInput } from "./fees";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListFeeFormulasResponse } from "./fees";
import type { Empty } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ticketspan.fees.FeeService
 */
export interface IFeeServiceClient {
    /**
     * @generated from protobuf rpc: ListFeeFormulas(ticketspan.common.Empty) returns (ticketspan.fees.ListFeeFormulasResponse);
     */
    listFeeFormulas(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListFeeFormulasResponse>;
    /**
     * @generated from protobuf rpc: CreateFeeFormula(ticketspan.fees.FeeFormulaInput) returns (ticketspan.common.UuidValue);
     */
    createFeeFormula(input: FeeFormulaInput, options?: RpcOptions): UnaryCall<FeeFormulaInput, UuidValue>;
    /**
     * @generated from protobuf rpc: UpdateFeeFormula(ticketspan.fees.FeeFormula) returns (ticketspan.common.AckResponse);
     */
    updateFeeFormula(input: FeeFormula, options?: RpcOptions): UnaryCall<FeeFormula, AckResponse>;
    /**
     * @generated from protobuf rpc: DeleteFeeFormula(ticketspan.common.UuidValue) returns (ticketspan.common.AckResponse);
     */
    deleteFeeFormula(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: ListAllEvents(ticketspan.common.Empty) returns (ticketspan.fees.DeveloperEventsResponse);
     */
    listAllEvents(input: Empty, options?: RpcOptions): UnaryCall<Empty, DeveloperEventsResponse>;
    /**
     * @generated from protobuf rpc: AssignFeeFormula(ticketspan.fees.AssignFeeFormulaRequest) returns (ticketspan.common.AckResponse);
     */
    assignFeeFormula(input: AssignFeeFormulaRequest, options?: RpcOptions): UnaryCall<AssignFeeFormulaRequest, AckResponse>;
}
/**
 * @generated from protobuf service ticketspan.fees.FeeService
 */
export class FeeServiceClient implements IFeeServiceClient, ServiceInfo {
    typeName = FeeService.typeName;
    methods = FeeService.methods;
    options = FeeService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListFeeFormulas(ticketspan.common.Empty) returns (ticketspan.fees.ListFeeFormulasResponse);
     */
    listFeeFormulas(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListFeeFormulasResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ListFeeFormulasResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateFeeFormula(ticketspan.fees.FeeFormulaInput) returns (ticketspan.common.UuidValue);
     */
    createFeeFormula(input: FeeFormulaInput, options?: RpcOptions): UnaryCall<FeeFormulaInput, UuidValue> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<FeeFormulaInput, UuidValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateFeeFormula(ticketspan.fees.FeeFormula) returns (ticketspan.common.AckResponse);
     */
    updateFeeFormula(input: FeeFormula, options?: RpcOptions): UnaryCall<FeeFormula, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<FeeFormula, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteFeeFormula(ticketspan.common.UuidValue) returns (ticketspan.common.AckResponse);
     */
    deleteFeeFormula(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAllEvents(ticketspan.common.Empty) returns (ticketspan.fees.DeveloperEventsResponse);
     */
    listAllEvents(input: Empty, options?: RpcOptions): UnaryCall<Empty, DeveloperEventsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, DeveloperEventsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AssignFeeFormula(ticketspan.fees.AssignFeeFormulaRequest) returns (ticketspan.common.AckResponse);
     */
    assignFeeFormula(input: AssignFeeFormulaRequest, options?: RpcOptions): UnaryCall<AssignFeeFormulaRequest, AckResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<AssignFeeFormulaRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
}
