/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "floorplan.proto" (package "svyne.floorplan", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { FloorPlanService } from "./floorplan";
import type { AckResponse } from "./common";
import type { ApplyTemplateRequest } from "./floorplan";
import type { ListFloorPlanTemplatesResponse } from "./floorplan";
import type { Empty } from "./common";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { UuidValue } from "./common";
import type { SaveAsTemplateRequest } from "./floorplan";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Reusable whole-floor-plan templates (grid + tables + objects). Distinct from
 * per-table table_templates. Layout objects and per-table overrides are saved
 * through TableBookingService.SaveEventLayout.
 *
 * @generated from protobuf service svyne.floorplan.FloorPlanService
 */
export interface IFloorPlanServiceClient {
    /**
     * @generated from protobuf rpc: SaveAsTemplate(svyne.floorplan.SaveAsTemplateRequest) returns (svyne.common.UuidValue);
     */
    saveAsTemplate(input: SaveAsTemplateRequest, options?: RpcOptions): UnaryCall<SaveAsTemplateRequest, UuidValue>;
    /**
     * @generated from protobuf rpc: ListFloorPlanTemplates(svyne.common.Empty) returns (svyne.floorplan.ListFloorPlanTemplatesResponse);
     */
    listFloorPlanTemplates(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListFloorPlanTemplatesResponse>;
    /**
     * @generated from protobuf rpc: ApplyTemplate(svyne.floorplan.ApplyTemplateRequest) returns (svyne.common.AckResponse);
     */
    applyTemplate(input: ApplyTemplateRequest, options?: RpcOptions): UnaryCall<ApplyTemplateRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: DeleteFloorPlanTemplate(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    deleteFloorPlanTemplate(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
}
/**
 * Reusable whole-floor-plan templates (grid + tables + objects). Distinct from
 * per-table table_templates. Layout objects and per-table overrides are saved
 * through TableBookingService.SaveEventLayout.
 *
 * @generated from protobuf service svyne.floorplan.FloorPlanService
 */
export class FloorPlanServiceClient implements IFloorPlanServiceClient, ServiceInfo {
    typeName = FloorPlanService.typeName;
    methods = FloorPlanService.methods;
    options = FloorPlanService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SaveAsTemplate(svyne.floorplan.SaveAsTemplateRequest) returns (svyne.common.UuidValue);
     */
    saveAsTemplate(input: SaveAsTemplateRequest, options?: RpcOptions): UnaryCall<SaveAsTemplateRequest, UuidValue> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SaveAsTemplateRequest, UuidValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListFloorPlanTemplates(svyne.common.Empty) returns (svyne.floorplan.ListFloorPlanTemplatesResponse);
     */
    listFloorPlanTemplates(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListFloorPlanTemplatesResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ListFloorPlanTemplatesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ApplyTemplate(svyne.floorplan.ApplyTemplateRequest) returns (svyne.common.AckResponse);
     */
    applyTemplate(input: ApplyTemplateRequest, options?: RpcOptions): UnaryCall<ApplyTemplateRequest, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ApplyTemplateRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteFloorPlanTemplate(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    deleteFloorPlanTemplate(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
}
