/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "reporting.proto" (package "ticketspan.reporting", syntax proto3)
// tslint:disable
import { TenantTierService } from "./reporting";
import type { SetTenantTaxDefaultRequest } from "./reporting";
import type { SetTenantTaxModeRequest } from "./reporting";
import type { SetTenantAchRequest } from "./reporting";
import type { SetTenantAdvancedReportingRequest } from "./reporting";
import type { AckResponse } from "./common";
import type { SetTenantTierRequest } from "./reporting";
import type { TenantReportingAccessList } from "./reporting";
import type { PageRequest } from "./common";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ReportingService } from "./reporting";
import type { TaxReport } from "./reporting";
import type { SalesByChannelList } from "./reporting";
import type { TicketTypeBreakdownList } from "./reporting";
import type { EventPerformanceList } from "./reporting";
import type { RevenueTimeseries } from "./reporting";
import type { TimeseriesRequest } from "./reporting";
import type { ReportSummary } from "./reporting";
import type { ReportRangeRequest } from "./reporting";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ReportingAccess } from "./reporting";
import type { Empty } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ticketspan.reporting.ReportingService
 */
export interface IReportingServiceClient {
    /**
     * @generated from protobuf rpc: GetReportingAccess(ticketspan.common.Empty) returns (ticketspan.reporting.ReportingAccess);
     */
    getReportingAccess(input: Empty, options?: RpcOptions): UnaryCall<Empty, ReportingAccess>;
    /**
     * @generated from protobuf rpc: GetReportSummary(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.ReportSummary);
     */
    getReportSummary(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, ReportSummary>;
    /**
     * @generated from protobuf rpc: GetRevenueTimeseries(ticketspan.reporting.TimeseriesRequest) returns (ticketspan.reporting.RevenueTimeseries);
     */
    getRevenueTimeseries(input: TimeseriesRequest, options?: RpcOptions): UnaryCall<TimeseriesRequest, RevenueTimeseries>;
    /**
     * @generated from protobuf rpc: GetEventPerformance(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.EventPerformanceList);
     */
    getEventPerformance(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, EventPerformanceList>;
    /**
     * @generated from protobuf rpc: GetTicketTypeBreakdown(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.TicketTypeBreakdownList);
     */
    getTicketTypeBreakdown(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, TicketTypeBreakdownList>;
    /**
     * @generated from protobuf rpc: GetSalesByChannel(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.SalesByChannelList);
     */
    getSalesByChannel(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, SalesByChannelList>;
    /**
     * @generated from protobuf rpc: GetTaxReport(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.TaxReport);
     */
    getTaxReport(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, TaxReport>;
}
/**
 * @generated from protobuf service ticketspan.reporting.ReportingService
 */
export class ReportingServiceClient implements IReportingServiceClient, ServiceInfo {
    typeName = ReportingService.typeName;
    methods = ReportingService.methods;
    options = ReportingService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetReportingAccess(ticketspan.common.Empty) returns (ticketspan.reporting.ReportingAccess);
     */
    getReportingAccess(input: Empty, options?: RpcOptions): UnaryCall<Empty, ReportingAccess> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ReportingAccess>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetReportSummary(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.ReportSummary);
     */
    getReportSummary(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, ReportSummary> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReportRangeRequest, ReportSummary>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRevenueTimeseries(ticketspan.reporting.TimeseriesRequest) returns (ticketspan.reporting.RevenueTimeseries);
     */
    getRevenueTimeseries(input: TimeseriesRequest, options?: RpcOptions): UnaryCall<TimeseriesRequest, RevenueTimeseries> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TimeseriesRequest, RevenueTimeseries>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetEventPerformance(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.EventPerformanceList);
     */
    getEventPerformance(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, EventPerformanceList> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReportRangeRequest, EventPerformanceList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTicketTypeBreakdown(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.TicketTypeBreakdownList);
     */
    getTicketTypeBreakdown(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, TicketTypeBreakdownList> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReportRangeRequest, TicketTypeBreakdownList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSalesByChannel(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.SalesByChannelList);
     */
    getSalesByChannel(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, SalesByChannelList> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReportRangeRequest, SalesByChannelList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTaxReport(ticketspan.reporting.ReportRangeRequest) returns (ticketspan.reporting.TaxReport);
     */
    getTaxReport(input: ReportRangeRequest, options?: RpcOptions): UnaryCall<ReportRangeRequest, TaxReport> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReportRangeRequest, TaxReport>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service ticketspan.reporting.TenantTierService
 */
export interface ITenantTierServiceClient {
    /**
     * @generated from protobuf rpc: ListTenantReportingAccess(ticketspan.common.PageRequest) returns (ticketspan.reporting.TenantReportingAccessList);
     */
    listTenantReportingAccess(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, TenantReportingAccessList>;
    /**
     * @generated from protobuf rpc: SetTenantTier(ticketspan.reporting.SetTenantTierRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantTier(input: SetTenantTierRequest, options?: RpcOptions): UnaryCall<SetTenantTierRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: SetTenantAdvancedReporting(ticketspan.reporting.SetTenantAdvancedReportingRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantAdvancedReporting(input: SetTenantAdvancedReportingRequest, options?: RpcOptions): UnaryCall<SetTenantAdvancedReportingRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: SetTenantAch(ticketspan.reporting.SetTenantAchRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantAch(input: SetTenantAchRequest, options?: RpcOptions): UnaryCall<SetTenantAchRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: SetTenantTaxMode(ticketspan.reporting.SetTenantTaxModeRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantTaxMode(input: SetTenantTaxModeRequest, options?: RpcOptions): UnaryCall<SetTenantTaxModeRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: SetTenantTaxDefault(ticketspan.reporting.SetTenantTaxDefaultRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantTaxDefault(input: SetTenantTaxDefaultRequest, options?: RpcOptions): UnaryCall<SetTenantTaxDefaultRequest, AckResponse>;
}
/**
 * @generated from protobuf service ticketspan.reporting.TenantTierService
 */
export class TenantTierServiceClient implements ITenantTierServiceClient, ServiceInfo {
    typeName = TenantTierService.typeName;
    methods = TenantTierService.methods;
    options = TenantTierService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListTenantReportingAccess(ticketspan.common.PageRequest) returns (ticketspan.reporting.TenantReportingAccessList);
     */
    listTenantReportingAccess(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, TenantReportingAccessList> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PageRequest, TenantReportingAccessList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetTenantTier(ticketspan.reporting.SetTenantTierRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantTier(input: SetTenantTierRequest, options?: RpcOptions): UnaryCall<SetTenantTierRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetTenantTierRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetTenantAdvancedReporting(ticketspan.reporting.SetTenantAdvancedReportingRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantAdvancedReporting(input: SetTenantAdvancedReportingRequest, options?: RpcOptions): UnaryCall<SetTenantAdvancedReportingRequest, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetTenantAdvancedReportingRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetTenantAch(ticketspan.reporting.SetTenantAchRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantAch(input: SetTenantAchRequest, options?: RpcOptions): UnaryCall<SetTenantAchRequest, AckResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetTenantAchRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetTenantTaxMode(ticketspan.reporting.SetTenantTaxModeRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantTaxMode(input: SetTenantTaxModeRequest, options?: RpcOptions): UnaryCall<SetTenantTaxModeRequest, AckResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetTenantTaxModeRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetTenantTaxDefault(ticketspan.reporting.SetTenantTaxDefaultRequest) returns (ticketspan.common.AckResponse);
     */
    setTenantTaxDefault(input: SetTenantTaxDefaultRequest, options?: RpcOptions): UnaryCall<SetTenantTaxDefaultRequest, AckResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetTenantTaxDefaultRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
}
