/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "tenant.proto" (package "svyne.tenant", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TenantService } from "./tenant";
import type { SetTenantAchEnabledRequest } from "./tenant";
import type { UpdateTenantStripeProfileRequest } from "./tenant";
import type { TenantStripeProfile } from "./tenant";
import type { TenantStripeStatus } from "./tenant";
import type { ListTenantMembersResponse } from "./tenant";
import type { ListPublicTenantsResponse } from "./tenant";
import type { ListTenantsResponse } from "./tenant";
import type { PageRequest } from "./common";
import type { PublicTenantBranding } from "./tenant";
import type { PublicTenantBrandingRequest } from "./tenant";
import type { UpdateMyTenantBrandingRequest } from "./tenant";
import type { UpdateMyTenantContactRequest } from "./tenant";
import type { Empty } from "./common";
import type { Tenant } from "./tenant";
import type { UuidValue } from "./common";
import type { AckResponse } from "./common";
import type { UpdateTenantRequest } from "./tenant";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateTenantResponse } from "./tenant";
import type { CreateTenantRequest } from "./tenant";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service svyne.tenant.TenantService
 */
export interface ITenantServiceClient {
    /**
     * @generated from protobuf rpc: CreateTenant(svyne.tenant.CreateTenantRequest) returns (svyne.tenant.CreateTenantResponse);
     */
    createTenant(input: CreateTenantRequest, options?: RpcOptions): UnaryCall<CreateTenantRequest, CreateTenantResponse>;
    /**
     * @generated from protobuf rpc: UpdateTenant(svyne.tenant.UpdateTenantRequest) returns (svyne.common.AckResponse);
     */
    updateTenant(input: UpdateTenantRequest, options?: RpcOptions): UnaryCall<UpdateTenantRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: ArchiveTenant(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    archiveTenant(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse>;
    /**
     * @generated from protobuf rpc: GetTenant(svyne.common.UuidValue) returns (svyne.tenant.Tenant);
     */
    getTenant(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Tenant>;
    /**
     * @generated from protobuf rpc: GetMyTenant(svyne.common.Empty) returns (svyne.tenant.Tenant);
     */
    getMyTenant(input: Empty, options?: RpcOptions): UnaryCall<Empty, Tenant>;
    /**
     * @generated from protobuf rpc: UpdateMyTenantContact(svyne.tenant.UpdateMyTenantContactRequest) returns (svyne.common.AckResponse);
     */
    updateMyTenantContact(input: UpdateMyTenantContactRequest, options?: RpcOptions): UnaryCall<UpdateMyTenantContactRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: UpdateMyTenantBranding(svyne.tenant.UpdateMyTenantBrandingRequest) returns (svyne.common.AckResponse);
     */
    updateMyTenantBranding(input: UpdateMyTenantBrandingRequest, options?: RpcOptions): UnaryCall<UpdateMyTenantBrandingRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: GetPublicTenantBranding(svyne.tenant.PublicTenantBrandingRequest) returns (svyne.tenant.PublicTenantBranding);
     */
    getPublicTenantBranding(input: PublicTenantBrandingRequest, options?: RpcOptions): UnaryCall<PublicTenantBrandingRequest, PublicTenantBranding>;
    /**
     * @generated from protobuf rpc: ListTenants(svyne.common.PageRequest) returns (svyne.tenant.ListTenantsResponse);
     */
    listTenants(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, ListTenantsResponse>;
    /**
     * @generated from protobuf rpc: ListPublicTenants(svyne.common.Empty) returns (svyne.tenant.ListPublicTenantsResponse);
     */
    listPublicTenants(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListPublicTenantsResponse>;
    /**
     * @generated from protobuf rpc: ListTenantMembers(svyne.common.UuidValue) returns (svyne.tenant.ListTenantMembersResponse);
     */
    listTenantMembers(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListTenantMembersResponse>;
    /**
     * @generated from protobuf rpc: GetTenantStripeStatus(svyne.common.UuidValue) returns (svyne.tenant.TenantStripeStatus);
     */
    getTenantStripeStatus(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, TenantStripeStatus>;
    /**
     * @generated from protobuf rpc: GetTenantStripeProfile(svyne.common.UuidValue) returns (svyne.tenant.TenantStripeProfile);
     */
    getTenantStripeProfile(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, TenantStripeProfile>;
    /**
     * @generated from protobuf rpc: UpdateTenantStripeProfile(svyne.tenant.UpdateTenantStripeProfileRequest) returns (svyne.common.AckResponse);
     */
    updateTenantStripeProfile(input: UpdateTenantStripeProfileRequest, options?: RpcOptions): UnaryCall<UpdateTenantStripeProfileRequest, AckResponse>;
    /**
     * @generated from protobuf rpc: SetTenantAchEnabled(svyne.tenant.SetTenantAchEnabledRequest) returns (svyne.common.AckResponse);
     */
    setTenantAchEnabled(input: SetTenantAchEnabledRequest, options?: RpcOptions): UnaryCall<SetTenantAchEnabledRequest, AckResponse>;
}
/**
 * @generated from protobuf service svyne.tenant.TenantService
 */
export class TenantServiceClient implements ITenantServiceClient, ServiceInfo {
    typeName = TenantService.typeName;
    methods = TenantService.methods;
    options = TenantService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateTenant(svyne.tenant.CreateTenantRequest) returns (svyne.tenant.CreateTenantResponse);
     */
    createTenant(input: CreateTenantRequest, options?: RpcOptions): UnaryCall<CreateTenantRequest, CreateTenantResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateTenantRequest, CreateTenantResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateTenant(svyne.tenant.UpdateTenantRequest) returns (svyne.common.AckResponse);
     */
    updateTenant(input: UpdateTenantRequest, options?: RpcOptions): UnaryCall<UpdateTenantRequest, AckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateTenantRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ArchiveTenant(svyne.common.UuidValue) returns (svyne.common.AckResponse);
     */
    archiveTenant(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, AckResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTenant(svyne.common.UuidValue) returns (svyne.tenant.Tenant);
     */
    getTenant(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, Tenant> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, Tenant>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMyTenant(svyne.common.Empty) returns (svyne.tenant.Tenant);
     */
    getMyTenant(input: Empty, options?: RpcOptions): UnaryCall<Empty, Tenant> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, Tenant>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateMyTenantContact(svyne.tenant.UpdateMyTenantContactRequest) returns (svyne.common.AckResponse);
     */
    updateMyTenantContact(input: UpdateMyTenantContactRequest, options?: RpcOptions): UnaryCall<UpdateMyTenantContactRequest, AckResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateMyTenantContactRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateMyTenantBranding(svyne.tenant.UpdateMyTenantBrandingRequest) returns (svyne.common.AckResponse);
     */
    updateMyTenantBranding(input: UpdateMyTenantBrandingRequest, options?: RpcOptions): UnaryCall<UpdateMyTenantBrandingRequest, AckResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateMyTenantBrandingRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPublicTenantBranding(svyne.tenant.PublicTenantBrandingRequest) returns (svyne.tenant.PublicTenantBranding);
     */
    getPublicTenantBranding(input: PublicTenantBrandingRequest, options?: RpcOptions): UnaryCall<PublicTenantBrandingRequest, PublicTenantBranding> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<PublicTenantBrandingRequest, PublicTenantBranding>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTenants(svyne.common.PageRequest) returns (svyne.tenant.ListTenantsResponse);
     */
    listTenants(input: PageRequest, options?: RpcOptions): UnaryCall<PageRequest, ListTenantsResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<PageRequest, ListTenantsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPublicTenants(svyne.common.Empty) returns (svyne.tenant.ListPublicTenantsResponse);
     */
    listPublicTenants(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListPublicTenantsResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ListPublicTenantsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTenantMembers(svyne.common.UuidValue) returns (svyne.tenant.ListTenantMembersResponse);
     */
    listTenantMembers(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, ListTenantMembersResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, ListTenantMembersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTenantStripeStatus(svyne.common.UuidValue) returns (svyne.tenant.TenantStripeStatus);
     */
    getTenantStripeStatus(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, TenantStripeStatus> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, TenantStripeStatus>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTenantStripeProfile(svyne.common.UuidValue) returns (svyne.tenant.TenantStripeProfile);
     */
    getTenantStripeProfile(input: UuidValue, options?: RpcOptions): UnaryCall<UuidValue, TenantStripeProfile> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<UuidValue, TenantStripeProfile>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateTenantStripeProfile(svyne.tenant.UpdateTenantStripeProfileRequest) returns (svyne.common.AckResponse);
     */
    updateTenantStripeProfile(input: UpdateTenantStripeProfileRequest, options?: RpcOptions): UnaryCall<UpdateTenantStripeProfileRequest, AckResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateTenantStripeProfileRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetTenantAchEnabled(svyne.tenant.SetTenantAchEnabledRequest) returns (svyne.common.AckResponse);
     */
    setTenantAchEnabled(input: SetTenantAchEnabledRequest, options?: RpcOptions): UnaryCall<SetTenantAchEnabledRequest, AckResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetTenantAchEnabledRequest, AckResponse>("unary", this._transport, method, opt, input);
    }
}
