/* eslint-disable */
// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_speed,eslint_disable
// @generated from protobuf file "tenant.proto" (package "entryvine.tenant", syntax proto3)
// tslint:disable
import { PageRequest } from "./common";
import { Empty } from "./common";
import { UuidValue } from "./common";
import { AckResponse } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PageMeta } from "./common";
/**
 * @generated from protobuf message entryvine.tenant.TenantStripeProfile
 */
export interface TenantStripeProfile {
    /**
     * @generated from protobuf field: bool has_account = 1;
     */
    hasAccount: boolean;
    /**
     * @generated from protobuf field: string business_type = 2;
     */
    businessType: string;
    /**
     * @generated from protobuf field: string business_name = 3;
     */
    businessName: string;
    /**
     * @generated from protobuf field: string business_url = 4;
     */
    businessUrl: string;
    /**
     * @generated from protobuf field: string product_description = 5;
     */
    productDescription: string;
    /**
     * @generated from protobuf field: string mcc = 6;
     */
    mcc: string;
    /**
     * @generated from protobuf field: string support_email = 7;
     */
    supportEmail: string;
}
/**
 * @generated from protobuf message entryvine.tenant.UpdateTenantStripeProfileRequest
 */
export interface UpdateTenantStripeProfileRequest {
    /**
     * @generated from protobuf field: string tenants_id = 1;
     */
    tenantsId: string;
    /**
     * @generated from protobuf field: string business_type = 2;
     */
    businessType: string;
    /**
     * @generated from protobuf field: string business_name = 3;
     */
    businessName: string;
    /**
     * @generated from protobuf field: string business_url = 4;
     */
    businessUrl: string;
    /**
     * @generated from protobuf field: string product_description = 5;
     */
    productDescription: string;
    /**
     * @generated from protobuf field: string mcc = 6;
     */
    mcc: string;
    /**
     * @generated from protobuf field: string support_email = 7;
     */
    supportEmail: string;
}
/**
 * @generated from protobuf message entryvine.tenant.Tenant
 */
export interface Tenant {
    /**
     * @generated from protobuf field: string tenants_id = 1;
     */
    tenantsId: string;
    /**
     * @generated from protobuf field: string slug = 2;
     */
    slug: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: string legal_name = 4;
     */
    legalName: string;
    /**
     * @generated from protobuf field: string country_code = 5;
     */
    countryCode: string;
    /**
     * @generated from protobuf field: int32 member_count = 6;
     */
    memberCount: number;
    /**
     * @generated from protobuf field: int32 event_count = 7;
     */
    eventCount: number;
    /**
     * @generated from protobuf field: int64 total_revenue_cents = 8;
     */
    totalRevenueCents: string;
    /**
     * @generated from protobuf field: bool archived = 9;
     */
    archived: boolean;
    /**
     * Tenant default service-fee formula. Auto-applied to every new event price;
     * empty = no default set. Developer-only (set via PricingService).
     *
     * @generated from protobuf field: string default_fee_formulas_id = 10;
     */
    defaultFeeFormulasId: string;
    /**
     * @generated from protobuf field: string phone = 11;
     */
    phone: string;
    /**
     * @generated from protobuf field: string address_line1 = 12;
     */
    addressLine1: string;
    /**
     * @generated from protobuf field: string address_line2 = 13;
     */
    addressLine2: string;
    /**
     * @generated from protobuf field: string city = 14;
     */
    city: string;
    /**
     * @generated from protobuf field: string state = 15;
     */
    state: string;
    /**
     * @generated from protobuf field: string zip = 16;
     */
    zip: string;
    /**
     * @generated from protobuf field: string logo_url = 17;
     */
    logoUrl: string;
    /**
     * @generated from protobuf field: string brand_primary = 18;
     */
    brandPrimary: string;
    /**
     * @generated from protobuf field: string brand_secondary = 19;
     */
    brandSecondary: string;
    /**
     * @generated from protobuf field: string brand_accent = 20;
     */
    brandAccent: string;
    /**
     * @generated from protobuf field: string brand_background = 21;
     */
    brandBackground: string;
    /**
     * @generated from protobuf field: string brand_text = 22;
     */
    brandText: string;
    /**
     * @generated from protobuf field: string brand_button = 23;
     */
    brandButton: string;
    /**
     * @generated from protobuf field: string brand_highlight = 24;
     */
    brandHighlight: string;
    /**
     * Whether this tenant may offer ACH bank-transfer payments (developer-managed).
     *
     * @generated from protobuf field: bool ach_enabled = 25;
     */
    achEnabled: boolean;
    /**
     * JSON object of advanced theme-token overrides, e.g. {"stage":"#101010"}.
     *
     * @generated from protobuf field: string brand_tokens_json = 26;
     */
    brandTokensJson: string;
    /**
     * ACH fee formula assigned to this tenant; empty = none (developer-managed).
     *
     * @generated from protobuf field: string ach_fee_formulas_id = 27;
     */
    achFeeFormulasId: string;
}
/**
 * @generated from protobuf message entryvine.tenant.UpdateMyTenantBrandingRequest
 */
export interface UpdateMyTenantBrandingRequest {
    /**
     * @generated from protobuf field: string logo_images_id = 1;
     */
    logoImagesId: string;
    /**
     * @generated from protobuf field: string brand_primary = 2;
     */
    brandPrimary: string;
    /**
     * @generated from protobuf field: string brand_secondary = 3;
     */
    brandSecondary: string;
    /**
     * @generated from protobuf field: string brand_accent = 4;
     */
    brandAccent: string;
    /**
     * @generated from protobuf field: string brand_background = 5;
     */
    brandBackground: string;
    /**
     * @generated from protobuf field: string brand_text = 6;
     */
    brandText: string;
    /**
     * @generated from protobuf field: string brand_button = 7;
     */
    brandButton: string;
    /**
     * @generated from protobuf field: string brand_highlight = 8;
     */
    brandHighlight: string;
    /**
     * @generated from protobuf field: string brand_tokens_json = 9;
     */
    brandTokensJson: string;
}
/**
 * @generated from protobuf message entryvine.tenant.PublicTenantBrandingRequest
 */
export interface PublicTenantBrandingRequest {
    /**
     * @generated from protobuf field: string slug = 1;
     */
    slug: string;
}
/**
 * @generated from protobuf message entryvine.tenant.PublicTenantBranding
 */
export interface PublicTenantBranding {
    /**
     * @generated from protobuf field: string slug = 1;
     */
    slug: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string logo_url = 3;
     */
    logoUrl: string;
    /**
     * @generated from protobuf field: string brand_primary = 4;
     */
    brandPrimary: string;
    /**
     * @generated from protobuf field: string brand_secondary = 5;
     */
    brandSecondary: string;
    /**
     * @generated from protobuf field: string brand_accent = 6;
     */
    brandAccent: string;
    /**
     * @generated from protobuf field: string brand_background = 7;
     */
    brandBackground: string;
    /**
     * @generated from protobuf field: string brand_text = 8;
     */
    brandText: string;
    /**
     * @generated from protobuf field: string brand_button = 9;
     */
    brandButton: string;
    /**
     * @generated from protobuf field: string brand_highlight = 10;
     */
    brandHighlight: string;
    /**
     * @generated from protobuf field: string brand_tokens_json = 11;
     */
    brandTokensJson: string;
}
/**
 * @generated from protobuf message entryvine.tenant.UpdateMyTenantContactRequest
 */
export interface UpdateMyTenantContactRequest {
    /**
     * @generated from protobuf field: string phone = 1;
     */
    phone: string;
    /**
     * @generated from protobuf field: string address_line1 = 2;
     */
    addressLine1: string;
    /**
     * @generated from protobuf field: string address_line2 = 3;
     */
    addressLine2: string;
    /**
     * @generated from protobuf field: string city = 4;
     */
    city: string;
    /**
     * @generated from protobuf field: string state = 5;
     */
    state: string;
    /**
     * @generated from protobuf field: string zip = 6;
     */
    zip: string;
}
/**
 * @generated from protobuf message entryvine.tenant.CreateTenantRequest
 */
export interface CreateTenantRequest {
    /**
     * @generated from protobuf field: string slug = 1;
     */
    slug: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string admin_email = 3;
     */
    adminEmail: string;
    /**
     * @generated from protobuf field: string admin_first_name = 4;
     */
    adminFirstName: string;
    /**
     * @generated from protobuf field: string admin_last_name = 5;
     */
    adminLastName: string;
    /**
     * @generated from protobuf field: string legal_name = 6;
     */
    legalName: string;
    /**
     * @generated from protobuf field: string country_code = 7;
     */
    countryCode: string;
    /**
     * Stripe Connect onboarding prefill (all optional). Used to pre-create the
     * connected account so the Express onboarding form is pre-filled.
     *
     * @generated from protobuf field: string business_type = 8;
     */
    businessType: string; // "individual" | "company"
    /**
     * @generated from protobuf field: string business_url = 9;
     */
    businessUrl: string;
    /**
     * @generated from protobuf field: string product_description = 10;
     */
    productDescription: string;
    /**
     * @generated from protobuf field: string mcc = 11;
     */
    mcc: string; // 4-digit Stripe merchant category code
    /**
     * @generated from protobuf field: string support_email = 12;
     */
    supportEmail: string;
}
/**
 * @generated from protobuf message entryvine.tenant.CreateTenantResponse
 */
export interface CreateTenantResponse {
    /**
     * @generated from protobuf field: string tenants_id = 1;
     */
    tenantsId: string;
    /**
     * @generated from protobuf field: string admin_users_id = 2;
     */
    adminUsersId: string;
    /**
     * @generated from protobuf field: string setup_url = 3;
     */
    setupUrl: string;
}
/**
 * @generated from protobuf message entryvine.tenant.UpdateTenantRequest
 */
export interface UpdateTenantRequest {
    /**
     * @generated from protobuf field: string tenants_id = 1;
     */
    tenantsId: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string legal_name = 3;
     */
    legalName: string;
    /**
     * @generated from protobuf field: string country_code = 4;
     */
    countryCode: string;
}
/**
 * @generated from protobuf message entryvine.tenant.ListTenantsResponse
 */
export interface ListTenantsResponse {
    /**
     * @generated from protobuf field: repeated entryvine.tenant.Tenant tenants = 1;
     */
    tenants: Tenant[];
    /**
     * @generated from protobuf field: entryvine.common.PageMeta meta = 2;
     */
    meta?: PageMeta;
}
/**
 * @generated from protobuf message entryvine.tenant.PublicTenant
 */
export interface PublicTenant {
    /**
     * @generated from protobuf field: string slug = 1;
     */
    slug: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
}
/**
 * @generated from protobuf message entryvine.tenant.ListPublicTenantsResponse
 */
export interface ListPublicTenantsResponse {
    /**
     * @generated from protobuf field: repeated entryvine.tenant.PublicTenant tenants = 1;
     */
    tenants: PublicTenant[];
}
/**
 * @generated from protobuf message entryvine.tenant.TenantMember
 */
export interface TenantMember {
    /**
     * @generated from protobuf field: string users_id = 1;
     */
    usersId: string;
    /**
     * @generated from protobuf field: string email = 2;
     */
    email: string;
    /**
     * @generated from protobuf field: int32 role = 3;
     */
    role: number;
    /**
     * @generated from protobuf field: string display_name = 4;
     */
    displayName: string;
}
/**
 * @generated from protobuf message entryvine.tenant.ListTenantMembersResponse
 */
export interface ListTenantMembersResponse {
    /**
     * @generated from protobuf field: repeated entryvine.tenant.TenantMember members = 1;
     */
    members: TenantMember[];
}
/**
 * @generated from protobuf message entryvine.tenant.TenantStripeStatus
 */
export interface TenantStripeStatus {
    /**
     * @generated from protobuf field: string tenants_id = 1;
     */
    tenantsId: string;
    /**
     * @generated from protobuf field: string stripe_connected_account_id = 2;
     */
    stripeConnectedAccountId: string;
    /**
     * @generated from protobuf field: bool charges_enabled = 3;
     */
    chargesEnabled: boolean;
    /**
     * @generated from protobuf field: bool payouts_enabled = 4;
     */
    payoutsEnabled: boolean;
    /**
     * @generated from protobuf field: bool details_submitted = 5;
     */
    detailsSubmitted: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class TenantStripeProfile$Type extends MessageType<TenantStripeProfile> {
    constructor() {
        super("entryvine.tenant.TenantStripeProfile", [
            { no: 1, name: "has_account", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "business_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "business_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "business_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "product_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "mcc", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "support_email", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TenantStripeProfile>): TenantStripeProfile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hasAccount = false;
        message.businessType = "";
        message.businessName = "";
        message.businessUrl = "";
        message.productDescription = "";
        message.mcc = "";
        message.supportEmail = "";
        if (value !== undefined)
            reflectionMergePartial<TenantStripeProfile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TenantStripeProfile): TenantStripeProfile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool has_account */ 1:
                    message.hasAccount = reader.bool();
                    break;
                case /* string business_type */ 2:
                    message.businessType = reader.string();
                    break;
                case /* string business_name */ 3:
                    message.businessName = reader.string();
                    break;
                case /* string business_url */ 4:
                    message.businessUrl = reader.string();
                    break;
                case /* string product_description */ 5:
                    message.productDescription = reader.string();
                    break;
                case /* string mcc */ 6:
                    message.mcc = reader.string();
                    break;
                case /* string support_email */ 7:
                    message.supportEmail = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TenantStripeProfile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool has_account = 1; */
        if (message.hasAccount !== false)
            writer.tag(1, WireType.Varint).bool(message.hasAccount);
        /* string business_type = 2; */
        if (message.businessType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.businessType);
        /* string business_name = 3; */
        if (message.businessName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.businessName);
        /* string business_url = 4; */
        if (message.businessUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.businessUrl);
        /* string product_description = 5; */
        if (message.productDescription !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.productDescription);
        /* string mcc = 6; */
        if (message.mcc !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.mcc);
        /* string support_email = 7; */
        if (message.supportEmail !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.supportEmail);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.TenantStripeProfile
 */
export const TenantStripeProfile = new TenantStripeProfile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTenantStripeProfileRequest$Type extends MessageType<UpdateTenantStripeProfileRequest> {
    constructor() {
        super("entryvine.tenant.UpdateTenantStripeProfileRequest", [
            { no: 1, name: "tenants_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "business_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "business_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "business_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "product_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "mcc", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "support_email", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateTenantStripeProfileRequest>): UpdateTenantStripeProfileRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tenantsId = "";
        message.businessType = "";
        message.businessName = "";
        message.businessUrl = "";
        message.productDescription = "";
        message.mcc = "";
        message.supportEmail = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateTenantStripeProfileRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTenantStripeProfileRequest): UpdateTenantStripeProfileRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tenants_id */ 1:
                    message.tenantsId = reader.string();
                    break;
                case /* string business_type */ 2:
                    message.businessType = reader.string();
                    break;
                case /* string business_name */ 3:
                    message.businessName = reader.string();
                    break;
                case /* string business_url */ 4:
                    message.businessUrl = reader.string();
                    break;
                case /* string product_description */ 5:
                    message.productDescription = reader.string();
                    break;
                case /* string mcc */ 6:
                    message.mcc = reader.string();
                    break;
                case /* string support_email */ 7:
                    message.supportEmail = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTenantStripeProfileRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tenants_id = 1; */
        if (message.tenantsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tenantsId);
        /* string business_type = 2; */
        if (message.businessType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.businessType);
        /* string business_name = 3; */
        if (message.businessName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.businessName);
        /* string business_url = 4; */
        if (message.businessUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.businessUrl);
        /* string product_description = 5; */
        if (message.productDescription !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.productDescription);
        /* string mcc = 6; */
        if (message.mcc !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.mcc);
        /* string support_email = 7; */
        if (message.supportEmail !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.supportEmail);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.UpdateTenantStripeProfileRequest
 */
export const UpdateTenantStripeProfileRequest = new UpdateTenantStripeProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Tenant$Type extends MessageType<Tenant> {
    constructor() {
        super("entryvine.tenant.Tenant", [
            { no: 1, name: "tenants_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "legal_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "country_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "member_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "event_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "total_revenue_cents", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "archived", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "default_fee_formulas_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "address_line1", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "address_line2", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "city", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "zip", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "logo_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "brand_primary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "brand_secondary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "brand_accent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 21, name: "brand_background", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "brand_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "brand_button", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 24, name: "brand_highlight", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 25, name: "ach_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 26, name: "brand_tokens_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 27, name: "ach_fee_formulas_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Tenant>): Tenant {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tenantsId = "";
        message.slug = "";
        message.name = "";
        message.legalName = "";
        message.countryCode = "";
        message.memberCount = 0;
        message.eventCount = 0;
        message.totalRevenueCents = "0";
        message.archived = false;
        message.defaultFeeFormulasId = "";
        message.phone = "";
        message.addressLine1 = "";
        message.addressLine2 = "";
        message.city = "";
        message.state = "";
        message.zip = "";
        message.logoUrl = "";
        message.brandPrimary = "";
        message.brandSecondary = "";
        message.brandAccent = "";
        message.brandBackground = "";
        message.brandText = "";
        message.brandButton = "";
        message.brandHighlight = "";
        message.achEnabled = false;
        message.brandTokensJson = "";
        message.achFeeFormulasId = "";
        if (value !== undefined)
            reflectionMergePartial<Tenant>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Tenant): Tenant {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tenants_id */ 1:
                    message.tenantsId = reader.string();
                    break;
                case /* string slug */ 2:
                    message.slug = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string legal_name */ 4:
                    message.legalName = reader.string();
                    break;
                case /* string country_code */ 5:
                    message.countryCode = reader.string();
                    break;
                case /* int32 member_count */ 6:
                    message.memberCount = reader.int32();
                    break;
                case /* int32 event_count */ 7:
                    message.eventCount = reader.int32();
                    break;
                case /* int64 total_revenue_cents */ 8:
                    message.totalRevenueCents = reader.int64().toString();
                    break;
                case /* bool archived */ 9:
                    message.archived = reader.bool();
                    break;
                case /* string default_fee_formulas_id */ 10:
                    message.defaultFeeFormulasId = reader.string();
                    break;
                case /* string phone */ 11:
                    message.phone = reader.string();
                    break;
                case /* string address_line1 */ 12:
                    message.addressLine1 = reader.string();
                    break;
                case /* string address_line2 */ 13:
                    message.addressLine2 = reader.string();
                    break;
                case /* string city */ 14:
                    message.city = reader.string();
                    break;
                case /* string state */ 15:
                    message.state = reader.string();
                    break;
                case /* string zip */ 16:
                    message.zip = reader.string();
                    break;
                case /* string logo_url */ 17:
                    message.logoUrl = reader.string();
                    break;
                case /* string brand_primary */ 18:
                    message.brandPrimary = reader.string();
                    break;
                case /* string brand_secondary */ 19:
                    message.brandSecondary = reader.string();
                    break;
                case /* string brand_accent */ 20:
                    message.brandAccent = reader.string();
                    break;
                case /* string brand_background */ 21:
                    message.brandBackground = reader.string();
                    break;
                case /* string brand_text */ 22:
                    message.brandText = reader.string();
                    break;
                case /* string brand_button */ 23:
                    message.brandButton = reader.string();
                    break;
                case /* string brand_highlight */ 24:
                    message.brandHighlight = reader.string();
                    break;
                case /* bool ach_enabled */ 25:
                    message.achEnabled = reader.bool();
                    break;
                case /* string brand_tokens_json */ 26:
                    message.brandTokensJson = reader.string();
                    break;
                case /* string ach_fee_formulas_id */ 27:
                    message.achFeeFormulasId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Tenant, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tenants_id = 1; */
        if (message.tenantsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tenantsId);
        /* string slug = 2; */
        if (message.slug !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.slug);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string legal_name = 4; */
        if (message.legalName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.legalName);
        /* string country_code = 5; */
        if (message.countryCode !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.countryCode);
        /* int32 member_count = 6; */
        if (message.memberCount !== 0)
            writer.tag(6, WireType.Varint).int32(message.memberCount);
        /* int32 event_count = 7; */
        if (message.eventCount !== 0)
            writer.tag(7, WireType.Varint).int32(message.eventCount);
        /* int64 total_revenue_cents = 8; */
        if (message.totalRevenueCents !== "0")
            writer.tag(8, WireType.Varint).int64(message.totalRevenueCents);
        /* bool archived = 9; */
        if (message.archived !== false)
            writer.tag(9, WireType.Varint).bool(message.archived);
        /* string default_fee_formulas_id = 10; */
        if (message.defaultFeeFormulasId !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.defaultFeeFormulasId);
        /* string phone = 11; */
        if (message.phone !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.phone);
        /* string address_line1 = 12; */
        if (message.addressLine1 !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.addressLine1);
        /* string address_line2 = 13; */
        if (message.addressLine2 !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.addressLine2);
        /* string city = 14; */
        if (message.city !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.city);
        /* string state = 15; */
        if (message.state !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.state);
        /* string zip = 16; */
        if (message.zip !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.zip);
        /* string logo_url = 17; */
        if (message.logoUrl !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.logoUrl);
        /* string brand_primary = 18; */
        if (message.brandPrimary !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.brandPrimary);
        /* string brand_secondary = 19; */
        if (message.brandSecondary !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.brandSecondary);
        /* string brand_accent = 20; */
        if (message.brandAccent !== "")
            writer.tag(20, WireType.LengthDelimited).string(message.brandAccent);
        /* string brand_background = 21; */
        if (message.brandBackground !== "")
            writer.tag(21, WireType.LengthDelimited).string(message.brandBackground);
        /* string brand_text = 22; */
        if (message.brandText !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.brandText);
        /* string brand_button = 23; */
        if (message.brandButton !== "")
            writer.tag(23, WireType.LengthDelimited).string(message.brandButton);
        /* string brand_highlight = 24; */
        if (message.brandHighlight !== "")
            writer.tag(24, WireType.LengthDelimited).string(message.brandHighlight);
        /* bool ach_enabled = 25; */
        if (message.achEnabled !== false)
            writer.tag(25, WireType.Varint).bool(message.achEnabled);
        /* string brand_tokens_json = 26; */
        if (message.brandTokensJson !== "")
            writer.tag(26, WireType.LengthDelimited).string(message.brandTokensJson);
        /* string ach_fee_formulas_id = 27; */
        if (message.achFeeFormulasId !== "")
            writer.tag(27, WireType.LengthDelimited).string(message.achFeeFormulasId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.Tenant
 */
export const Tenant = new Tenant$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateMyTenantBrandingRequest$Type extends MessageType<UpdateMyTenantBrandingRequest> {
    constructor() {
        super("entryvine.tenant.UpdateMyTenantBrandingRequest", [
            { no: 1, name: "logo_images_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "brand_primary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "brand_secondary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "brand_accent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "brand_background", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "brand_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "brand_button", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "brand_highlight", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "brand_tokens_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateMyTenantBrandingRequest>): UpdateMyTenantBrandingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.logoImagesId = "";
        message.brandPrimary = "";
        message.brandSecondary = "";
        message.brandAccent = "";
        message.brandBackground = "";
        message.brandText = "";
        message.brandButton = "";
        message.brandHighlight = "";
        message.brandTokensJson = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateMyTenantBrandingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateMyTenantBrandingRequest): UpdateMyTenantBrandingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string logo_images_id */ 1:
                    message.logoImagesId = reader.string();
                    break;
                case /* string brand_primary */ 2:
                    message.brandPrimary = reader.string();
                    break;
                case /* string brand_secondary */ 3:
                    message.brandSecondary = reader.string();
                    break;
                case /* string brand_accent */ 4:
                    message.brandAccent = reader.string();
                    break;
                case /* string brand_background */ 5:
                    message.brandBackground = reader.string();
                    break;
                case /* string brand_text */ 6:
                    message.brandText = reader.string();
                    break;
                case /* string brand_button */ 7:
                    message.brandButton = reader.string();
                    break;
                case /* string brand_highlight */ 8:
                    message.brandHighlight = reader.string();
                    break;
                case /* string brand_tokens_json */ 9:
                    message.brandTokensJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateMyTenantBrandingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string logo_images_id = 1; */
        if (message.logoImagesId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.logoImagesId);
        /* string brand_primary = 2; */
        if (message.brandPrimary !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.brandPrimary);
        /* string brand_secondary = 3; */
        if (message.brandSecondary !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.brandSecondary);
        /* string brand_accent = 4; */
        if (message.brandAccent !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.brandAccent);
        /* string brand_background = 5; */
        if (message.brandBackground !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.brandBackground);
        /* string brand_text = 6; */
        if (message.brandText !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.brandText);
        /* string brand_button = 7; */
        if (message.brandButton !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.brandButton);
        /* string brand_highlight = 8; */
        if (message.brandHighlight !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.brandHighlight);
        /* string brand_tokens_json = 9; */
        if (message.brandTokensJson !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.brandTokensJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.UpdateMyTenantBrandingRequest
 */
export const UpdateMyTenantBrandingRequest = new UpdateMyTenantBrandingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PublicTenantBrandingRequest$Type extends MessageType<PublicTenantBrandingRequest> {
    constructor() {
        super("entryvine.tenant.PublicTenantBrandingRequest", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PublicTenantBrandingRequest>): PublicTenantBrandingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        if (value !== undefined)
            reflectionMergePartial<PublicTenantBrandingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PublicTenantBrandingRequest): PublicTenantBrandingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PublicTenantBrandingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.PublicTenantBrandingRequest
 */
export const PublicTenantBrandingRequest = new PublicTenantBrandingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PublicTenantBranding$Type extends MessageType<PublicTenantBranding> {
    constructor() {
        super("entryvine.tenant.PublicTenantBranding", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "logo_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "brand_primary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "brand_secondary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "brand_accent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "brand_background", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "brand_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "brand_button", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "brand_highlight", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "brand_tokens_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PublicTenantBranding>): PublicTenantBranding {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        message.name = "";
        message.logoUrl = "";
        message.brandPrimary = "";
        message.brandSecondary = "";
        message.brandAccent = "";
        message.brandBackground = "";
        message.brandText = "";
        message.brandButton = "";
        message.brandHighlight = "";
        message.brandTokensJson = "";
        if (value !== undefined)
            reflectionMergePartial<PublicTenantBranding>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PublicTenantBranding): PublicTenantBranding {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string logo_url */ 3:
                    message.logoUrl = reader.string();
                    break;
                case /* string brand_primary */ 4:
                    message.brandPrimary = reader.string();
                    break;
                case /* string brand_secondary */ 5:
                    message.brandSecondary = reader.string();
                    break;
                case /* string brand_accent */ 6:
                    message.brandAccent = reader.string();
                    break;
                case /* string brand_background */ 7:
                    message.brandBackground = reader.string();
                    break;
                case /* string brand_text */ 8:
                    message.brandText = reader.string();
                    break;
                case /* string brand_button */ 9:
                    message.brandButton = reader.string();
                    break;
                case /* string brand_highlight */ 10:
                    message.brandHighlight = reader.string();
                    break;
                case /* string brand_tokens_json */ 11:
                    message.brandTokensJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PublicTenantBranding, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string logo_url = 3; */
        if (message.logoUrl !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.logoUrl);
        /* string brand_primary = 4; */
        if (message.brandPrimary !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.brandPrimary);
        /* string brand_secondary = 5; */
        if (message.brandSecondary !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.brandSecondary);
        /* string brand_accent = 6; */
        if (message.brandAccent !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.brandAccent);
        /* string brand_background = 7; */
        if (message.brandBackground !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.brandBackground);
        /* string brand_text = 8; */
        if (message.brandText !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.brandText);
        /* string brand_button = 9; */
        if (message.brandButton !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.brandButton);
        /* string brand_highlight = 10; */
        if (message.brandHighlight !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.brandHighlight);
        /* string brand_tokens_json = 11; */
        if (message.brandTokensJson !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.brandTokensJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.PublicTenantBranding
 */
export const PublicTenantBranding = new PublicTenantBranding$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateMyTenantContactRequest$Type extends MessageType<UpdateMyTenantContactRequest> {
    constructor() {
        super("entryvine.tenant.UpdateMyTenantContactRequest", [
            { no: 1, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "address_line1", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "address_line2", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "city", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "zip", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateMyTenantContactRequest>): UpdateMyTenantContactRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.phone = "";
        message.addressLine1 = "";
        message.addressLine2 = "";
        message.city = "";
        message.state = "";
        message.zip = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateMyTenantContactRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateMyTenantContactRequest): UpdateMyTenantContactRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string phone */ 1:
                    message.phone = reader.string();
                    break;
                case /* string address_line1 */ 2:
                    message.addressLine1 = reader.string();
                    break;
                case /* string address_line2 */ 3:
                    message.addressLine2 = reader.string();
                    break;
                case /* string city */ 4:
                    message.city = reader.string();
                    break;
                case /* string state */ 5:
                    message.state = reader.string();
                    break;
                case /* string zip */ 6:
                    message.zip = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateMyTenantContactRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string phone = 1; */
        if (message.phone !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.phone);
        /* string address_line1 = 2; */
        if (message.addressLine1 !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.addressLine1);
        /* string address_line2 = 3; */
        if (message.addressLine2 !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.addressLine2);
        /* string city = 4; */
        if (message.city !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.city);
        /* string state = 5; */
        if (message.state !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.state);
        /* string zip = 6; */
        if (message.zip !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.zip);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.UpdateMyTenantContactRequest
 */
export const UpdateMyTenantContactRequest = new UpdateMyTenantContactRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTenantRequest$Type extends MessageType<CreateTenantRequest> {
    constructor() {
        super("entryvine.tenant.CreateTenantRequest", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "admin_email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "admin_first_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "admin_last_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "legal_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "country_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "business_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "business_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "product_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "mcc", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "support_email", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateTenantRequest>): CreateTenantRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        message.name = "";
        message.adminEmail = "";
        message.adminFirstName = "";
        message.adminLastName = "";
        message.legalName = "";
        message.countryCode = "";
        message.businessType = "";
        message.businessUrl = "";
        message.productDescription = "";
        message.mcc = "";
        message.supportEmail = "";
        if (value !== undefined)
            reflectionMergePartial<CreateTenantRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTenantRequest): CreateTenantRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string admin_email */ 3:
                    message.adminEmail = reader.string();
                    break;
                case /* string admin_first_name */ 4:
                    message.adminFirstName = reader.string();
                    break;
                case /* string admin_last_name */ 5:
                    message.adminLastName = reader.string();
                    break;
                case /* string legal_name */ 6:
                    message.legalName = reader.string();
                    break;
                case /* string country_code */ 7:
                    message.countryCode = reader.string();
                    break;
                case /* string business_type */ 8:
                    message.businessType = reader.string();
                    break;
                case /* string business_url */ 9:
                    message.businessUrl = reader.string();
                    break;
                case /* string product_description */ 10:
                    message.productDescription = reader.string();
                    break;
                case /* string mcc */ 11:
                    message.mcc = reader.string();
                    break;
                case /* string support_email */ 12:
                    message.supportEmail = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTenantRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string admin_email = 3; */
        if (message.adminEmail !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.adminEmail);
        /* string admin_first_name = 4; */
        if (message.adminFirstName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.adminFirstName);
        /* string admin_last_name = 5; */
        if (message.adminLastName !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.adminLastName);
        /* string legal_name = 6; */
        if (message.legalName !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.legalName);
        /* string country_code = 7; */
        if (message.countryCode !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.countryCode);
        /* string business_type = 8; */
        if (message.businessType !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.businessType);
        /* string business_url = 9; */
        if (message.businessUrl !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.businessUrl);
        /* string product_description = 10; */
        if (message.productDescription !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.productDescription);
        /* string mcc = 11; */
        if (message.mcc !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.mcc);
        /* string support_email = 12; */
        if (message.supportEmail !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.supportEmail);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.CreateTenantRequest
 */
export const CreateTenantRequest = new CreateTenantRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTenantResponse$Type extends MessageType<CreateTenantResponse> {
    constructor() {
        super("entryvine.tenant.CreateTenantResponse", [
            { no: 1, name: "tenants_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "admin_users_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "setup_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateTenantResponse>): CreateTenantResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tenantsId = "";
        message.adminUsersId = "";
        message.setupUrl = "";
        if (value !== undefined)
            reflectionMergePartial<CreateTenantResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTenantResponse): CreateTenantResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tenants_id */ 1:
                    message.tenantsId = reader.string();
                    break;
                case /* string admin_users_id */ 2:
                    message.adminUsersId = reader.string();
                    break;
                case /* string setup_url */ 3:
                    message.setupUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTenantResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tenants_id = 1; */
        if (message.tenantsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tenantsId);
        /* string admin_users_id = 2; */
        if (message.adminUsersId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.adminUsersId);
        /* string setup_url = 3; */
        if (message.setupUrl !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.setupUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.CreateTenantResponse
 */
export const CreateTenantResponse = new CreateTenantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTenantRequest$Type extends MessageType<UpdateTenantRequest> {
    constructor() {
        super("entryvine.tenant.UpdateTenantRequest", [
            { no: 1, name: "tenants_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "legal_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "country_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateTenantRequest>): UpdateTenantRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tenantsId = "";
        message.name = "";
        message.legalName = "";
        message.countryCode = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateTenantRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTenantRequest): UpdateTenantRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tenants_id */ 1:
                    message.tenantsId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string legal_name */ 3:
                    message.legalName = reader.string();
                    break;
                case /* string country_code */ 4:
                    message.countryCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTenantRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tenants_id = 1; */
        if (message.tenantsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tenantsId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string legal_name = 3; */
        if (message.legalName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.legalName);
        /* string country_code = 4; */
        if (message.countryCode !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.countryCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.UpdateTenantRequest
 */
export const UpdateTenantRequest = new UpdateTenantRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListTenantsResponse$Type extends MessageType<ListTenantsResponse> {
    constructor() {
        super("entryvine.tenant.ListTenantsResponse", [
            { no: 1, name: "tenants", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Tenant },
            { no: 2, name: "meta", kind: "message", T: () => PageMeta }
        ]);
    }
    create(value?: PartialMessage<ListTenantsResponse>): ListTenantsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tenants = [];
        if (value !== undefined)
            reflectionMergePartial<ListTenantsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListTenantsResponse): ListTenantsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated entryvine.tenant.Tenant tenants */ 1:
                    message.tenants.push(Tenant.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* entryvine.common.PageMeta meta */ 2:
                    message.meta = PageMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListTenantsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated entryvine.tenant.Tenant tenants = 1; */
        for (let i = 0; i < message.tenants.length; i++)
            Tenant.internalBinaryWrite(message.tenants[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* entryvine.common.PageMeta meta = 2; */
        if (message.meta)
            PageMeta.internalBinaryWrite(message.meta, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.ListTenantsResponse
 */
export const ListTenantsResponse = new ListTenantsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PublicTenant$Type extends MessageType<PublicTenant> {
    constructor() {
        super("entryvine.tenant.PublicTenant", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PublicTenant>): PublicTenant {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<PublicTenant>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PublicTenant): PublicTenant {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PublicTenant, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.PublicTenant
 */
export const PublicTenant = new PublicTenant$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListPublicTenantsResponse$Type extends MessageType<ListPublicTenantsResponse> {
    constructor() {
        super("entryvine.tenant.ListPublicTenantsResponse", [
            { no: 1, name: "tenants", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PublicTenant }
        ]);
    }
    create(value?: PartialMessage<ListPublicTenantsResponse>): ListPublicTenantsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tenants = [];
        if (value !== undefined)
            reflectionMergePartial<ListPublicTenantsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListPublicTenantsResponse): ListPublicTenantsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated entryvine.tenant.PublicTenant tenants */ 1:
                    message.tenants.push(PublicTenant.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListPublicTenantsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated entryvine.tenant.PublicTenant tenants = 1; */
        for (let i = 0; i < message.tenants.length; i++)
            PublicTenant.internalBinaryWrite(message.tenants[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.ListPublicTenantsResponse
 */
export const ListPublicTenantsResponse = new ListPublicTenantsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TenantMember$Type extends MessageType<TenantMember> {
    constructor() {
        super("entryvine.tenant.TenantMember", [
            { no: 1, name: "users_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "role", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TenantMember>): TenantMember {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.usersId = "";
        message.email = "";
        message.role = 0;
        message.displayName = "";
        if (value !== undefined)
            reflectionMergePartial<TenantMember>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TenantMember): TenantMember {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string users_id */ 1:
                    message.usersId = reader.string();
                    break;
                case /* string email */ 2:
                    message.email = reader.string();
                    break;
                case /* int32 role */ 3:
                    message.role = reader.int32();
                    break;
                case /* string display_name */ 4:
                    message.displayName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TenantMember, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string users_id = 1; */
        if (message.usersId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.usersId);
        /* string email = 2; */
        if (message.email !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.email);
        /* int32 role = 3; */
        if (message.role !== 0)
            writer.tag(3, WireType.Varint).int32(message.role);
        /* string display_name = 4; */
        if (message.displayName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.displayName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.TenantMember
 */
export const TenantMember = new TenantMember$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListTenantMembersResponse$Type extends MessageType<ListTenantMembersResponse> {
    constructor() {
        super("entryvine.tenant.ListTenantMembersResponse", [
            { no: 1, name: "members", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TenantMember }
        ]);
    }
    create(value?: PartialMessage<ListTenantMembersResponse>): ListTenantMembersResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.members = [];
        if (value !== undefined)
            reflectionMergePartial<ListTenantMembersResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListTenantMembersResponse): ListTenantMembersResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated entryvine.tenant.TenantMember members */ 1:
                    message.members.push(TenantMember.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListTenantMembersResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated entryvine.tenant.TenantMember members = 1; */
        for (let i = 0; i < message.members.length; i++)
            TenantMember.internalBinaryWrite(message.members[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.ListTenantMembersResponse
 */
export const ListTenantMembersResponse = new ListTenantMembersResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TenantStripeStatus$Type extends MessageType<TenantStripeStatus> {
    constructor() {
        super("entryvine.tenant.TenantStripeStatus", [
            { no: 1, name: "tenants_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "stripe_connected_account_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "charges_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "payouts_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "details_submitted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TenantStripeStatus>): TenantStripeStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tenantsId = "";
        message.stripeConnectedAccountId = "";
        message.chargesEnabled = false;
        message.payoutsEnabled = false;
        message.detailsSubmitted = false;
        if (value !== undefined)
            reflectionMergePartial<TenantStripeStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TenantStripeStatus): TenantStripeStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tenants_id */ 1:
                    message.tenantsId = reader.string();
                    break;
                case /* string stripe_connected_account_id */ 2:
                    message.stripeConnectedAccountId = reader.string();
                    break;
                case /* bool charges_enabled */ 3:
                    message.chargesEnabled = reader.bool();
                    break;
                case /* bool payouts_enabled */ 4:
                    message.payoutsEnabled = reader.bool();
                    break;
                case /* bool details_submitted */ 5:
                    message.detailsSubmitted = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TenantStripeStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tenants_id = 1; */
        if (message.tenantsId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tenantsId);
        /* string stripe_connected_account_id = 2; */
        if (message.stripeConnectedAccountId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.stripeConnectedAccountId);
        /* bool charges_enabled = 3; */
        if (message.chargesEnabled !== false)
            writer.tag(3, WireType.Varint).bool(message.chargesEnabled);
        /* bool payouts_enabled = 4; */
        if (message.payoutsEnabled !== false)
            writer.tag(4, WireType.Varint).bool(message.payoutsEnabled);
        /* bool details_submitted = 5; */
        if (message.detailsSubmitted !== false)
            writer.tag(5, WireType.Varint).bool(message.detailsSubmitted);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message entryvine.tenant.TenantStripeStatus
 */
export const TenantStripeStatus = new TenantStripeStatus$Type();
/**
 * @generated ServiceType for protobuf service entryvine.tenant.TenantService
 */
export const TenantService = new ServiceType("entryvine.tenant.TenantService", [
    { name: "CreateTenant", options: {}, I: CreateTenantRequest, O: CreateTenantResponse },
    { name: "UpdateTenant", options: {}, I: UpdateTenantRequest, O: AckResponse },
    { name: "ArchiveTenant", options: {}, I: UuidValue, O: AckResponse },
    { name: "GetTenant", options: {}, I: UuidValue, O: Tenant },
    { name: "GetMyTenant", options: {}, I: Empty, O: Tenant },
    { name: "UpdateMyTenantContact", options: {}, I: UpdateMyTenantContactRequest, O: AckResponse },
    { name: "UpdateMyTenantBranding", options: {}, I: UpdateMyTenantBrandingRequest, O: AckResponse },
    { name: "GetPublicTenantBranding", options: {}, I: PublicTenantBrandingRequest, O: PublicTenantBranding },
    { name: "ListTenants", options: {}, I: PageRequest, O: ListTenantsResponse },
    { name: "ListPublicTenants", options: {}, I: Empty, O: ListPublicTenantsResponse },
    { name: "ListTenantMembers", options: {}, I: UuidValue, O: ListTenantMembersResponse },
    { name: "GetTenantStripeStatus", options: {}, I: UuidValue, O: TenantStripeStatus },
    { name: "GetTenantStripeProfile", options: {}, I: UuidValue, O: TenantStripeProfile },
    { name: "UpdateTenantStripeProfile", options: {}, I: UpdateTenantStripeProfileRequest, O: AckResponse }
]);
